INSERT INTO %dbprefix%language_master(language_name, is_rtl, is_default, is_loaded) VALUES ('arabic',1,0,1);
INSERT INTO %dbprefix%language_data (l_name, l_index, l_value, file_name) VALUES
( 'arabic', 'cal_su', 'له', 'calendar_lang.php'),
( 'arabic', 'cal_mo', 'أنت', 'calendar_lang.php'),
( 'arabic', 'cal_tu', 'ك', 'calendar_lang.php'),
( 'arabic', 'cal_we', 'نحن', 'calendar_lang.php'),
( 'arabic', 'cal_th', 'ث', 'calendar_lang.php'),
( 'arabic', 'cal_fr', 'الاب', 'calendar_lang.php'),
( 'arabic', 'cal_sa', 'لها', 'calendar_lang.php'),
( 'arabic', 'cal_sun', 'شمس', 'calendar_lang.php'),
( 'arabic', 'cal_tue', 'الثلاثاء', 'calendar_lang.php'),
( 'arabic', 'cal_thu', 'جمع', 'calendar_lang.php'),
( 'arabic', 'cal_wed', 'تزوج', 'calendar_lang.php'),
( 'arabic', 'cal_mon', 'الإثنين', 'calendar_lang.php'),
( 'arabic', 'cal_fri', 'الجمعة', 'calendar_lang.php'),
( 'arabic', 'cal_sat', 'جلسنا', 'calendar_lang.php'),
( 'arabic', 'cal_sunday', 'الأحد', 'calendar_lang.php'),
( 'arabic', 'cal_monday', 'الإثنين', 'calendar_lang.php'),
( 'arabic', 'cal_tuesday', 'الثلاثاء', 'calendar_lang.php'),
( 'arabic', 'cal_wednesday', 'الأربعاء', 'calendar_lang.php'),
( 'arabic', 'cal_thursday', 'الخميس', 'calendar_lang.php'),
( 'arabic', 'cal_friday', 'يوم الجمعة', 'calendar_lang.php'),
( 'arabic', 'cal_saturday', 'يوم السبت', 'calendar_lang.php'),
( 'arabic', 'cal_jan', 'يناير', 'calendar_lang.php'),
( 'arabic', 'cal_feb', 'فبراير', 'calendar_lang.php'),
( 'arabic', 'cal_mar', 'مارس', 'calendar_lang.php'),
( 'arabic', 'cal_may', 'قد', 'calendar_lang.php'),
( 'arabic', 'cal_apr', 'أبريل', 'calendar_lang.php'),
( 'arabic', 'cal_jun', 'يونيو', 'calendar_lang.php'),
( 'arabic', 'cal_jul', 'يوليو', 'calendar_lang.php'),
( 'arabic', 'cal_sep', 'سبتمبر', 'calendar_lang.php'),
( 'arabic', 'cal_aug', 'أغسطس', 'calendar_lang.php'),
( 'arabic', 'cal_oct', 'أكتوبر', 'calendar_lang.php'),
( 'arabic', 'cal_nov', 'نوفمبر', 'calendar_lang.php'),
( 'arabic', 'cal_dec', 'ديسمبر', 'calendar_lang.php'),
( 'arabic', 'cal_january', 'كانون الثاني', 'calendar_lang.php'),
( 'arabic', 'cal_april', 'أبريل', 'calendar_lang.php'),
( 'arabic', 'cal_march', 'مارس', 'calendar_lang.php'),
( 'arabic', 'cal_february', 'شهر فبراير', 'calendar_lang.php'),
( 'arabic', 'cal_mayl', 'قد', 'calendar_lang.php'),
( 'arabic', 'cal_june', 'يونيو', 'calendar_lang.php'),
( 'arabic', 'cal_september', 'سبتمبر', 'calendar_lang.php'),
( 'arabic', 'cal_october', 'شهر اكتوبر', 'calendar_lang.php'),
( 'arabic', 'cal_august', 'أغسطس', 'calendar_lang.php'),
( 'arabic', 'cal_july', 'يوليو', 'calendar_lang.php'),
( 'arabic', 'cal_november', 'شهر نوفمبر', 'calendar_lang.php'),
( 'arabic', 'cal_december', 'ديسمبر', 'calendar_lang.php'),
( 'arabic', 'date_year', 'عام', 'date_lang.php'),
( 'arabic', 'date_month', 'شهر', 'date_lang.php'),
( 'arabic', 'date_years', 'سنوات', 'date_lang.php'),
( 'arabic', 'date_week', 'أسبوع', 'date_lang.php'),
( 'arabic', 'date_months', 'الشهور', 'date_lang.php'),
( 'arabic', 'date_weeks', 'أسابيع', 'date_lang.php'),
( 'arabic', 'date_day', 'يوم', 'date_lang.php'),
( 'arabic', 'date_days', 'أيام', 'date_lang.php'),
( 'arabic', 'date_hours', 'ساعات', 'date_lang.php'),
( 'arabic', 'date_hour', 'ساعة', 'date_lang.php'),
( 'arabic', 'date_minute', 'اللحظة', 'date_lang.php'),
( 'arabic', 'date_minutes', 'الدقائق', 'date_lang.php'),
( 'arabic', 'date_second', 'ثانيا', 'date_lang.php'),
( 'arabic', 'UM12', '(UTC -12:00) بيكر / جزيرة هاولاند', 'date_lang.php'),
( 'arabic', 'UM10', '(UTC -10:00) هاواي-أليوتيان، الوقت الرسمي، جزر كوك، تاهيتي', 'date_lang.php'),
( 'arabic', 'date_seconds', 'ثواني', 'date_lang.php'),
( 'arabic', 'UM11', '(UTC -11:00) نيوي', 'date_lang.php'),
( 'arabic', 'UM9', '(UTC -9:00) ألاسكا، وقت قياسي، غامبير، إسلاندس', 'date_lang.php'),
( 'arabic', 'UM95', '(UTC -9:30) جزر ماركيساس', 'date_lang.php'),
( 'arabic', 'UM7', '(UTC -7:00) جبل التوقيت الرسمي', 'date_lang.php'),
( 'arabic', 'UM8', '(UTC -8:00) المحيط الهادي، التوقيت، جزيرة كليبرتون', 'date_lang.php'),
( 'arabic', 'UM6', '(UTC -6:00) الوقت القياسي المركزي', 'date_lang.php'),
( 'arabic', 'UM5', '(UTC -5:00) التوقيت الشرقي, التوقيت الكاريبي الغربي', 'date_lang.php'),
( 'arabic', 'UM45', '(UTC -4:30) التوقيت الفنزويلي', 'date_lang.php'),
( 'arabic', 'UM4', '(UTC -4:00) الأطلسي التوقيت القياسي, التوقيت الشرقي لبحر الكاريبي', 'date_lang.php'),
( 'arabic', 'UM35', '(UTC -3:30) نيوفاوندلاند وقت قياسي', 'date_lang.php'),
( 'arabic', 'UM3', '(UTC -3:00) الأرجنتين, البرازيل, غيانا الفرنسية, أوروغواي', 'date_lang.php'),
( 'arabic', 'UM2', '(UTC -2:00) جورجيا الجنوبية / جزر ساندويتش الجنوبية', 'date_lang.php'),
( 'arabic', 'UM1', '(UTC -1:00) الأزور, جزر الرأس الأخضر', 'date_lang.php'),
( 'arabic', 'UTC', '(UTC) توقيت غرينيتش, توقيت أوروبا الغربية', 'date_lang.php'),
( 'arabic', 'UP2', '(UTC +2:00) توقيت أفريقيا الوسطى, توقيت أوروبا الشرقية, كالينينغراد الوقت', 'date_lang.php'),
( 'arabic', 'UP1', '(UTC +1:00) توقيت وسط أوروبا, غرب أفريقيا الوقت', 'date_lang.php'),
( 'arabic', 'UP3', '(UTC +3:00) توقيت موسكو, شرق أفريقيا الوقت, العربية التوقيت الرسمي', 'date_lang.php'),
( 'arabic', 'UP35', '(UTC +3:30) إيران التوقيت الرسمي', 'date_lang.php'),
( 'arabic', 'UP4', '(UTC +4:00) أذربيجان التوقيت الرسمي, سمارة الوقت', 'date_lang.php'),
( 'arabic', 'UP45', '(UTC +4:30) أفغانستان', 'date_lang.php'),
( 'arabic', 'UP5', '(UTC +5:00) باكستان التوقيت الرسمي, يكاترينبورغ الوقت', 'date_lang.php'),
( 'arabic', 'UP575', '(UTC +5:45) نيبال', 'date_lang.php'),
( 'arabic', 'UP55', '(UTC +5:30) توقيت الهند القياسية, سريلانكا الوقت', 'date_lang.php'),
( 'arabic', 'UP6', '(UTC +6:00) بنغلاديش التوقيت الرسمي, توقيت بوتان, أومسك الوقت', 'date_lang.php'),
( 'arabic', 'UP65', '(UTC +6:30) جزر كوكوس, ميانمار', 'date_lang.php'),
( 'arabic', 'UP7', '(UTC +7:00) كراسنويارسك الوقت, كمبوديا, لاوس, تايلاند, فيتنام', 'date_lang.php'),
( 'arabic', 'UP8', '(UTC +8:00) التوقيت الغربي الغربي الأسترالي, بتوقيت بكين، وقت إيركوتسك', 'date_lang.php'),
( 'arabic', 'UP875', '(UTC +8:45) التوقيت المركزي الغربي الاسترالي', 'date_lang.php'),
( 'arabic', 'UP9', '(UTC +9:00) اليابان التوقيت الرسمي, كوريا التوقيت الرسمي, ياكوتسك الوقت', 'date_lang.php'),
( 'arabic', 'UP95', '(UTC +9:30) التوقيت المركزي المركزي الأسترالي', 'date_lang.php'),
( 'arabic', 'UP105', '(UTC +10:30) جزيرة لورد هاو', 'date_lang.php'),
( 'arabic', 'UP10', '(UTC +10:00) التوقيت الشرقي الشرقي الأسترالي, فلاديفوستوك الوقت', 'date_lang.php'),
( 'arabic', 'UP11', '(UTC +11:00) سريدنيكوليمسك الموضوع, جزر سليمان, فانواتو', 'date_lang.php'),
( 'arabic', 'UP115', '(UTC +11:30) جزيرة نورفولك', 'date_lang.php'),
( 'arabic', 'UP12', '(UTC +12:00) فيجي, جزر جيلبرت, وقت كامتشاتكا, نيوزيلندا التوقيت الرسمي', 'date_lang.php'),
( 'arabic', 'UP14', '(UTC +14:00) جزر الخط', 'date_lang.php'),
( 'arabic', 'UP1275', '(UTC +12:45) جزر شاتام التوقيت الرسمي', 'date_lang.php'),
( 'arabic', 'UP13', '(UTC +13:00) ساموا المنطقة الزمنية, جزر فينيكس الوقت, تونغا', 'date_lang.php'),
( 'arabic', 'db_invalid_connection_str', 'يتعذر تحديد إعدادات قاعدة البيانات استنادا إلى سلسلة الاتصال التي أرسلتها.', 'db_lang.php'),
( 'arabic', 'db_unable_to_connect', 'تعذر الاتصال بخادم قاعدة البيانات باستخدام الإعدادات المتوفرة.', 'db_lang.php'),
( 'arabic', 'db_unable_to_select', 'تعذر تحديد قاعدة البيانات المحددة:٪ s', 'db_lang.php'),
( 'arabic', 'db_unable_to_create', 'تعذر إنشاء قاعدة البيانات المحددة:٪ s', 'db_lang.php'),
( 'arabic', 'db_invalid_query', 'طلب البحث الذي أرسلته غير صالح.', 'db_lang.php'),
( 'arabic', 'db_must_set_table', 'يجب تعيين جدول قاعدة البيانات ليتم استخدامه مع الاستعلام الخاص بك.', 'db_lang.php'),
( 'arabic', 'db_must_use_index', 'يجب تحديد فهرس لمطابقته لتحديثات الدفعات.', 'db_lang.php'),
( 'arabic', 'db_must_use_set', 'يجب استخدام الأسلوب "سيت" لتحديث إدخال.', 'db_lang.php'),
( 'arabic', 'db_batch_missing_index', 'يفتقد صف واحد أو أكثر يتم إرساله لتحديث الدفعة الفهرس المحدد.', 'db_lang.php'),
( 'arabic', 'db_must_use_where', 'لا يسمح بالتحديثات إلا إذا كانت تحتوي على شرط "حيث".', 'db_lang.php'),
( 'arabic', 'db_del_must_use_where', 'لا يسمح بالحذف ما لم تحتوي على شرط "حيث" أو "أعجبني".', 'db_lang.php'),
( 'arabic', 'db_transaction_failure', 'فشل المعاملة: تمت عملية التراجع.', 'db_lang.php'),
( 'arabic', 'db_field_param_missing', 'يتطلب جلب الحقول اسم الجدول كمعلمة.', 'db_lang.php'),
( 'arabic', 'db_unsupported_function', 'هذه الميزة غير متوفرة لقاعدة البيانات التي تستخدمها.', 'db_lang.php'),
( 'arabic', 'db_unable_to_drop', 'تعذر إسقاط قاعدة البيانات المحددة.', 'db_lang.php'),
( 'arabic', 'db_unsupported_feature', 'ميزة غير مدعومة من منصة قاعدة البيانات التي تستخدمها.', 'db_lang.php'),
( 'arabic', 'db_unsupported_compression', 'تنسيق ضغط الملف الذي اخترته غير مدعوم من قبل الخادم.', 'db_lang.php'),
( 'arabic', 'db_filepath_error', 'يتعذر كتابة البيانات إلى مسار الملف الذي أرسلته.', 'db_lang.php'),
( 'arabic', 'db_table_name_required', 'اسم جدول مطلوب لهذه العملية.', 'db_lang.php'),
( 'arabic', 'db_invalid_cache_path', 'مسار ذاكرة التخزين المؤقت الذي أرسلته غير صالح أو قابل للكتابة.', 'db_lang.php'),
( 'arabic', 'db_column_name_required', 'مطلوب اسم عمود لهذه العملية.', 'db_lang.php'),
( 'arabic', 'db_column_definition_required', 'مطلوب تعريف عمود لهذه العملية.', 'db_lang.php'),
( 'arabic', 'db_error_heading', 'حدث خطأ في قاعدة البيانات', 'db_lang.php'),
( 'arabic', 'db_unable_to_set_charset', 'تعذر تعيين مجموعة أحرف اتصال العميل:٪ s', 'db_lang.php'),
( 'arabic', 'email_must_be_array', 'يجب أن يتم تمرير طريقة التحقق من صحة البريد الإلكتروني مصفوفة.', 'email_lang.php'),
( 'arabic', 'email_invalid_address', 'عنوان البريد الإلكتروني غير صالح:٪ s', 'email_lang.php'),
( 'arabic', 'email_attachment_missing', 'تعذر تحديد موقع مرفق البريد الإلكتروني التالي:٪ s', 'email_lang.php'),
( 'arabic', 'email_attachment_unreadable', 'تعذر فتح هذا المرفق:٪ s', 'email_lang.php'),
( 'arabic', 'email_no_from', 'لا يمكن إرسال البريد بدون رأس "من".', 'email_lang.php'),
( 'arabic', 'email_no_recipients', 'يجب تضمين المستلمين: إلى أو نسخة إلى أو نسخة مخفية الوجهة', 'email_lang.php'),
( 'arabic', 'email_send_failure_phpmail', 'تعذر إرسال البريد الإلكتروني باستخدام بريد فب (). قد لا تتم تهيئة الخادم لإرسال البريد باستخدام هذه الطريقة.', 'email_lang.php'),
( 'arabic', 'email_send_failure_sendmail', 'تعذر إرسال البريد الإلكتروني باستخدام فب سيندمايل. قد لا تتم تهيئة الخادم لإرسال البريد باستخدام هذه الطريقة.', 'email_lang.php'),
( 'arabic', 'email_sent', 'تم إرسال رسالتك بنجاح باستخدام البروتوكول التالي:٪ s', 'email_lang.php'),
( 'arabic', 'email_send_failure_smtp', 'تعذر إرسال البريد الإلكتروني باستخدام فب سمتب. قد لا تتم تهيئة الخادم لإرسال البريد باستخدام هذه الطريقة.', 'email_lang.php'),
( 'arabic', 'email_no_hostname', 'لم تحدد اسم مضيف سمتب.', 'email_lang.php'),
( 'arabic', 'email_no_socket', 'تعذر فتح مأخذ توصيل إلى سيندمايل. يرجى التحقق من الإعدادات.', 'email_lang.php'),
( 'arabic', 'email_smtp_error', 'حدث خطأ سمتب التالي:٪ s', 'email_lang.php'),
( 'arabic', 'email_no_smtp_unpw', 'خطأ: يجب تعيين اسم مستخدم وكلمة مرور سمتب.', 'email_lang.php'),
( 'arabic', 'email_smtp_auth_un', 'أخفق مصادقة اسم المستخدم. خطأ:٪ s', 'email_lang.php'),
( 'arabic', 'email_smtp_auth_pw', 'أخفق مصادقة كلمة المرور. خطأ:٪ s', 'email_lang.php'),
( 'arabic', 'email_smtp_data_failure', 'تعذر إرسال البيانات:٪ s', 'email_lang.php'),
( 'arabic', 'email_failed_smtp_login', 'أخفق إرسال أمر أوث لوجين. خطأ:٪ s', 'email_lang.php'),
( 'arabic', 'email_exit_status', 'رمز حالة الخروج:٪ s', 'email_lang.php'),
( 'arabic', 'form_validation_isset', 'يجب أن يكون للحقل {فيلد} قيمة.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_valid_email', 'يجب أن يحتوي حقل {فيلد} على عنوان بريد إلكتروني صالح.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_required', 'حقل {فيلد} مطلوب.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_valid_emails', 'يجب أن يحتوي الحقل {فيلد} على جميع عناوين البريد الإلكتروني الصالحة.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_valid_url', 'يجب أن يحتوي حقل {فيلد} على عنوان ورل صالح.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_valid_ip', 'يجب أن يحتوي حقل {فيلد} على إب صالح.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_min_length', 'يجب أن يكون حقل {فيلد} على الأقل {بارام} حرفا.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_exact_length', 'يجب أن يكون الحقل {فيلد} بالضبط {بارام} حرفا.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_max_length', 'لا يمكن أن يتجاوز الحقل {فيلد} {بارام} حرفا في الطول.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_alpha', 'قد يحتوي حقل {فيلد} على أحرف أبجدية فقط.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_alpha_numeric', 'قد يحتوي الحقل {فيلد} على أحرف أبجدية رقمية فقط.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_alpha_numeric_spaces', 'قد يحتوي الحقل {فيلد} على أحرف وأرقام فراغية رقمية فقط.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_alpha_dash', 'قد يحتوي حقل {فيلد} على أحرف أبجدية رقمية وشرطات سفلية وشرطات.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_numeric', 'يجب أن يحتوي الحقل {فيلد} على أرقام فقط.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_is_numeric', 'يجب أن يحتوي الحقل {فيلد} على أحرف رقمية فقط.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_integer', 'يجب أن يحتوي الحقل {فيلد} على عدد صحيح.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_regex_match', 'حقل {فيلد} ليس بالتنسيق الصحيح.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_differs', 'يجب أن يختلف الحقل {فيلد} عن الحقل {بارام}.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_is_unique', 'يجب أن يحتوي الحقل {فيلد} على قيمة فريدة.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_matches', 'لا يتطابق حقل {فيلد} مع الحقل {بارام}.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_is_natural', 'يجب أن يحتوي الحقل {فيلد} على أرقام فقط.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_is_natural_no_zero', 'يجب أن يحتوي الحقل {فيلد} على أرقام فقط ويجب أن يكون أكبر من الصفر.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_decimal', 'يجب أن يحتوي الحقل {فيلد} على رقم عشري.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_less_than', 'يجب أن يحتوي الحقل {فيلد} على رقم أقل من {بارام}.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_less_than_equal_to', 'يجب أن يحتوي الحقل {فيلد} على رقم أقل من أو يساوي {بارام}..', 'form_validation_lang.php'),
( 'arabic', 'form_validation_greater_than', 'يجب أن يحتوي الحقل {فيلد} على رقم أكبر من {بارام}.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_greater_than_equal_to', 'يجب أن يحتوي حقل {فيلد} على رقم أكبر من أو يساوي {بارام}.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_error_message_not_set', 'تعذر الوصول إلى رسالة خطأ تطابق اسم الحقل {فيلد}.', 'form_validation_lang.php'),
( 'arabic', 'form_validation_in_list', 'يجب أن يكون حقل {فيلد} واحدا من: {بارام}.', 'form_validation_lang.php'),
( 'arabic', 'ftp_no_connection', 'يتعذر تحديد موقع معرف اتصال صالح. يرجى التأكد من أنك متصل قبل تنفيذ أي إجراءات ملف.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_connect', 'تعذر الاتصال بخادم فتب باستخدام اسم المضيف المرفق.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_login', 'تعذر تسجيل الدخول إلى خادم فتب. يرجى التحقق من اسم المستخدم وكلمة المرور.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_chmod', 'تعذر تعيين أذونات الملف. يرجى التحقق من المسار الخاص بك.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_mkdir', 'تعذر إنشاء الدليل الذي حددته.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_changedir', 'تعذر إنشاء الدليل الذي حددته.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_upload', 'تعذر تحميل الملف المحدد. يرجى التحقق من المسار الخاص بك.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_download', 'تعذر تنزيل الملف المحدد. يرجى التحقق من المسار الخاص بك.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_rename', 'يتعذر إعادة تسمية الملف.', 'ftp_lang.php'),
( 'arabic', 'ftp_no_source_file', 'تعذر تحديد موقع الملف المصدر. يرجى التحقق من المسار الخاص بك.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_delete', 'تعذر حذف الملف.', 'ftp_lang.php'),
( 'arabic', 'ftp_unable_to_move', 'تعذر نقل الملف. الرجاء التأكد من وجود دليل الوجهة.', 'ftp_lang.php'),
( 'arabic', 'imglib_source_image_required', 'يجب تحديد صورة مصدر في تفضيلاتك.', 'imglib_lang.php'),
( 'arabic', 'imglib_gd_required', 'مطلوب مكتبة الصور غ لهذه الميزة.', 'imglib_lang.php'),
( 'arabic', 'imglib_gd_required_for_props', 'يجب أن يدعم الخادم مكتبة صورة غ لتحديد خصائص الصورة.', 'imglib_lang.php'),
( 'arabic', 'imglib_unsupported_imagecreate', 'لا يدعم الخادم وظيفة غ المطلوبة لمعالجة هذا النوع من الصور.', 'imglib_lang.php'),
( 'arabic', 'imglib_gif_not_supported', 'غالبا ما تكون صور جيف غير مدعومة بسبب قيود الترخيص. قد تضطر إلى استخدام الصور جبغ أو ينغ بدلا من ذلك.', 'imglib_lang.php'),
( 'arabic', 'imglib_jpg_not_supported', 'لا تتوفر صور جبغ.', 'imglib_lang.php'),
( 'arabic', 'imglib_png_not_supported', 'لا يتم دعم الصور ينغ.', 'imglib_lang.php'),
( 'arabic', 'imglib_copy_error', 'حدث خطأ أثناء محاولة استبدال الملف. الرجاء التأكد من أن دليل الملف قابل للكتابة.', 'imglib_lang.php'),
( 'arabic', 'imglib_jpg_or_png_required', 'لا يعمل بروتوكول تغيير حجم الصورة المحدد في تفضيلاتك إلا مع أنواع صور جبيغ أو ينغ.', 'imglib_lang.php'),
( 'arabic', 'imglib_rotate_unsupported', 'لا يبدو دوران الصورة مدعوما بخادمك.', 'imglib_lang.php'),
( 'arabic', 'imglib_libpath_invalid', 'المسار إلى مكتبة الصور ليس صحيحا. يرجى تعيين المسار الصحيح في تفضيلات الصورة.', 'imglib_lang.php'),
( 'arabic', 'imglib_image_process_failed', 'أخفقت معالجة الصور. الرجاء التحقق من أن الخادم يدعم البروتوكول المختار وأن المسار إلى مكتبة الصور الخاصة بك هو الصحيح.', 'imglib_lang.php'),
( 'arabic', 'imglib_rotation_angle_required', 'مطلوب زاوية دوران لتدوير الصورة.', 'imglib_lang.php'),
( 'arabic', 'imglib_invalid_path', 'المسار إلى صورة غير صحيح.', 'imglib_lang.php'),
( 'arabic', 'imglib_copy_failed', 'أخفق روتين نسخ الصورة.', 'imglib_lang.php'),
( 'arabic', 'imglib_missing_font', 'تعذر العثور على خط لاستخدامه.', 'imglib_lang.php'),
( 'arabic', 'imglib_save_failed', 'تعذر حفظ الصورة. الرجاء التأكد من أن ملف الصور والملفات قابل للكتابة.', 'imglib_lang.php'),
( 'arabic', 'app_name', 'Chikitsa', 'main_lang.php'),
( 'arabic', 'app_tagline', 'نظام إدارة العيادة', 'main_lang.php'),
( 'arabic', 'main_title', 'Chikitsa - نظام إدارة العيادة', 'main_lang.php'),
( 'arabic', 'cmp_version', 'Chikitsa الإصدار', 'main_lang.php'),
( 'arabic', 'cmp_name', 'Sanskruti تكنولوجيز', 'main_lang.php'),
( 'arabic', 'about_chikitsa', 'حول شيكانغا ', 'main_lang.php'),
( 'arabic', 'sign_in', 'تسجيل الدخول', 'main_lang.php'),
( 'arabic', '5min', '5 دقائق', 'main_lang.php'),
( 'arabic', '7min', '7 دقيقة', 'main_lang.php'),
( 'arabic', '15min', '15 دقيقة', 'main_lang.php'),
( 'arabic', '30min', '30 دقيقة', 'main_lang.php'),
( 'arabic', '1hr', 'ساعة واحدة', 'main_lang.php'),
( 'arabic', 'main_section', 'القسم الرئيسي', 'main_lang.php'),
( 'arabic', 'second_section', 'القسم الثاني', 'main_lang.php'),
( 'arabic', 'third_section', 'القسم الثالث', 'main_lang.php'),
( 'arabic', 'background_color', 'لون الخلفية', 'main_lang.php'),
( 'arabic', 'title_color', 'لون العنوان', 'main_lang.php'),
( 'arabic', 'text_color', 'لون النص', 'main_lang.php'),
( 'arabic', 'about', 'حول', 'main_lang.php'),
( 'arabic', 'about_settings', 'حول الإعدادات', 'main_lang.php'),
( 'arabic', 'about_page_settings', 'حول إعدادات الصفحة', 'main_lang.php'),
( 'arabic', 'access_on_menu', 'الوصول على القائمة', 'main_lang.php'),
( 'arabic', 'access_code', 'رمز الدخول', 'main_lang.php'),
( 'arabic', 'account_group_master', 'حساب مجموعة ماستر', 'main_lang.php'),
( 'arabic', 'account_details_meta', 'تفاصيل الحساب', 'main_lang.php'),
( 'arabic', 'account_group', 'جماعة حساب', 'main_lang.php'),
( 'arabic', 'account_group_name', 'اسم مجموعة الحساب', 'main_lang.php'),
( 'arabic', 'account_group_order', 'أمر مجموعة الحساب', 'main_lang.php'),
( 'arabic', 'account_groups', 'مجموعات الحساب', 'main_lang.php'),
( 'arabic', 'accounts', 'حسابات', 'main_lang.php'),
( 'arabic', 'account', 'الحساب', 'main_lang.php'),
( 'arabic', 'action', 'عمل', 'main_lang.php'),
( 'arabic', 'actions', 'أفعال', 'main_lang.php'),
( 'arabic', 'amount', 'كمية', 'main_lang.php'),
( 'arabic', 'activate', 'تفعيل', 'main_lang.php'),
( 'arabic', 'add', 'إضافة', 'main_lang.php'),
( 'arabic', 'add_condition', 'إضافة شرط', 'main_lang.php'),
( 'arabic', 'available_quantity', 'الكمية المتاحة', 'main_lang.php'),
( 'arabic', 'additional_css', 'CSS إضافية', 'main_lang.php'),
( 'arabic', 'add_another_medicine', 'إضافة دواء آخر', 'main_lang.php'),
( 'arabic', 'add_slider', 'أضف منزلق', 'main_lang.php'),
( 'arabic', 'add_alerts', 'إضافة تنبيهات', 'main_lang.php'),
( 'arabic', 'add_about_page_post', 'إضافة حول نشر الصفحة', 'main_lang.php'),
( 'arabic', 'add_appointment', 'إضافة موعد', 'main_lang.php'),
( 'arabic', 'add_footer_section', 'إضافة قسم تذييل الصفحة', 'main_lang.php'),
( 'arabic', 'add_footer_credit', 'إضافة قسم الائتمان تذييل', 'main_lang.php'),
( 'arabic', 'add_image', 'إضافة صورة جديدة', 'main_lang.php'),
( 'arabic', 'add_category', 'إضافة فئة', 'main_lang.php'),
( 'arabic', 'add_top_section', 'إضافة القسم العلوي', 'main_lang.php'),
( 'arabic', 'add_department', 'إضافة قسم', 'main_lang.php'),
( 'arabic', 'add_detail', 'السماح لإضافة التفاصيل', 'main_lang.php'),
( 'arabic', 'add_from_users', 'أضف من المستخدمين', 'main_lang.php'),
( 'arabic', 'add_more_contact_number', 'أضف المزيد', 'main_lang.php'),
( 'arabic', 'add_news', 'أضف الأخبار', 'main_lang.php'),
( 'arabic', 'add_new_user', 'إضافة مستخدم جديد', 'main_lang.php'),
( 'arabic', 'add_inquiry', 'إضافة رسالتك', 'main_lang.php'),
( 'arabic', 'add_as_medicine', 'أضف كدواء', 'main_lang.php'),
( 'arabic', 'add_test', 'إضافة اختبار', 'main_lang.php'),
( 'arabic', 'add_service', 'أضف خدمة', 'main_lang.php'),
( 'arabic', 'add_section', 'إضافة قسم', 'main_lang.php'),
( 'arabic', 'add_treatment', 'أضف العلاج', 'main_lang.php'),
( 'arabic', 'add_reference_by', 'إضافة مرجع بواسطة', 'main_lang.php'),
( 'arabic', 'add_refund', 'إضافة رد', 'main_lang.php'),
( 'arabic', 'add_user', 'أضف المستخدم', 'main_lang.php'),
( 'arabic', 'add_language', 'إضافة لغة', 'main_lang.php'),
( 'arabic', 'add_bottom_section', 'إضافة القسم السفلي', 'main_lang.php'),
( 'arabic', 'add_fee', 'إضافة رسوم', 'main_lang.php'),
( 'arabic', 'add_extension', 'إضافة ملحقات', 'main_lang.php'),
( 'arabic', 'add_patient', 'أضف المريض', 'main_lang.php'),
( 'arabic', 'add_license_key', 'إضافة مفتاح الترخيص', 'main_lang.php'),
( 'arabic', 'add_payment', 'نصف الدفع', 'main_lang.php'),
( 'arabic', 'address', 'عنوان', 'main_lang.php'),
( 'arabic', 'added_date', 'تاريخ الاضافة', 'main_lang.php'),
( 'arabic', 'addresstype', 'نوع العنوان', 'main_lang.php'),
( 'arabic', 'address_line_2', 'سطر العنوان 2', 'main_lang.php'),
( 'arabic', 'address_line_1', 'العنوان الأول', 'main_lang.php'),
( 'arabic', 'administration', 'الادارة', 'main_lang.php'),
( 'arabic', 'adult_teeth', 'أسنان البالغين', 'main_lang.php'),
( 'arabic', 'appointment_calendar', 'موعد التقويم', 'main_lang.php'),
( 'arabic', 'administrator', 'مدير', 'main_lang.php'),
( 'arabic', 'amount_paid', 'المبلغ المدفوع', 'main_lang.php'),
( 'arabic', 'admin_log_in', 'دخول المشرف', 'main_lang.php'),
( 'arabic', 'afternoon', 'A', 'main_lang.php'),
( 'arabic', 'afternoon_time', 'وقت الظهيرة', 'main_lang.php'),
( 'arabic', 'age', 'عمر', 'main_lang.php'),
( 'arabic', 'after', 'بعد', 'main_lang.php'),
( 'arabic', 'alert_settings', 'تنبيه الإعداد', 'main_lang.php'),
( 'arabic', 'alerts', 'التنبيهات', 'main_lang.php'),
( 'arabic', 'alert_time', 'وقت التنبيه', 'main_lang.php'),
( 'arabic', 'alert_email_log', 'سجل تنبيه البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'alert_name', 'اسم التنبيه', 'main_lang.php'),
( 'arabic', 'alert_sms_log', 'سجل الرسائل القصيرة التنبيه', 'main_lang.php'),
( 'arabic', 'all', 'الكل', 'main_lang.php'),
( 'arabic', 'allot', 'تخصيص', 'main_lang.php'),
( 'arabic', 'allow_menu', 'السماح بالقوائم', 'main_lang.php'),
( 'arabic', 'allocate', 'تخصيص', 'main_lang.php'),
( 'arabic', 'allow_repeat', 'السماح بالتكرار', 'main_lang.php'),
( 'arabic', 'allow_center', 'السماح للمراكز', 'main_lang.php'),
( 'arabic', 'all_sell', 'كل بيع', 'main_lang.php'),
( 'arabic', 'stock_all_sell', 'كل بيع', 'main_lang.php'),
( 'arabic', 'all_users', 'جميع المستخدمين', 'main_lang.php'),
( 'arabic', 'all_patients', 'جميع المرضى', 'main_lang.php'),
( 'arabic', 'all_clinic', 'كل العيادة', 'main_lang.php'),
( 'arabic', 'all_folloups', 'كل متابعة شكا', 'main_lang.php'),
( 'arabic', 'appointment', 'موعد', 'main_lang.php'),
( 'arabic', 'appointment_details', 'تفاصيل المواعيد', 'main_lang.php'),
( 'arabic', 'appointments', 'تعيينات', 'main_lang.php'),
( 'arabic', 'appointment_report', 'تقرير موعد', 'main_lang.php'),
( 'arabic', 'appointment_reason', 'سبب التعيين', 'main_lang.php'),
( 'arabic', 'appointment_time_interval', 'فاصل زمني موعد', 'main_lang.php'),
( 'arabic', 'appointment_date', 'تاريخ التعيين', 'main_lang.php'),
( 'arabic', 'assets', 'الأصول', 'main_lang.php'),
( 'arabic', 'availability', 'توفر', 'main_lang.php'),
( 'arabic', 'available', 'متاح', 'main_lang.php'),
( 'arabic', 'additional_detail_label', 'تسمية إضافية التفاصيل', 'main_lang.php'),
( 'arabic', 'average_price', 'متوسط السعر', 'main_lang.php'),
( 'arabic', 'adjust_from_account', 'ضبط من الحساب', 'main_lang.php'),
( 'arabic', 'available_stock', 'المخزون المتوفر', 'main_lang.php'),
( 'arabic', 'amount_in_account', 'المبلغ في الحساب', 'main_lang.php'),
( 'arabic', 'approve', 'يوافق', 'main_lang.php'),
( 'arabic', 'additional_detail', 'تفاصيل إضافية', 'main_lang.php'),
( 'arabic', 'baby_teeth', 'أسنان الطفل', 'main_lang.php'),
( 'arabic', 'back', 'الى الخلف', 'main_lang.php'),
( 'arabic', 'backup', 'دعم', 'main_lang.php'),
( 'arabic', 'backup_restore', 'اسنرجاع البيانات', 'main_lang.php'),
( 'arabic', 'back_to', 'ارجع الى', 'main_lang.php'),
( 'arabic', 'book_an_appoinment', 'حجز موعد', 'main_lang.php'),
( 'arabic', 'back_to_app', 'العودة إلى موعد', 'main_lang.php'),
( 'arabic', 'back_to_visit', 'العودة الى الزيارة', 'main_lang.php'),
( 'arabic', 'balance', 'توازن', 'main_lang.php'),
( 'arabic', 'balance_amount', 'مقدار وسطي', 'main_lang.php'),
( 'arabic', 'bank_payments', 'المدفوعات المصرفية', 'main_lang.php'),
( 'arabic', 'bank_receipt', 'إيصال البنك', 'main_lang.php'),
( 'arabic', 'bank_payment', 'الدفع المصرفية', 'main_lang.php'),
( 'arabic', 'barcode', 'الرمز الشريطي', 'main_lang.php'),
( 'arabic', 'bank_receipts', 'إيصالات البنك', 'main_lang.php'),
( 'arabic', 'bed', 'السرير', 'main_lang.php'),
( 'arabic', 'before', 'قبل', 'main_lang.php'),
( 'arabic', 'beds', 'سرير', 'main_lang.php'),
( 'arabic', 'bill', 'مشروع قانون', 'main_lang.php'),
( 'arabic', 'bills', 'فواتير', 'main_lang.php'),
( 'arabic', 'bill_amount', 'المبلغ المفوتر', 'main_lang.php'),
( 'arabic', 'bill_details', 'تفاصيل الفاتورة', 'main_lang.php'),
( 'arabic', 'bill_id', 'معرف الفاتورة', 'main_lang.php'),
( 'arabic', 'bill_no', 'مشروع قانون لا.', 'main_lang.php'),
( 'arabic', 'bill_date', 'تاريخ الفاتورة', 'main_lang.php'),
( 'arabic', 'bills_payments', 'دفع', 'main_lang.php'),
( 'arabic', 'bill_number', 'رقم الفاتوره', 'main_lang.php'),
( 'arabic', 'back_to_appointment', 'العودة إلى الموعد', 'main_lang.php'),
( 'arabic', 'back_to_payment', 'العودة إلى الدفع', 'main_lang.php'),
( 'arabic', 'bill_report', 'تقرير الفاتورة', 'main_lang.php'),
( 'arabic', 'bill_type', 'نوع الفاتورة', 'main_lang.php'),
( 'arabic', 'body', 'الجسم', 'main_lang.php'),
( 'arabic', 'bought_at', 'اشترى في', 'main_lang.php'),
( 'arabic', 'bought_avg', 'اشترى متوسط', 'main_lang.php'),
( 'arabic', 'book', 'كتاب', 'main_lang.php'),
( 'arabic', 'bought_quantity', 'اشترى الكمية', 'main_lang.php'),
( 'arabic', 'browse', 'تصفح', 'main_lang.php'),
( 'arabic', 'bottom_section_3', 'الجزء السفلي 3', 'main_lang.php'),
( 'arabic', 'bottom_section_2', 'الجزء السفلي 2', 'main_lang.php'),
( 'arabic', 'button', 'زر', 'main_lang.php'),
( 'arabic', 'bottom_section_1', 'الجزء السفلي 1', 'main_lang.php'),
( 'arabic', 'book_appoinment', 'موعد الكتاب', 'main_lang.php'),
( 'arabic', 'blood_group', 'فصيلة الدم', 'main_lang.php'),
( 'arabic', 'button_text', 'نص الزر', 'main_lang.php'),
( 'arabic', 'button_url', 'عنوان URL للزر', 'main_lang.php'),
( 'arabic', 'bonus_percentage', 'نسبة المكافأة', 'main_lang.php'),
( 'arabic', 'billed', 'فاتورة', 'main_lang.php'),
( 'arabic', 'bonus', 'علاوة', 'main_lang.php'),
( 'arabic', 'calendar', 'التقويم الشهري', 'main_lang.php'),
( 'arabic', 'calendar_hours', 'التقويم اليومي', 'main_lang.php'),
( 'arabic', 'cancelled', 'ألغيت', 'main_lang.php'),
( 'arabic', 'cash', 'السيولة النقدية', 'main_lang.php'),
( 'arabic', 'cancel', 'إلغاء', 'main_lang.php'),
( 'arabic', 'cases', 'الحالات', 'main_lang.php'),
( 'arabic', 'case', 'الحالات', 'main_lang.php'),
( 'arabic', 'case_number', 'القضية رقم.', 'main_lang.php'),
( 'arabic', 'cash_receipt', 'إيصال الدفع', 'main_lang.php'),
( 'arabic', 'cash_payment', 'دفع نقدا', 'main_lang.php'),
( 'arabic', 'cash_receipts', 'المقبوضات النقدية', 'main_lang.php'),
( 'arabic', 'cash_payments', 'التسديد نقذا', 'main_lang.php'),
( 'arabic', 'case_date', 'تاريخ القضيةs', 'main_lang.php'),
( 'arabic', 'category', 'الفئة', 'main_lang.php'),
( 'arabic', 'centers', 'مراكز', 'main_lang.php'),
( 'arabic', 'center_details', 'تفاصيل المركز', 'main_lang.php'),
( 'arabic', 'center', 'مركز', 'main_lang.php'),
( 'arabic', 'categories', 'الاقسام', 'main_lang.php'),
( 'arabic', 'center_logo', 'شعار المركز', 'main_lang.php'),
( 'arabic', 'center_name', 'اسم المركز', 'main_lang.php'),
( 'arabic', 'change_center', 'مركز التغيير', 'main_lang.php'),
( 'arabic', 'change_theme_color', 'إعدادات النسق', 'main_lang.php'),
( 'arabic', 'change', 'يتغيرون', 'main_lang.php'),
( 'arabic', 'center_code', 'رمز المركز', 'main_lang.php'),
( 'arabic', 'change_language', 'غير اللغة', 'main_lang.php'),
( 'arabic', 'change_profile', 'تشانغ الشخصي', 'main_lang.php'),
( 'arabic', 'change_timezone', 'تغيير المنطقة الزمنية', 'main_lang.php'),
( 'arabic', 'change_status_of_field', 'تغيير حالة الحقل', 'main_lang.php'),
( 'arabic', 'change_template', 'تغيير قالب', 'main_lang.php'),
( 'arabic', 'charges_fees', 'الرسوم / الرسوم', 'main_lang.php'),
( 'arabic', 'charges', 'شحنة', 'main_lang.php'),
( 'arabic', 'cheque', 'التحقق من', 'main_lang.php'),
( 'arabic', 'chikitsa_new_version_available', 'Chikitsa النسخة الجديدة المتاحة', 'main_lang.php'),
( 'arabic', 'cheque_number', 'رقم الشيك', 'main_lang.php'),
( 'arabic', 'choose_file', 'اختر ملف', 'main_lang.php'),
( 'arabic', 'city', 'مدينة', 'main_lang.php'),
( 'arabic', 'close', 'قريب', 'main_lang.php'),
( 'arabic', 'clear_data', 'امسح البيانات', 'main_lang.php'),
( 'arabic', 'clinic', 'عيادة', 'main_lang.php'),
( 'arabic', 'clinic_address', 'عنوان العيادة', 'main_lang.php'),
( 'arabic', 'clinic_details', 'تفاصيل العيادة', 'main_lang.php'),
( 'arabic', 'clinic_end_time', 'وقت نهاية العيادة', 'main_lang.php'),
( 'arabic', 'clinic_note', 'ملاحظة العيادة', 'main_lang.php'),
( 'arabic', 'clinic_landline', 'عيادة الخط الأرضي', 'main_lang.php'),
( 'arabic', 'clinic_logo', 'شعار العيادة', 'main_lang.php'),
( 'arabic', 'clinic_phone_1', 'عيادة الهاتف 1', 'main_lang.php'),
( 'arabic', 'clinic_phone_2', 'عيادة هاتف 2', 'main_lang.php'),
( 'arabic', 'clinic_name', 'اسم العيادة', 'main_lang.php'),
( 'arabic', 'clinic_start_time', 'عيادة وقت البدء', 'main_lang.php'),
( 'arabic', 'clinic_runs_full_day', 'عيادة يدير يوم كامل', 'main_lang.php'),
( 'arabic', 'column_2', 'العمود 2', 'main_lang.php'),
( 'arabic', 'column_1', 'العمود 1', 'main_lang.php'),
( 'arabic', 'complete', 'اكتمال', 'main_lang.php'),
( 'arabic', 'cost', 'كلفة', 'main_lang.php'),
( 'arabic', 'completed_appointment', 'الموعد المكتمل', 'main_lang.php'),
( 'arabic', 'company_information', 'معلومات الشركة', 'main_lang.php'),
( 'arabic', 'company', 'شركة', 'main_lang.php'),
( 'arabic', 'completed_sessions', 'الدورات المكتملة', 'main_lang.php'),
( 'arabic', 'compare', 'قارن', 'main_lang.php'),
( 'arabic', 'content', 'يحتوى', 'main_lang.php'),
( 'arabic', 'contact', 'اتصل', 'main_lang.php'),
( 'arabic', 'conditions', 'الظروف', 'main_lang.php'),
( 'arabic', 'country_code', 'الرقم الدولي', 'main_lang.php'),
( 'arabic', 'continue', 'استمر', 'main_lang.php'),
( 'arabic', 'contact_details', 'بيانات المتصل', 'main_lang.php'),
( 'arabic', 'copyright', '&نسخ؛ 2016', 'main_lang.php'),
( 'arabic', 'copyright_text', 'نص حقوق الطبع والنشر', 'main_lang.php'),
( 'arabic', 'consultation', 'تشاور', 'main_lang.php'),
( 'arabic', 'confirm_password', 'تأكيد كلمة المرور', 'main_lang.php'),
( 'arabic', 'copyright_url', 'عنوان URL لحقوق الطبع والنشر', 'main_lang.php'),
( 'arabic', 'consultation_in', 'التشاور في', 'main_lang.php'),
( 'arabic', 'consultation_out', 'التشاور خارج', 'main_lang.php'),
( 'arabic', 'contact_number', 'رقم الاتصال', 'main_lang.php'),
( 'arabic', 'curr_post', 'بوستفيكس العملة', 'main_lang.php'),
( 'arabic', 'country', 'بلد', 'main_lang.php'),
( 'arabic', 'cost_price', 'سعر الكلفة', 'main_lang.php'),
( 'arabic', 'curr_pre', 'بادئة العملة', 'main_lang.php'),
( 'arabic', 'cr_ac_name', 'كر. اسم المكيفات', 'main_lang.php'),
( 'arabic', 'created_by', 'صنع من قبل', 'main_lang.php'),
( 'arabic', 'currency', 'دقة', 'main_lang.php'),
( 'arabic', 'column_1_header', 'العمود 1 - رأس', 'main_lang.php'),
( 'arabic', 'custom_details', 'تفاصيل مخصصة', 'main_lang.php'),
( 'arabic', 'column_1_content', 'العمود 1 - المحتوى', 'main_lang.php'),
( 'arabic', 'ccavenue', 'CCAvenue', 'main_lang.php'),
( 'arabic', 'contact_us', 'اتصل بنا', 'main_lang.php'),
( 'arabic', 'copy', 'نسخ', 'main_lang.php'),
( 'arabic', 'ccavenue_settings', 'إعدادات CCAvenue', 'main_lang.php'),
( 'arabic', 'cancelled_appoinment_by_patient', 'في حالة إلغاء الموعد من قبل المريض ، يجب أن يتم استرداد المبلغ يدويًا', 'main_lang.php'),
( 'arabic', 'change_language_file', 'تغيير الكلمات في ملف اللغة', 'main_lang.php'),
( 'arabic', 'create_language_file', 'إنشاء ملف لغة جديد', 'main_lang.php'),
( 'arabic', 'compare_image', 'مطلوب صورتان كحد أدنى للمقارنة', 'main_lang.php'),
( 'arabic', 'dose', 'جرعة', 'main_lang.php'),
( 'arabic', 'dr_ac_name', 'دكتور A / c الاسم', 'main_lang.php'),
( 'arabic', 'does_not_has_value', 'ليس له قيمة', 'main_lang.php'),
( 'arabic', 'day', 'يوم', 'main_lang.php'),
( 'arabic', 'days', 'أيام', 'main_lang.php'),
( 'arabic', 'daily', 'اليومي', 'main_lang.php'),
( 'arabic', 'daily_hour', 'يوميا / في الساعة', 'main_lang.php'),
( 'arabic', 'daily_per_bed_charge', 'تكلفة السرير الواحد (يوميًا)', 'main_lang.php'),
( 'arabic', 'date', 'تاريخ', 'main_lang.php'),
( 'arabic', 'dashboard', 'لوحة القيادة', 'main_lang.php'),
( 'arabic', 'date_format', 'صيغة التاريخ', 'main_lang.php'),
( 'arabic', 'deallocate', 'إلغاء تخصيص', 'main_lang.php'),
( 'arabic', 'delete', 'حذف', 'main_lang.php'),
( 'arabic', 'degrees', 'درجات', 'main_lang.php'),
( 'arabic', 'delete_item', 'حذفa عنصر', 'main_lang.php'),
( 'arabic', 'deactivate', 'عطل', 'main_lang.php'),
( 'arabic', 'delete_supplier', 'حذف المورد', 'main_lang.php'),
( 'arabic', 'delete_user', 'مسح المستخدم', 'main_lang.php'),
( 'arabic', 'department', ' قسم، أقسام', 'main_lang.php'),
( 'arabic', 'department_name', 'اسم القسم', 'main_lang.php'),
( 'arabic', 'delete_treatment', 'حذف العلاج', 'main_lang.php'),
( 'arabic', 'departments', 'الإدارات', 'main_lang.php'),
( 'arabic', 'desired_stock', 'الأسهم المطلوبة', 'main_lang.php'),
( 'arabic', 'detail', 'التفاصيل', 'main_lang.php'),
( 'arabic', 'default', 'افتراضي', 'main_lang.php'),
( 'arabic', 'details', 'تفاصيل', 'main_lang.php'),
( 'arabic', 'due_amount', 'مبلغ مستحق', 'main_lang.php'),
( 'arabic', 'discount', 'خصم', 'main_lang.php'),
( 'arabic', 'dismissed', 'رفض', 'main_lang.php'),
( 'arabic', 'dismiss', 'رفض', 'main_lang.php'),
( 'arabic', 'display', 'عرض', 'main_lang.php'),
( 'arabic', 'discount_amount', 'مقدار الخصم', 'main_lang.php'),
( 'arabic', 'display_in', 'عرض في', 'main_lang.php'),
( 'arabic', 'display_name', 'اسم الaعرض', 'main_lang.php'),
( 'arabic', 'display_google_ads', 'عرض إعلانات Google', 'main_lang.php'),
( 'arabic', 'discount_percentage', 'نسبة الخصم', 'main_lang.php'),
( 'arabic', 'dob', 'تاريخ الولادة', 'main_lang.php'),
( 'arabic', 'doctors', 'الأطباء', 'main_lang.php'),
( 'arabic', 'doctor_share', 'دكتور شارك', 'main_lang.php'),
( 'arabic', 'doctor_name', 'اسم الطبيب', 'main_lang.php'),
( 'arabic', 'doctor', 'طبيب', 'main_lang.php'),
( 'arabic', 'doctor_availability', 'طبيب في توافر', 'main_lang.php'),
( 'arabic', 'doctor_bonus_report', 'تقرير مكافأة الطبيب', 'main_lang.php'),
( 'arabic', 'doctor_detail', 'طبيب التفاصيل', 'main_lang.php'),
( 'arabic', 'doctor_unavailability', 'عدم توفر الطبيب', 'main_lang.php'),
( 'arabic', 'doctor_inavailability', 'طبيب في توافر', 'main_lang.php'),
( 'arabic', 'doctor_schedule', 'جدول الطبيب', 'main_lang.php'),
( 'arabic', 'doctor_preferences', 'تفضيلات الطبيب', 'main_lang.php'),
( 'arabic', 'download', 'تحميل', 'main_lang.php'),
( 'arabic', 'download_extension', 'ملحق التحميل', 'main_lang.php'),
( 'arabic', 'downloading_files', 'تحميل الملفات', 'main_lang.php'),
( 'arabic', 'dr', 'Dr.', 'main_lang.php'),
( 'arabic', 'duplicate', 'مكرر', 'main_lang.php'),
( 'arabic', 'duration', 'المدة الزمنية', 'main_lang.php'),
( 'arabic', 'description', 'وصف', 'main_lang.php'),
( 'arabic', 'disease', 'مرض', 'main_lang.php'),
( 'arabic', 'diseases', 'الأمراض', 'main_lang.php'),
( 'arabic', 'diagnosed_diseases', 'مرض تشخيصي', 'main_lang.php'),
( 'arabic', 'decimal_symbol', 'رمز عشري', 'main_lang.php'),
( 'arabic', 'eraser', 'مسترة', 'main_lang.php'),
( 'arabic', 'erpnext_sync', 'مزامنة Erpnext', 'main_lang.php'),
( 'arabic', 'erpnext_url', 'عنوان Erpnext', 'main_lang.php'),
( 'arabic', 'enable_about_page', 'تمكين حول الصفحة', 'main_lang.php'),
( 'arabic', 'edit', 'تصحيح', 'main_lang.php'),
( 'arabic', 'end_time', 'وقت النهاية', 'main_lang.php'),
( 'arabic', 'edit_Contact', 'تحرير الاتصال', 'main_lang.php'),
( 'arabic', 'end_date', 'تاريخ الانتهاء', 'main_lang.php'),
( 'arabic', 'edit_treatment', 'تعديل اaلعلاج', 'main_lang.php'),
( 'arabic', 'edit_section', 'تحرير القسم', 'main_lang.php'),
( 'arabic', 'edit_test', 'تحرير الاختبار', 'main_lang.php'),
( 'arabic', 'edit_medicine_too', 'تحرير الطب أيضا', 'main_lang.php'),
( 'arabic', 'email', 'البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'edit_user', 'تحرير العضو', 'main_lang.php'),
( 'arabic', 'email_log', 'سجل البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'email_alert_name', 'اسم تنبيه البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'email_id', 'عنوان الايميل', 'main_lang.php'),
( 'arabic', 'email_bill', 'فاتورة البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'email_settings', 'إعدادات البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'established_patient', 'أنشئت المريض', 'main_lang.php'),
( 'arabic', 'enter_email_address', 'أدخل عنوان البريد الالكتروني ', 'main_lang.php'),
( 'arabic', 'enter_details_to_login', 'أدخل التفاصيل aلتسجيل الدخول ', 'main_lang.php'),
( 'arabic', 'extracting', 'Extracting', 'main_lang.php'),
( 'arabic', 'extraction_failed', 'فشل الاaستخراج', 'main_lang.php'),
( 'arabic', 'expenditure', 'المصروفات', 'main_lang.php'),
( 'arabic', 'experience', 'تجربة', 'main_lang.php'),
( 'arabic', 'exceptional_days', 'أيام استثنائية', 'main_lang.php'),
( 'arabic', 'extensions', 'ملحقات', 'main_lang.php'),
( 'arabic', 'export_to_excel', 'تصدير إلى Excel', 'main_lang.php'),
( 'arabic', 'expiry_date', 'تاريخ الانتهاء', 'main_lang.php'),
( 'arabic', 'enter_new_password', 'أدخل كلمة المرور الجديدة أدناه', 'main_lang.php'),
( 'arabic', 'enable_news', 'تمكين صفحة الأخبار', 'main_lang.php'),
( 'arabic', 'enable_online_appointment', 'تمكين الحجز عبر الإنترنت', 'main_lang.php'),
( 'arabic', 'enable_paypal', 'تمكين PayPal', 'main_lang.php'),
( 'arabic', 'enable_admin_approval', 'تمكين موافقة المسؤول', 'main_lang.php'),
( 'arabic', 'enable_ccavenue', 'تمكين CCAvenue', 'main_lang.php'),
( 'arabic', 'enable_sandbox', 'تمكين Sandbox', 'main_lang.php'),
( 'arabic', 'enable_service_page', 'تمكين صفحة الخدمة', 'main_lang.php'),
( 'arabic', 'email_alert_time', 'البريد الإلكتروني وقت التنبيه', 'main_lang.php'),
( 'arabic', 'email_format', 'تنسيق البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'edit_format', 'تحرير الشكل', 'main_lang.php'),
( 'arabic', 'edit_language', 'تحرير اللغة', 'main_lang.php'),
( 'arabic', 'facebook', 'الفيسبوك', 'main_lang.php'),
( 'arabic', 'face', 'وجه', 'main_lang.php'),
( 'arabic', 'fax', 'فاكس', 'main_lang.php'),
( 'arabic', 'fees', 'رسوم', 'main_lang.php'),
( 'arabic', 'fees_detail', 'رسوم', 'main_lang.php'),
( 'arabic', 'facebook_link', 'رابط فيسبوك', 'main_lang.php'),
( 'arabic', 'file', 'ملف', 'main_lang.php'),
( 'arabic', 'female', 'إناثا', 'main_lang.php'),
( 'arabic', 'filter', 'منقي', 'main_lang.php'),
( 'arabic', 'file_content', 'محتوى الملف', 'main_lang.php'),
( 'arabic', 'first', 'أول', 'main_lang.php'),
( 'arabic', 'first_name', 'الاسم الاول', 'main_lang.php'),
( 'arabic', 'find_us_here', 'تجد لنا هنا', 'main_lang.php'),
( 'arabic', 'fields', 'مجالات', 'main_lang.php'),
( 'arabic', 'field_options', 'خيار المجال', 'main_lang.php'),
( 'arabic', 'field_label', 'تسمية الميدان', 'main_lang.php'),
( 'arabic', 'field_order', 'مجال الطلب', 'main_lang.php'),
( 'arabic', 'field_name', 'اسم الحقل', 'main_lang.php'),
( 'arabic', 'field_type', 'نوع الحقل', 'main_lang.php'),
( 'arabic', 'field_width', 'عرض المجال', 'main_lang.php'),
( 'arabic', 'foc', 'F.O.C.', 'main_lang.php'),
( 'arabic', 'field_status', 'حالة الحقل', 'main_lang.php'),
( 'arabic', 'follow', 'إتبع', 'main_lang.php'),
( 'arabic', 'follow_on', 'متابعة على', 'main_lang.php'),
( 'arabic', 'follow_up', 'متابعة', 'main_lang.php'),
( 'arabic', 'follow_ups', 'المتابعات', 'main_lang.php'),
( 'arabic', 'footer_settings', 'إعدادات تذييل الصفحة', 'main_lang.php'),
( 'arabic', 'footer_credits', 'الاعتمادات التذييل', 'main_lang.php'),
( 'arabic', 'for', 'إلى عن على', 'main_lang.php'),
( 'arabic', 'forgot_password', 'هل نسيت كلمة المرور؟', 'main_lang.php'),
( 'arabic', 'form', 'شكل', 'main_lang.php'),
( 'arabic', 'footer_credit_settings', 'تذييل إعدادات الائتمان', 'main_lang.php'),
( 'arabic', 'found', 'وجدت', 'main_lang.php'),
( 'arabic', 'frequency', 'تكرر', 'main_lang.php'),
( 'arabic', 'from_date', 'من التاريخ', 'main_lang.php'),
( 'arabic', 'from_time', 'من وقت', 'main_lang.php'),
( 'arabic', 'to_time', 'الى وقت', 'main_lang.php'),
( 'arabic', 'from_name', 'من الاسم', 'main_lang.php'),
( 'arabic', 'from_doctor', 'من الطبيب', 'main_lang.php'),
( 'arabic', 'framework', 'الإطار', 'main_lang.php'),
( 'arabic', 'frontend', 'نهاية المقدمة', 'main_lang.php'),
( 'arabic', 'full_day', 'يوم كامل', 'main_lang.php'),
( 'arabic', 'fixed_amount', 'مبلغ ثابت', 'main_lang.php'),
( 'arabic', 'from_email', 'من البريد الإلكترونى', 'main_lang.php'),
( 'arabic', 'featured', 'متميز', 'main_lang.php'),
( 'arabic', 'footer_section_1', 'تذييل القسم 1', 'main_lang.php'),
( 'arabic', 'featured_image', 'صورة مميزة', 'main_lang.php'),
( 'arabic', 'footer_section_2', 'تذييل القسم 2', 'main_lang.php'),
( 'arabic', 'footer_section_3', 'تذييل القسم 3', 'main_lang.php'),
( 'arabic', 'gender', 'جنس', 'main_lang.php'),
( 'arabic', 'gain', 'ربح', 'main_lang.php'),
( 'arabic', 'gallery', 'صالة عرض', 'main_lang.php'),
( 'arabic', 'go', 'اذهب', 'main_lang.php'),
( 'arabic', 'footer_section_4', 'تذييل القسم 4', 'main_lang.php'),
( 'arabic', 'file_size', 'السماح بالحد الأقصى لحجم الملف (بالكيلو بايت)', 'main_lang.php'),
( 'arabic', 'file_type', 'أنواع الملفات المسموح بها', 'main_lang.php'),
( 'arabic', 'file_type_msg','أنواع الملفات منفصلة عن طريق jpeg | jpg | png إلخ.', 'main_lang.php'),
( 'arabic', 'google_plus', 'جوجل بلس', 'main_lang.php'),
( 'arabic', 'general_settings', 'الاعدادات العامة', 'main_lang.php'),
( 'arabic', 'group_name', 'أسم المجموعة', 'main_lang.php'),
( 'arabic', 'group_by', 'مجموعة من', 'main_lang.php'),
( 'arabic', 'group', 'مجموعة', 'main_lang.php'),
( 'arabic', 'gallery_setting_msg', '(يمكنك إدارة أنواع الملفات المسموح بها وحجم الملف المسموح به من الإدارة> الإعدادات> المعرض)', 'main_lang.php'),
( 'arabic', 'header', 'رأس', 'main_lang.php'),
( 'arabic', 'hidden', 'مخفي', 'main_lang.php'),
( 'arabic', 'home', 'الصفحة الرئيسية', 'main_lang.php'),
( 'arabic', 'hour', 'ساعة', 'main_lang.php'),
( 'arabic', 'hourly', 'باستمرار', 'main_lang.php'),
( 'arabic', 'html_content', 'محتوى HTML', 'main_lang.php'),
( 'arabic', 'hourly_per_bed_charge', 'تكلفة السرير (كل ساعة)', 'main_lang.php'),
( 'arabic', 'header_settings', 'إعدادات الرأس', 'main_lang.php'),
( 'arabic', 'home_settings', 'إعدادات الصفحة الرئيسية', 'main_lang.php'),
( 'arabic', 'has_additional_details', 'لديه تفاصيل إضافية', 'main_lang.php'),
( 'arabic', 'header_contact_number', 'رقم جهة الاتصال الرأس', 'main_lang.php'),
( 'arabic', 'has_value', 'له قيمة', 'main_lang.php'),
( 'arabic', 'heading', 'عنوان', 'main_lang.php'),
( 'arabic', 'history', 'التاريخ', 'main_lang.php'),
( 'arabic', 'home_page_settings', 'إعدادات الصفحة الرئيسية', 'main_lang.php'),
( 'arabic', 'home_page_top_section', 'الصفحة الرئيسية القسم العلوي', 'main_lang.php'),
( 'arabic', 'home_page_slider', 'الصفحة الرئيسية المتزلج', 'main_lang.php'),
( 'arabic', 'half_day', 'نصف يوم', 'main_lang.php'),
( 'arabic', 'home_page_bottom_section', 'الصفحة الرئيسية القسم السفلي', 'main_lang.php'),
( 'arabic', 'invoice', 'فاتورة', 'main_lang.php'),
( 'arabic', 'id', 'هوية شخصية', 'main_lang.php'),
( 'arabic', 'icon', 'أيقونة', 'main_lang.php'),
( 'arabic', 'if_field', 'إذا الحقل', 'main_lang.php'),
( 'arabic', 'inavailablity', 'عدم', 'main_lang.php'),
( 'arabic', 'install', 'التثبت', 'main_lang.php'),
( 'arabic', 'installing', 'تثبيت', 'main_lang.php'),
( 'arabic', 'invoice_number', 'رقم الفاتورة', 'main_lang.php'),
( 'arabic', 'invoice_prefix', 'بادئة الفاتورة', 'main_lang.php'),
( 'arabic', 'invoice_settings', 'إعدادات الفاتورة', 'main_lang.php'),
( 'arabic', 'invoice_details', 'تفاصيل الفاتورة', 'main_lang.php'),
( 'arabic', 'instructions', 'تعليمات', 'main_lang.php'),
( 'arabic', 'in_minutes', 'في دقائق', 'main_lang.php'),
( 'arabic', 'in_group', 'في مجموعة', 'main_lang.php'),
( 'arabic', 'is_checked', 'مفحوص', 'main_lang.php'),
( 'arabic', 'is_active', '{الحقل} غير نشط. يرجى الاتصال بالمسؤول', 'main_lang.php'),
( 'arabic', 'is_unchecked', 'لم يتم التحقق منه', 'main_lang.php'),
( 'arabic', 'is_default', 'هو الافتراضي', 'main_lang.php'),
( 'arabic', 'item_name', 'اسم العنصر', 'main_lang.php'),
( 'arabic', 'item', 'بند', 'main_lang.php'),
( 'arabic', 'items', 'العناصر', 'main_lang.php'),
( 'arabic', 'item_number', 'رقم الشيء', 'main_lang.php'),
( 'arabic', 'item_type', 'نوع العنصر', 'main_lang.php'),
( 'arabic', 'import', 'استيراد ملف CSV', 'main_lang.php'),
( 'arabic', 'images', 'صور', 'main_lang.php'),
( 'arabic', 'image', 'صورة', 'main_lang.php'),
( 'arabic', 'image_id', 'معرف الصورة', 'main_lang.php'),
( 'arabic', 'image_name', 'اسم الصورة', 'main_lang.php'),
( 'arabic', 'image_path', 'مسار الصورة', 'main_lang.php'),
( 'arabic', 'issue_refund', 'استرداد القضية', 'main_lang.php'),
( 'arabic', 'income', 'الإيرادات', 'main_lang.php'),
( 'arabic', 'individual', 'فرد', 'main_lang.php'),
( 'arabic', 'information', 'معلومات', 'main_lang.php'),
( 'arabic', 'jurisdiction', 'تخضع لسلطة الاختصاص', 'main_lang.php'),
( 'arabic', 'joining_date', 'تاريخ الانضمام', 'main_lang.php'),
( 'arabic', 'journal_voucher', 'قسيمة يومية', 'main_lang.php'),
( 'arabic', 'landline', 'هاتف ارضي', 'main_lang.php'),
( 'arabic', 'journal_vouchers', 'قسائم اليومية', 'main_lang.php'),
( 'arabic', 'key', 'مفتاح', 'main_lang.php'),
( 'arabic', 'last_name', 'الكنية', 'main_lang.php'),
( 'arabic', 'languages', 'اللغات', 'main_lang.php'),
( 'arabic', 'last', 'الاخير', 'main_lang.php'),
( 'arabic', 'lab_instructions', 'تعليمات المختبر', 'main_lang.php'),
( 'arabic', 'lab_tests', 'فحوصات مخبرية', 'main_lang.php'),
( 'arabic', 'lab_test', 'اختبار مختبر', 'main_lang.php'),
( 'arabic', 'lab_reports', 'تقارير مختبر', 'main_lang.php'),
( 'arabic', 'latest_news', 'آخر الأخبار', 'main_lang.php'),
( 'arabic', 'length_invoice', 'طول رقم الفاتورة', 'main_lang.php'),
( 'arabic', 'login', 'تسجيل الدخول', 'main_lang.php'),
( 'arabic', 'login_yourself_to_get_access', 'تسجيل الدخول نفسك للوصول', 'main_lang.php'),
( 'arabic', 'license_key', 'مفتاح الترخيص', 'main_lang.php'),
( 'arabic', 'log_out', 'الخروج', 'main_lang.php'),
( 'arabic', 'licence_number', 'رقم الرخصة', 'main_lang.php'),
( 'arabic', 'line2', 'خط 2', 'main_lang.php'),
( 'arabic', 'line1', 'خط 1', 'main_lang.php'),
( 'arabic', 'liabilities', 'المطلوبات', 'main_lang.php'),
( 'arabic', 'list_master', 'قائمة ماجستير', 'main_lang.php'),
( 'arabic', 'language_name', 'اسم اللغة', 'main_lang.php'),
( 'arabic', 'latest', 'آخر', 'main_lang.php'),
( 'arabic', 'link', 'حلقة الوصل', 'main_lang.php'),
( 'arabic', 'language', 'لغة', 'main_lang.php'),
( 'arabic', 'link_text', 'نص الارتباط', 'main_lang.php'),
( 'arabic', 'link_url', 'رابط URL', 'main_lang.php'),
( 'arabic', 'male', 'الذكر', 'main_lang.php'),
( 'arabic', 'marker', 'علامة', 'main_lang.php'),
( 'arabic', 'marking', 'العلامات', 'main_lang.php'),
( 'arabic', 'marking_images', 'بمناسبة الصور', 'main_lang.php'),
( 'arabic', 'max_patient', 'ماكس المرضى في وقت واحد', 'main_lang.php'),
( 'arabic', 'medicine', 'دواء', 'main_lang.php'),
( 'arabic', 'menu_access', 'الوصول إلى القائمة', 'main_lang.php'),
( 'arabic', 'medicine_store_bill', 'فاتورة متجر الأدوية', 'main_lang.php'),
( 'arabic', 'medicines', 'أدوية', 'main_lang.php'),
( 'arabic', 'mobile_no', 'رقم المحمول', 'main_lang.php'),
( 'arabic', 'middle', 'وسط', 'main_lang.php'),
( 'arabic', 'medicine_name', 'اسم الدواء', 'main_lang.php'),
( 'arabic', 'mobile', 'التليفون المحمول', 'main_lang.php'),
( 'arabic', 'module', 'وحدة', 'main_lang.php'),
( 'arabic', 'mode', 'الوضع', 'main_lang.php'),
( 'arabic', 'mrp', 'M.R.P.', 'main_lang.php'),
( 'arabic', 'morning', 'M', 'main_lang.php'),
( 'arabic', 'middle_name', 'الاسم الأوسط', 'main_lang.php'),
( 'arabic', 'minutes', 'الدقائق', 'main_lang.php'),
( 'arabic', 'modules', 'وحدات', 'main_lang.php'),
( 'arabic', 'message', 'رسالة', 'main_lang.php'),
( 'arabic', 'morning_time', 'وقت الصباح', 'main_lang.php'),
( 'arabic', 'make', 'يصنع', 'main_lang.php'),
( 'arabic', 'merchant_id', 'معرف التاجر', 'main_lang.php'),
( 'arabic', 'media', 'وسائل الإعلام', 'main_lang.php'),
( 'arabic', 'my_account', 'حسابي', 'main_lang.php'),
( 'arabic', 'make_appointment', 'تحديد موعد', 'main_lang.php'),
( 'arabic', 'maximum_about_posts', '(لقد وصلت إلى الحد الأقصى حول المشاركات التي يمكن إضافتها)', 'main_lang.php'),
( 'arabic', 'minimum_stock', 'الحد الأدنى من الأسهم المطلوبة', 'main_lang.php'),
( 'arabic', 'make_an_appointment', 'إحجز موعد', 'main_lang.php'),
( 'arabic', 'maximum_bottom_posts', '(لقد وصلت إلى الحد الأقصى لمشاركات الأقسام السفلية التي يمكن إضافتها)', 'main_lang.php'),
( 'arabic', 'maximum_footer_posts', '(لقد وصلت إلى أقصى أقسام تذييل الصفحة التي يمكن إضافتها)', 'main_lang.php'),
( 'arabic', 'maximum_top_posts', '(لقد وصلت إلى الحد الأقصى لأعلى أقسام المشاركات التي يمكن إضافتها)', 'main_lang.php'),
( 'arabic', 'maximum_footer_credits', '(لقد وصلت إلى الحد الأقصى لمشاركات رصيد تذييل الصفحة التي يمكن إضافتها)', 'main_lang.php'),
( 'arabic', 'month', 'شهر', 'main_lang.php'),
( 'arabic', 'minimum_income', 'الحد الأدنى للدخل', 'main_lang.php'),
( 'arabic', 'name', 'اسم', 'main_lang.php'),
( 'arabic', 'medical', 'طبي', 'main_lang.php'),
( 'arabic', 'none', 'لا شيء', 'main_lang.php'),
( 'arabic', 'next_follow_date', 'تاريخ المتابعة التالي', 'main_lang.php'),
( 'arabic', 'net_total', 'صافي المجموع', 'main_lang.php'),
( 'arabic', 'next_follow_up', 'التالي متابعة بعد', 'main_lang.php'),
( 'arabic', 'new', 'الجديد', 'main_lang.php'),
( 'arabic', 'news_title', 'عنوان', 'main_lang.php'),
( 'arabic', 'news_date', 'تاريخ الأخبار', 'main_lang.php'),
( 'arabic', 'news', 'أخبار', 'main_lang.php'),
( 'arabic', 'new_appointment', 'موعد جديد', 'main_lang.php'),
( 'arabic', 'new_contact', 'جهة اتصال جديدة', 'main_lang.php'),
( 'arabic', 'new_inquiry', 'استفسار جديد', 'main_lang.php'),
( 'arabic', 'new_inquires', 'استفسارات جديدة', 'main_lang.php'),
( 'arabic', 'new_password', 'كلمة السر الجديدة', 'main_lang.php'),
( 'arabic', 'new_sell', 'بيع جديد', 'main_lang.php'),
( 'arabic', 'night', 'N', 'main_lang.php'),
( 'arabic', 'news_setting', 'إعدادات صفحة الأخبار', 'main_lang.php'),
( 'arabic', 'non_taxable_revenue', 'عائد غير خاضع للضريبة', 'main_lang.php'),
( 'arabic', 'no_of_beds', 'عدد الأسرة', 'main_lang.php'),
( 'arabic', 'no', 'لا', 'main_lang.php'),
( 'arabic', 'not_available', 'غير متاح', 'main_lang.php'),
( 'arabic', 'notes', 'ملاحظات', 'main_lang.php'),
( 'arabic', 'notes_for_patient', 'ملاحظات للمريض', 'main_lang.php'),
( 'arabic', 'number', 'رقم', 'main_lang.php'),
( 'arabic', 'news_page_settings', 'إعدادات صفحة الأخبار', 'main_lang.php'),
( 'arabic', 'number_of_columns', 'عدد الأعمدة', 'main_lang.php'),
( 'arabic', 'night_time', 'وقت الليل', 'main_lang.php'),
( 'arabic', 'needs_cash_calc', 'يحتاج حاسبة النقدية', 'main_lang.php'),
( 'arabic', 'nurse', 'ممرضة', 'main_lang.php'),
( 'arabic', 'no_prescription', 'لم يتم العثور على وصفة طبية', 'main_lang.php'),
( 'arabic', 'no_image_for_comparision', 'لا توجد صور محددة للمقارنة', 'main_lang.php'),
( 'arabic', 'our', 'لنا', 'main_lang.php'),
( 'arabic', 'on', 'على', 'main_lang.php'),
( 'arabic', 'number_of_decimal', 'المنازل العشرية', 'main_lang.php'),
( 'arabic', 'our_team', 'فريقنا', 'main_lang.php'),
( 'arabic', 'our_services', 'خدماتنا', 'main_lang.php'),
( 'arabic', 'old_password', 'كلمة المرور القديمة', 'main_lang.php'),
( 'arabic', 'option', 'اختيار', 'main_lang.php'),
( 'arabic', 'office_branch', 'فرع المكتب', 'main_lang.php'),
( 'arabic', 'office', 'مكتب. مقر. مركز', 'main_lang.php'),
( 'arabic', 'opening', 'افتتاح', 'main_lang.php'),
( 'arabic', 'opening_stock', 'فتح المخزون', 'main_lang.php'),
( 'arabic', 'other', 'آخر', 'main_lang.php'),
( 'arabic', 'paid', 'دفع', 'main_lang.php'),
( 'arabic', 'of_appoinment_time', 'وقت التعيين', 'main_lang.php'),
( 'arabic', 'page_title', 'عنوان الصفحة', 'main_lang.php'),
( 'arabic', 'paid_cash', 'النقدية المدفوعة', 'main_lang.php'),
( 'arabic', 'paid_amount', 'المبلغ المدفوع', 'main_lang.php'),
( 'arabic', 'particular', 'بصفة خاصة', 'main_lang.php'),
( 'arabic', 'parent', 'الأبوين', 'main_lang.php'),
( 'arabic', 'password', 'كلمه السر', 'main_lang.php'),
( 'arabic', 'patient', 'صبور', 'main_lang.php'),
( 'arabic', 'patient_details', 'تفاصيل المريض', 'main_lang.php'),
( 'arabic', 'patient_detail', 'تفاصيل المريض', 'main_lang.php'),
( 'arabic', 'patient_account', 'حساب المريض', 'main_lang.php'),
( 'arabic', 'patient_id', 'رقم المريض', 'main_lang.php'),
( 'arabic', 'patients', 'المرضى', 'main_lang.php'),
( 'arabic', 'patient_name', 'اسم المريض', 'main_lang.php'),
( 'arabic', 'patient_notes', 'ملاحظات المريض', 'main_lang.php'),
( 'arabic', 'patient_added_after', 'المريض يضاف بعد', 'main_lang.php'),
( 'arabic', 'patient_report', 'تقرير المريض', 'main_lang.php'),
( 'arabic', 'patient_wise_alert_settings', 'إعدادات تنبيه المريض الحكيمة', 'main_lang.php'),
( 'arabic', 'payment', 'دفع', 'main_lang.php'),
( 'arabic', 'payments', 'المدفوعات', 'main_lang.php'),
( 'arabic', 'payment_form', 'نموذج الدفع', 'main_lang.php'),
( 'arabic', 'payment_amount', 'مبلغ الدفعة', 'main_lang.php'),
( 'arabic', 'payment_methods', 'طرق الدفع', 'main_lang.php'),
( 'arabic', 'payment_adjustement', 'تسوية الدفع', 'main_lang.php'),
( 'arabic', 'payment_date', 'تاريخ الدفع', 'main_lang.php'),
( 'arabic', 'payment_method', 'طريقة الدفع او السداد', 'main_lang.php'),
( 'arabic', 'payment_mode', 'طريقة الدفع', 'main_lang.php'),
( 'arabic', 'payment_status', 'حالة السداد', 'main_lang.php'),
( 'arabic', 'payment_history', 'تاريخ الدفع', 'main_lang.php'),
( 'arabic', 'paypal_settings', 'إعدادات PayPal', 'main_lang.php'),
( 'arabic', 'paypal_business_email', 'PayPal Business Email', 'main_lang.php'),
( 'arabic', 'pending', 'قيد الانتظار', 'main_lang.php'),
( 'arabic', 'pending_payments', 'دفعات مؤجلة', 'main_lang.php'),
( 'arabic', 'per_bed_charge', 'لكل سرير المسؤول', 'main_lang.php'),
( 'arabic', 'per_day', 'في اليوم', 'main_lang.php'),
( 'arabic', 'per_hour', 'في الساعة', 'main_lang.php'),
( 'arabic', 'placeholder', 'نائب', 'main_lang.php'),
( 'arabic', 'post', 'بريد', 'main_lang.php'),
( 'arabic', 'postal_code', 'الرمز البريدي', 'main_lang.php'),
( 'arabic', 'posts', 'المشاركات', 'main_lang.php'),
( 'arabic', 'phone_number', 'رقم الهاتف', 'main_lang.php'),
( 'arabic', 'post_content', 'آخر المحتوى', 'main_lang.php'),
( 'arabic', 'post_title', 'عنوان الوظيفة', 'main_lang.php'),
( 'arabic', 'post_type', 'نوع الوظيفة', 'main_lang.php'),
( 'arabic', 'print', 'طباعة', 'main_lang.php'),
( 'arabic', 'print_receipt', 'اطبع الايصال', 'main_lang.php'),
( 'arabic', 'profile', 'الملف الشخصي', 'main_lang.php'),
( 'arabic', 'progress', 'تقدم', 'main_lang.php'),
( 'arabic', 'prev_bal', 'الرصيد السابق', 'main_lang.php'),
( 'arabic', 'preferred_size', 'حجم المفضل 260X60', 'main_lang.php'),
( 'arabic', 'price', 'السعر', 'main_lang.php'),
( 'arabic', 'print_report', 'اطبع تقرير', 'main_lang.php'),
( 'arabic', 'prev_due', 'الاستحقاق السابق', 'main_lang.php'),
( 'arabic', 'prescription', 'وصفة طبية', 'main_lang.php'),
( 'arabic', 'purchase_date', 'تاريخ الشراء', 'main_lang.php'),
( 'arabic', 'purchase', 'شراء', 'main_lang.php'),
( 'arabic', 'purchase_return', 'عودة شراء', 'main_lang.php'),
( 'arabic', 'purchase_register', 'سجل الشراء', 'main_lang.php'),
( 'arabic', 'preferences', 'تفضيلات', 'main_lang.php'),
( 'arabic', 'promocode', 'رمز ترويجي', 'main_lang.php'),
( 'arabic', 'percentage', 'النسبة المئوية', 'main_lang.php'),
( 'arabic', 'pending_appointments', 'المواعيد المعلقة', 'main_lang.php'),
( 'arabic', 'pending_payment', 'في انتظار الدفع', 'main_lang.php'),
( 'arabic', 'promocodes', 'رموز الترويجي', 'main_lang.php'),
( 'arabic', 'planned_appointment', 'هذا موعد هو جلسة مخططة', 'main_lang.php'),
( 'arabic', 'pay', 'دفع', 'main_lang.php'),
( 'arabic', 'payment_pending', 'حافظ على الدفع معلقًا حتى تتم الموافقة عليه', 'main_lang.php'),
( 'arabic', 'planned_visit', 'هذه الزيارة هي جلسة مخططة', 'main_lang.php'),
( 'arabic', 'planned_sessions', 'الجلسات المخطط لها', 'main_lang.php'),
( 'arabic', 'phone', 'هاتف', 'main_lang.php'),
( 'arabic', 'paypal', 'باي بال', 'main_lang.php'),
( 'arabic', 'prescribed_medicine', 'وصفه الطب', 'main_lang.php'),
( 'arabic', 'prefered_language', 'اللغة المفضلة', 'main_lang.php'),
( 'arabic', 'quantity', 'كمية', 'main_lang.php'),
( 'arabic', 'qrcode', 'كود QR', 'main_lang.php'),
( 'arabic', 'fixed', 'الثابته', 'main_lang.php'),
( 'arabic', 'variable', 'متغير', 'main_lang.php'),
( 'arabic', 'in', 'في', 'main_lang.php'),
( 'arabic', 'decimal_places', 'المنازل العشرية', 'main_lang.php'),
( 'arabic', 'rate', 'معدل', 'main_lang.php'),
( 'arabic', 'reason', 'السبب', 'main_lang.php'),
( 'arabic', 'response', 'استجابة', 'main_lang.php'),
( 'arabic', 'rebrand', 'اعادة تصنيف', 'main_lang.php'),
( 'arabic', 'receipt_template', 'قوالب الاستلام', 'main_lang.php'),
( 'arabic', 'receipt', 'إيصال', 'main_lang.php'),
( 'arabic', 'report', 'أبلغ عن', 'main_lang.php'),
( 'arabic', 'reference_by', 'مرجع بواسطة', 'main_lang.php'),
( 'arabic', 'refund', 'إعادة مال', 'main_lang.php'),
( 'arabic', 'reports', 'تقارير', 'main_lang.php'),
( 'arabic', 'restore', 'استعادة', 'main_lang.php'),
( 'arabic', 'reset_password', 'إعادة ضبط كلمة المرور', 'main_lang.php'),
( 'arabic', 'remark', 'تعليق', 'main_lang.php'),
( 'arabic', 'remove_logo', 'إزالة الشعار', 'main_lang.php'),
( 'arabic', 'remove', 'إزالة', 'main_lang.php'),
( 'arabic', 'remove_patient_image', 'إزالة صورة المريض', 'main_lang.php'),
( 'arabic', 'renew_license_to_update', 'تجديد الترخيص للتحديث', 'main_lang.php'),
( 'arabic', 'renew_license', 'تجديد الترخيص', 'main_lang.php'),
( 'arabic', 'quantity_exceeds', 'الكمية المطلوبة تتجاوز المخزون المتاح', 'main_lang.php'),
( 'arabic', 'receive_fee', 'الرسوم المستلمة مقابل الخدمات المهنية والرسوم الأخرى الخاصة بنا', 'main_lang.php'),
( 'arabic', 'room', 'مجال', 'main_lang.php'),
( 'arabic', 'rooms_allocate', 'تخصيص الغرف', 'main_lang.php'),
( 'arabic', 'rooms_categories', 'فئات الغرف', 'main_lang.php'),
( 'arabic', 'rooms', 'غرف', 'main_lang.php'),
( 'arabic', 'register', 'تسجيل', 'main_lang.php'),
( 'arabic', 'rooms_calendar', 'غرف التقويم', 'main_lang.php'),
( 'arabic', 'rooms_beds', 'غرف / أسرة', 'main_lang.php'),
( 'arabic', 'reference_details', 'تفاصيل المرجع', 'main_lang.php'),
( 'arabic', 'resend_code', 'أعد إرسال الرمز', 'main_lang.php'),
( 'arabic', 'registration', 'التسجيل', 'main_lang.php'),
( 'arabic', 'residence', 'إقامة', 'main_lang.php'),
( 'arabic', 'restore_backup', 'استرجاع النسخة الاحتياطية', 'main_lang.php'),
( 'arabic', 'return', 'إرجاع', 'main_lang.php'),
( 'arabic', 'room_charges', 'تقارير غرفة الرسوم', 'main_lang.php'),
( 'arabic', 'return_change', 'العودة التغيير', 'main_lang.php'),
( 'arabic', 'return_date', 'تاريخ العودة', 'main_lang.php'),
( 'arabic', 'refund_date', 'تاريخ الاسترداد', 'main_lang.php'),
( 'arabic', 'refund_amount', 'المبلغ المسترد', 'main_lang.php'),
( 'arabic', 'room_number', 'رقم الغرفة', 'main_lang.php'),
( 'arabic', 'refund_note', 'رد المبلغ', 'main_lang.php'),
( 'arabic', 'refresh', 'تحديث', 'main_lang.php'),
( 'arabic', 'reject', 'رفض', 'main_lang.php'),
( 'arabic', 'required_quantity', 'الكمية المطلوبة', 'main_lang.php'),
( 'arabic', 'rtl', 'RTL', 'main_lang.php'),
( 'arabic', 'reason_for_appointment', 'سبب التعيين', 'main_lang.php'),
( 'arabic', 'right_to_left', 'من اليمين إلى اللغة اليسرى', 'main_lang.php'),
( 'arabic', 'reload_language_file', 'إعادة تحميل ملف اللغة', 'main_lang.php'),
( 'arabic', 'reload_language_file_instruction', 'This will overwrite the changes from language file.', 'main_lang.php'),
( 'arabic', 'slider_image', 'صورة منزلق', 'main_lang.php'),
( 'arabic', 'sign_up', 'سجل', 'main_lang.php'),
( 'arabic', 'slider_2', 'شريط التمرير 2', 'main_lang.php'),
( 'arabic', 'slider_1', 'شريط التمرير 1', 'main_lang.php'),
( 'arabic', 'slider_3', 'شريط التمرير 3', 'main_lang.php'),
( 'arabic', 'slider', 'المنزلق', 'main_lang.php'),
( 'arabic', 'section', 'الجزء', 'main_lang.php'),
( 'arabic', 'section_1', 'القسم 1', 'main_lang.php'),
( 'arabic', 'section_4', 'القسم 4', 'main_lang.php'),
( 'arabic', 'section_3', 'القسم 3', 'main_lang.php'),
( 'arabic', 'section_2', 'القسم 2', 'main_lang.php'),
( 'arabic', 'section_name', 'اسم القسم', 'main_lang.php'),
( 'arabic', 'senderid', 'هوية المرسل', 'main_lang.php'),
( 'arabic', 'save', 'حفظ', 'main_lang.php'),
( 'arabic', 'schedule', 'جدول', 'main_lang.php'),
( 'arabic', 'search', 'بحث', 'main_lang.php'),
( 'arabic', 'search_by_name', 'البحث عن طريق الإسم', 'main_lang.php'),
( 'arabic', 'select', 'تحديد', 'main_lang.php'),
( 'arabic', 'second_number', 'الرقم الثاني', 'main_lang.php'),
( 'arabic', 'select_lang', 'اختر لغتك', 'main_lang.php'),
( 'arabic', 'select_currency', 'حدد العملة', 'main_lang.php'),
( 'arabic', 'select_date', 'حدد التاريخ', 'main_lang.php'),
( 'arabic', 'select_duration', 'تحديد المدة', 'main_lang.php'),
( 'arabic', 'select_media_image', 'تحديد صورة الوسائط', 'main_lang.php'),
( 'arabic', 'select_time_zone', 'اختر منطقتك الزمنية', 'main_lang.php'),
( 'arabic', 'select_all', 'اختر الكل', 'main_lang.php'),
( 'arabic', 'select_mode', 'حدد الوضع', 'main_lang.php'),
( 'arabic', 'sell', 'يبيع', 'main_lang.php'),
( 'arabic', 'subject', 'موضوع', 'main_lang.php'),
( 'arabic', 'select_blood_group', 'اختر فصيلة الدم', 'main_lang.php'),
( 'arabic', 'shortcode_label', 'الرموز القصيرة التي تحتاج إلى استخدامها:', 'main_lang.php'),
( 'arabic', 'shortcode_patient_name', '[patient_name] - اسم المريض', 'main_lang.php'),
( 'arabic', 'shortcode_clinic_name', '[clinic_name] - اسم العيادة', 'main_lang.php'),
( 'arabic', 'shortcode_patient_id', '[patient_id] - رقم المريض', 'main_lang.php'),
( 'arabic', 'shortcode_clinic_logo', '[clinic_logo] - عيادة شعار - يمكن وضعها في عيادة التفاصيل', 'main_lang.php'),
( 'arabic', 'shortcode_clinic_address', '[clinic_address] - عنوان العيادة - يمكن وضعها في تفاصيل العيادة', 'main_lang.php'),
( 'arabic', 'shortcode_clinic_landline', '[landline] - خط أرضي - يمكن تعيينه في عيادة التفاصيل', 'main_lang.php'),
( 'arabic', 'shortcode_clinic_mobile', '[mobile] - المحمول - يمكن وضعها في عيادة التفاصيل', 'main_lang.php'),
( 'arabic', 'shortcode_clinic_email', '[email] - البريد الإلكتروني - يمكن تعيينها في عيادة التفاصيل', 'main_lang.php'),
( 'arabic', 'shortcode_tag_line', '[tag_line] - خط العلامة - يمكن ضبطه في عيادة التفاصيل', 'main_lang.php'),
( 'arabic', 'shortcode_dose_time', '[dose_time] - صباح | الثلاثاء | الأربعاء', 'main_lang.php'),
( 'arabic', 'shortcode_doctor_name', '[doctor_name] - اسم الطبيب', 'main_lang.php'),
( 'arabic', 'shortcode_medicine_details', '[medicine_details] - جميع تفاصيل الطب في شكل الجدول', 'main_lang.php'),
( 'arabic', 'shortcode_sms_medicine_details', '[sms_medicine_details] - جميع تفاصيل الطب في شكل الجدول', 'main_lang.php'),
( 'arabic', 'shortcode_appointment_time', '[appointment_time] - وقت الموعد', 'main_lang.php'),
( 'arabic', 'shortcode_appointment_status', '[appointment_status] - حالة التعيين', 'main_lang.php'),
( 'arabic', 'shortcode_appointment_date', '[appointment_date] - موعد موعد', 'main_lang.php'),
( 'arabic', 'shortcode_appointment_reason', '[appointment_reason] - سبب التعيين', 'main_lang.php'),
( 'arabic', 'shortcode_bill', '[bill] - نسخة ميسرة من الفاتورة', 'main_lang.php'),
( 'arabic', 'shortcode_bill_date', '[bill_date] - تاريخ الفاتورة', 'main_lang.php'),
( 'arabic', 'shortcode_bill_id', '[bill_id] - معرف الفاتورة', 'main_lang.php'),
( 'arabic', 'shortcode_patient_email', '[patient_email] - عنوان الايميل', 'main_lang.php'),
( 'arabic', 'shortcode_bill_time', '[bill_time] - وقت بيل', 'main_lang.php'),
( 'arabic', 'shortcode_patient_age', '[age] - عمر المريض', 'main_lang.php'),
( 'arabic', 'shortcode_patient_sex', '[sex] - الجنس المريض', 'main_lang.php'),
( 'arabic', 'shortcode_visit_date', '[visit_date] - موعد زيارة', 'main_lang.php'),
( 'arabic', 'shortcode_total', '[total] - مجموع هذا بيل', 'main_lang.php'),
( 'arabic', 'shortcode_previous_due', '[previous_due] - المستحقات السابقة', 'main_lang.php'),
( 'arabic', 'shortcode_paid_amount', '[paid_amount] - المبلغ المدفوع', 'main_lang.php'),
( 'arabic', 'shortcode_patient_phone_number', '[patient_phone_number] - رقم الهاتف', 'main_lang.php'),
( 'arabic', 'shortcode_username', '[username] - سيتم استبدال اسم المستخدم', 'main_lang.php'),
( 'arabic', 'shortcode_password', '[password] - سيتم استبداله بكلمة المرور', 'main_lang.php'),
( 'arabic', 'shortcode_senderid', '[senderid] - سيتم استبدال معرف المرسل', 'main_lang.php'),
( 'arabic', 'shortcode_template_id', '[template_id] - سيتم استبداله بمعرف القالب', 'main_lang.php'),
( 'arabic', 'shortcode_mobileno', '[mobileno] - سيتم استبداله رقم الجوال المستلم', 'main_lang.php'),
( 'arabic', 'shortcode_message', '[message] - سيتم استبدال الرسالة', 'main_lang.php'),
( 'arabic', 'shortcode_bill_columns', 'الأعمدة لعرضها في الجدول بيل', 'main_lang.php'),
( 'arabic', 'sms_settings', 'إعدادات الرسائل القصيرة', 'main_lang.php'),
( 'arabic', 'share_type', 'نوع المشاركة', 'main_lang.php'),
( 'arabic', 'shortcode_prescription_columns', 'الأعمدة لعرضها في الجدول للحصول على وصفة طبية', 'main_lang.php'),
( 'arabic', 'smtp_instructions', 'أدناه الحقول المطلوبة فقط لإرسال رسائل البريد الإلكتروني SMTP', 'main_lang.php'),
( 'arabic', 'services_settings', 'إعدادات الخدمات', 'main_lang.php'),
( 'arabic', 'sell_id', 'بيع معرف', 'main_lang.php'),
( 'arabic', 'stock_sell', 'يبيع', 'main_lang.php'),
( 'arabic', 'set', 'جلس', 'main_lang.php'),
( 'arabic', 'sell_amount', 'بيع المبلغ', 'main_lang.php'),
( 'arabic', 'sell_date', 'تاريخ البيع', 'main_lang.php'),
( 'arabic', 'sell_price', 'سعر البيع', 'main_lang.php'),
( 'arabic', 'set_as_default', 'تعيين كافتراضي', 'main_lang.php'),
( 'arabic', 'settings', 'إعدادات', 'main_lang.php'),
( 'arabic', 'services', 'خدمات', 'main_lang.php'),
( 'arabic', 'services_type', 'أنواع الخدمات', 'main_lang.php'),
( 'arabic', 'service', 'الخدمات', 'main_lang.php'),
( 'arabic', 'session', 'جلسة', 'main_lang.php'),
( 'arabic', 'session_report', 'تقرير الجلسة', 'main_lang.php'),
( 'arabic', 'sessions', 'جلسات', 'main_lang.php'),
( 'arabic', 'signature', 'التوقيع', 'main_lang.php'),
( 'arabic', 'setting', 'ضبط', 'main_lang.php'),
( 'arabic', 'software_name', 'اسم البرنامج', 'main_lang.php'),
( 'arabic', 'sold_at', 'بيعت في', 'main_lang.php'),
( 'arabic', 'sold_avg', 'تم بيع متوسط', 'main_lang.php'),
( 'arabic', 'sold_quantity', 'الكمية المباعة', 'main_lang.php'),
( 'arabic', 'special_access', 'وصول خاص', 'main_lang.php'),
( 'arabic', 'specialization', 'تخصص', 'main_lang.php'),
( 'arabic', 'staff', 'العاملين', 'main_lang.php'),
( 'arabic', 'sr_no', 'الأب رقم.', 'main_lang.php'),
( 'arabic', 'start_date', 'تاريخ البدء', 'main_lang.php'),
( 'arabic', 'state', 'حالة', 'main_lang.php'),
( 'arabic', 'static_prefix', 'بادئة ثابتة', 'main_lang.php'),
( 'arabic', 'status', 'الحالة', 'main_lang.php'),
( 'arabic', 'start_time', 'وقت البدء', 'main_lang.php'),
( 'arabic', 'stock', 'مخزون', 'main_lang.php'),
( 'arabic', 'stock_item', 'بند', 'main_lang.php'),
( 'arabic', 'stock_stock_report', 'تقرير الاسهم', 'main_lang.php'),
( 'arabic', 'submit', 'خضع', 'main_lang.php'),
( 'arabic', 'stock_report', 'أبلغ عن', 'main_lang.php'),
( 'arabic', 'sub_total', 'المجموع الفرعي', 'main_lang.php'),
( 'arabic', 'supplier', 'المورد', 'main_lang.php'),
( 'arabic', 'suppliers', 'الموردين', 'main_lang.php'),
( 'arabic', 'stock_purchase_report', 'تقرير الشراء', 'main_lang.php'),
( 'arabic', 'stock_suppliers', 'الموردين', 'main_lang.php'),
( 'arabic', 'stock_purchase', 'شراء', 'main_lang.php'),
( 'arabic', 'support', 'الدعم', 'main_lang.php'),
( 'arabic', 'supplier_name', 'اسم المورد', 'main_lang.php'),
( 'arabic', 'support_text', 'نص الدعم', 'main_lang.php'),
( 'arabic', 'support_url', 'عنوان URL الدعم', 'main_lang.php'),
( 'arabic', 'select_a_Slot', 'تحديد فتحة', 'main_lang.php'),
( 'arabic', 'select_doctor', 'حدد الطبيب', 'main_lang.php'),
( 'arabic', 'select_beautician', 'حدد الطبيب', 'main_lang.php'),
( 'arabic', 'select_fields', 'حدد الحقول', 'main_lang.php'),
( 'arabic', 'select_patient', 'اختر المريض', 'main_lang.php'),
( 'arabic', 'select_tax_rate', 'حدد معدل الضريبة', 'main_lang.php'),
( 'arabic', 'stock_sell_report', 'كل تقرير بيع', 'main_lang.php'),
( 'arabic', 'sell_return', 'بيع العودة', 'main_lang.php'),
( 'arabic', 'total_sell_report', 'تقرير إجمالي البيع', 'main_lang.php'),
( 'arabic', 'synchronize', 'تزامن', 'main_lang.php'),
( 'arabic', 'smtp_port', 'SMTP Port', 'main_lang.php'),
( 'arabic', 'sms_url', 'عنوان URL لإرسال الرسائل القصيرة', 'main_lang.php'),
( 'arabic', 'sms_alert_time', 'وقت التنبيه SMS', 'main_lang.php'),
( 'arabic', 'smtp_host', 'SMTP Host', 'main_lang.php'),
( 'arabic', 'sms_format', 'تنسيق الرسائل القصيرة', 'main_lang.php'),
( 'arabic', 'sms_template_id', 'معرف قالب SMS', 'main_lang.php'),
( 'arabic', 'save_and_bill', 'حفظ وإنشاء بيل', 'main_lang.php'),
( 'arabic', 'sms_log', 'سجل SMS', 'main_lang.php'),
( 'arabic', 'ssn_id', 'رقم الأساس', 'main_lang.php'),
( 'arabic', 'save_complete', 'حفظ وكاملة', 'main_lang.php'),
( 'arabic', 'set_alert_time', 'ضبط وقت التنبيه', 'main_lang.php'),
( 'arabic', 'slot', 'فتحة', 'main_lang.php'),
( 'arabic', 'take_backup', 'خذ النسخ الاحتياطي', 'main_lang.php'),
( 'arabic', 'total_appointments', 'مجموع المواعيد', 'main_lang.php'),
( 'arabic', 'to', 'إلى', 'main_lang.php'),
( 'arabic', 'tag_line', 'خط العلامة', 'main_lang.php'),
( 'arabic', 'task', 'مهمة', 'main_lang.php'),
( 'arabic', 'tasks', 'مهام', 'main_lang.php'),
( 'arabic', 'tax', 'ضريبة', 'main_lang.php'),
( 'arabic', 'tax_amount', 'قيمة الضريبة', 'main_lang.php'),
( 'arabic', 'tax_revenue', 'عائدات الضرائب', 'main_lang.php'),
( 'arabic', 'taxable', 'خاضع للضريبة', 'main_lang.php'),
( 'arabic', 'taxable_revenue', 'عائد خاضع للضريبة', 'main_lang.php'),
( 'arabic', 'tax_rates', 'معدلات الضريبة', 'main_lang.php'),
( 'arabic', 'tax_report', 'تقرير الضرائب', 'main_lang.php'),
( 'arabic', 'tax_rate', 'معدل الضريبة', 'main_lang.php'),
( 'arabic', 'template_name', 'اسم القالب', 'main_lang.php'),
( 'arabic', 'template_content', 'محتوى القالب', 'main_lang.php'),
( 'arabic', 'thanks', 'حصل مع الشكر', 'main_lang.php'),
( 'arabic', 'timestamp', 'الطابع الزمني', 'main_lang.php'),
( 'arabic', 'time', 'زمن', 'main_lang.php'),
( 'arabic', 'test', 'اختبار', 'main_lang.php'),
( 'arabic', 'timings', 'توقيت', 'main_lang.php'),
( 'arabic', 'time_zone', 'وحدة زمنية', 'main_lang.php'),
( 'arabic', 'time_format', 'تنسيق الوقت', 'main_lang.php'),
( 'arabic', 'title', 'عنوان', 'main_lang.php'),
( 'arabic', 'to_admin_panel', ' إلى لوحة المشرف', 'main_lang.php'),
( 'arabic', 'time_interval', 'الفاصل الزمني', 'main_lang.php'),
( 'arabic', 'to_date', 'ان يذهب في موعد', 'main_lang.php'),
( 'arabic', 'total', 'مجموع', 'main_lang.php'),
( 'arabic', 'to_be_paid', 'لكي تدفع', 'main_lang.php'),
( 'arabic', 'transport', 'المواصلات', 'main_lang.php'),
( 'arabic', 'treatment', 'علاج او معاملة', 'main_lang.php'),
( 'arabic', 'total_due_after_payment', 'المجموع المستحق بعد الدفع', 'main_lang.php'),
( 'arabic', 'treatment_report', 'تقرير العلاج', 'main_lang.php'),
( 'arabic', 'treatments', 'العلاجات', 'main_lang.php'),
( 'arabic', 'twitter', 'تغريد', 'main_lang.php'),
( 'arabic', 'type', 'اكتب', 'main_lang.php'),
( 'arabic', 'treatment_name', 'اسم العلاج', 'main_lang.php'),
( 'arabic', 'treatment_charges', 'رسوم العلاج / الرسوم', 'main_lang.php'),
( 'arabic', 'twitter_link', 'رابط تويتر', 'main_lang.php'),
( 'arabic', 'theme', 'موضوع', 'main_lang.php'),
( 'arabic', 'tax_rate_name', 'اسم معدل الضريبة', 'main_lang.php'),
( 'arabic', 'test_name', 'اسم الاختبار', 'main_lang.php'),
( 'arabic', 'tests', 'اختبارات', 'main_lang.php'),
( 'arabic', 'txn_id', 'معرف TXN', 'main_lang.php'),
( 'arabic', 'text', 'نص', 'main_lang.php'),
( 'arabic', 'top_section_1', 'الجزء العلوي 1', 'main_lang.php'),
( 'arabic', 'top_section_2', 'الجزء العلوي 2', 'main_lang.php'),
( 'arabic', 'top_section_3', 'الجزء العلوي 3', 'main_lang.php'),
( 'arabic', 'this_payment_is_rejected', 'تم رفض هذا الدفع', 'main_lang.php'),
( 'arabic', 'types', 'أنواع', 'main_lang.php'),
( 'arabic', 'thousands_separator', 'فاصل آلاف', 'main_lang.php'),
( 'arabic', 'upload', 'رفع', 'main_lang.php'),
( 'arabic', 'upload_extension', 'تحميل الإضافات', 'main_lang.php'),
( 'arabic', 'update', 'تحديث', 'main_lang.php'),
( 'arabic', 'updates', 'التحديثات', 'main_lang.php'),
( 'arabic', 'update_now', 'تحديث الان', 'main_lang.php'),
( 'arabic', 'username', 'اسم المستخدم', 'main_lang.php'),
( 'arabic', 'user', 'المستعمل', 'main_lang.php'),
( 'arabic', 'users', 'المستخدمين', 'main_lang.php'),
( 'arabic', 'url', 'URL', 'main_lang.php'),
( 'arabic', 'using', 'عن طريق', 'main_lang.php'),
( 'arabic', 'upcoming_appointments', 'المواعيد القادمة', 'main_lang.php'),
( 'arabic', 'unpacking_zip_package', 'تفريغ حزمة البريدي', 'main_lang.php'),
( 'arabic', 'upload_language_file', 'تحميل ملف لغة موجود', 'main_lang.php'),
( 'arabic', 'vaccine', 'لقاح', 'main_lang.php'),
( 'arabic', 'vaccine_master', 'تلقيح', 'main_lang.php'),
( 'arabic', 'vaccines', 'لقاحات', 'main_lang.php'),
( 'arabic', 'vaccine_name', 'اسم اللقاح', 'main_lang.php'),
( 'arabic', 'viewed', 'شوهد', 'main_lang.php'),
( 'arabic', 'view', 'رأي', 'main_lang.php'),
( 'arabic', 'visit', 'يزور', 'main_lang.php'),
( 'arabic', 'visit_date', 'تاريخ الزيارة', 'main_lang.php'),
( 'arabic', 'visit_time', 'وقت الزيارة', 'main_lang.php'),
( 'arabic', 'visits', 'مرة', 'main_lang.php'),
( 'arabic', 'visit_type', 'زيارة النوع', 'main_lang.php'),
( 'arabic', 'verify', 'التحقق', 'main_lang.php'),
( 'arabic', 'version', 'الإصدار', 'main_lang.php'),
( 'arabic', 'verification_code', 'رمز التحقق', 'main_lang.php'),
( 'arabic', 'verify_email', 'التحقق من البريد الإلكتروني', 'main_lang.php'),
( 'arabic', 'voucher_no', 'رقم القسيمة', 'main_lang.php'),
( 'arabic', 'voucher_date', 'تاريخ القسيمة', 'main_lang.php'),
( 'arabic', 'view_prescription', 'عرض وصفة طبية', 'main_lang.php'),
( 'arabic', 'view_larger_map', 'عرض خريطة أكبر', 'main_lang.php'),
( 'arabic', 'value', 'القيمة', 'main_lang.php'),
( 'arabic', 'visit_report', 'تقرير التاريخ الطبي', 'main_lang.php'),
( 'arabic', 'waiting_in', 'في انتظار', 'main_lang.php'),
( 'arabic', 'welcome', 'أهلا بك', 'main_lang.php'),
( 'arabic', 'waiting', 'انتظار', 'main_lang.php'),
( 'arabic', 'whole_day', 'كل اليوم', 'main_lang.php'),
( 'arabic', 'website', 'موقع الكتروني', 'main_lang.php'),
( 'arabic', 'website_url', 'رابط الموقع', 'main_lang.php'),
( 'arabic', 'website_text', 'نص الموقع', 'main_lang.php'),
( 'arabic', 'working', 'العمل', 'main_lang.php'),
( 'arabic', 'working_days', 'أيام العمل', 'main_lang.php'),
( 'arabic', 'non_working', 'هذا هو يوم غير العمل', 'main_lang.php'),
( 'arabic', 'we_provide', 'نحن نقدم', 'main_lang.php'),
( 'arabic', 'working_key', 'مفتاح العمل', 'main_lang.php'),
( 'arabic', 'year', 'عام', 'main_lang.php'),
( 'arabic', 'sunday', 'الأحد', 'main_lang.php'),
( 'arabic', 'wednesday', 'الأربعاء', 'main_lang.php'),
( 'arabic', 'tuesday', 'الثلاثاء', 'main_lang.php'),
( 'arabic', 'monday', 'الإثنين', 'main_lang.php'),
( 'arabic', 'thursday', 'الخميس', 'main_lang.php'),
( 'arabic', 'friday', 'يوم الجمعة', 'main_lang.php'),
( 'arabic', 'your_username', 'اسم المستخدم الخاص بك', 'main_lang.php'),
( 'arabic', 'saturday', 'يوم السبت', 'main_lang.php'),
( 'arabic', 'your_password', 'كلمة السر خاصتك', 'main_lang.php'),
( 'arabic', 'room_numbers_for', 'أرقام الغرف', 'main_lang.php'),
( 'arabic', 'aplha_space', 'قد يحتوي الحقل٪ s على أحرف ألفا ومسافات بيضاء فقط', 'main_lang.php'),
( 'arabic', 'first_or_last', 'الرجاء إدخال الاسم الأول أو اسم العائلة', 'main_lang.php'),
( 'arabic', 'irreversible_process', '|هذا هو عملية لا رجعة فيها. قد يسبب فقدان البيانات. كن حقا متأكدا حقا قبل استعادة البيانات.', 'main_lang.php'),
( 'arabic', 'password_not_match', 'كلمة المرور القديمة غير متطابقة', 'main_lang.php'),
( 'arabic', 'numbersof_days_between_two_appointments', 'حدده للأيام الأساسية بين موعدين. اضبطه على 0 ، لتعطيل إعداد المتابعة التالية تلقائيًا.', 'main_lang.php'),
( 'arabic', 'calculation_purpose_only', '* هذه الحقول لغرض الحساب فقط. إضافة مبلغ الدفع الفعلي في حقل مبلغ الدفع.', 'main_lang.php'),
( 'arabic', 'clickto_toggle_display', '(انقر لتبديل العرض)', 'main_lang.php'),
( 'arabic', 'norecfound', 'لا يوجد سجلات', 'main_lang.php'),
( 'arabic', 'nobillsfound_for_selected_parameters', 'لم يتم العثور على فواتير للمعلمات المحددة', 'main_lang.php'),
( 'arabic', 'areyousure', 'هل أنت متأكد أنك تريد', 'main_lang.php'),
( 'arabic', 'areyousure_delete', 'هل أنت متأكد أنك تريد حذف؟', 'main_lang.php'),
( 'arabic', 'areyousure_reject', 'هل أنت متأكد أنك تريد الرفض؟', 'main_lang.php'),
( 'arabic', 'areyousure_approve', 'هل أنت متأكد أنك تريد الموافقة؟', 'main_lang.php'),
( 'arabic', 'areyousure_deactivate', 'هل أنت متأكد من أنك تريد إلغاء التنشيط؟', 'main_lang.php'),
( 'arabic', 'please_select', 'من فضلك اختر', 'main_lang.php'),
( 'arabic', 'areyousure_cleardata', 'هل أنت متأكد من أنك تريد مسح البيانات؟ هذه العملية لا يمكن التراجع عنها!', 'main_lang.php'),
( 'arabic', 'tempnote', '&nbsp;&nbsp;&nbsp;&nbsp;* لن يؤدي تغيير اسم قالب موجود إلى إعادة تسمية القالب. بدلا من ذلك سوف يقوم بإنشاء نسخة من القالب.', 'main_lang.php'),
( 'arabic', 'invalid_username', 'اسم المستخدم و / أو كلمة المرور غير صالحة', 'main_lang.php'),
( 'arabic', 'jpg_format_not_allow', 'صيغة ملف jpg مسموح بها &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; حجم الصورة: 800 * 800', 'main_lang.php'),
( 'arabic', 'no_treatment_added_add_treatment', 'لا توجد علاجات مضافة. إضافة علاج.', 'main_lang.php'),
( 'arabic', 'no_file_chosen', 'لم تقم باختيار ملف', 'main_lang.php'),
( 'arabic', 'no_vaccine_added_add_vaccine', 'لا لقاحات المضافة. أضف لقاح.', 'main_lang.php'),
( 'arabic', 'no_vaccine_schedule_added_add_vaccine', 'لا جدول لقاحات المضافة. أضف جدول اللقاحات.', 'main_lang.php'),
( 'arabic', 'temptext', 'يجب تعيين دليل القالب للكتابة لاستخدام محرر القالب.', 'main_lang.php'),
( 'arabic', 'upload_extention_instruction', 'إذا كان لديك امتداد في تنسيق. zip ، فيمكنك تثبيته عن طريق تحميله هنا.', 'main_lang.php'),
( 'arabic', 'no_visits', 'إذا كان لديك امتداد في تنسيق. zip ، فيمكنك تثبيته عن طريق تحميله هنا.', 'main_lang.php'),
( 'arabic', 'toggle_display', '(انقر لتبديل العرض)', 'main_lang.php'),
( 'arabic', 'initial_password_message', 'كلمة المرور المبدئية هي نفسها اسم المستخدم', 'main_lang.php'),
( 'arabic', 'thanks_to_amazing_works', 'لم يكن من الممكن Chikitsa دون الأعمال المدهشة المذكورة أدناه', 'main_lang.php'),
( 'arabic', 'no_disease', 'لم تتم إضافة أي أمراض. إضافة مرض.', 'main_lang.php'),
( 'arabic', 'validate_date_or_day', 'الرجاء إدخال التاريخ أو تحديد الأيام.', 'main_lang.php'),
( 'arabic', 'max_post_allowed', '(لقد وصلت إلى الحد الأقصى حول المشاركات التي يمكن إضافتها)', 'main_lang.php'),
( 'arabic', 'time_booked', 'تم حجز هذه المرة بالفعل مع أقصى عدد ممكن من المرضى!', 'main_lang.php'),
( 'arabic', 'doctor_not_available', 'الطبيب غير متوفر خلال هذا الوقت', 'main_lang.php'),
( 'arabic', 'error_saving_image', 'حدث خطأ ما أثناء محاولة حفظ الصورة.', 'main_lang.php'),
( 'arabic', 'image_for_compare', 'يرجى اختيار الصور للمقارنة', 'main_lang.php'),
( 'arabic', 'select_two', 'يرجى اختيار اثنين فقط', 'main_lang.php'),
( 'arabic', 'validate_code', 'رمز التحقق غير صالح', 'main_lang.php'),
( 'arabic', 'save_language_instructions', '(فقط قم بتغيير النص وانتقل إلى التالي للحفظ)', 'main_lang.php'),
( 'arabic', 'reset_password_instructions', 'الرجاء إدخال اسم المستخدم أو عنوان البريد الإلكتروني. ستتلقى رابطًا لإنشاء كلمة مرور جديدة عبر البريد الإلكتروني.', 'main_lang.php'),
( 'arabic', 'no_email_registered', 'لا يوجد مستخدم مسجل بهذا الاسم أو البريد الإلكتروني.', 'main_lang.php'),
( 'arabic', 'check_confirmation_link', 'تحقق من بريدك الالكتروني للحصول على رابط التأكيد.', 'main_lang.php'),
( 'arabic', 'appointment_payment_success', 'تم سداد الدفعة بنجاح ، ونشكرك على حجز موعدك.', 'main_lang.php'),
( 'arabic', 'paypal_cancel_message', 'نحن اسفون! تم إلغاء آخر معاملة لك.', 'main_lang.php'),
( 'arabic', 'paypal_cancel_salutation', 'عزيزي المنتسب', 'main_lang.php'),
( 'arabic', 'file_missing', 'مجلد مفقود', 'main_lang.php'),
( 'arabic', 'sms_username_instruction', 'أدخل اسم المستخدم المقدم من قبل مزود خدمة SMS API', 'main_lang.php'),
( 'arabic', 'sms_password_instruction', 'أدخل كلمة المرور التي يوفرها موفر SMS API', 'main_lang.php'),
( 'arabic', 'sms_senderid_instruction', 'أدخل معرف المرسل الذي يوفره موفر واجهة برمجة تطبيقات SMS', 'main_lang.php'),
( 'arabic', 'sms_countrycode_instruction', 'احتفظ بها فارغة حتى لا تدرج رمز البلد في رقم الجوال', 'main_lang.php'),
( 'arabic', 'sms_url_instruction', 'أدخل عنوان URL المقدم من قبل موفر خدمة SMS API', 'main_lang.php'),
( 'arabic', 'updating_to_latest', 'تحديث Chikitsa إلى أحدث نسخة. قد تستغرق هذه العملية عدة دقائق. <br/>', 'main_lang.php'),
( 'arabic', 'donot_close_browser', '<strong> يرجى عدم إغلاق المتصفح حتى تكتمل العملية. </strong><br/>', 'main_lang.php'),
( 'arabic', 'download_chikitsa', 'يتم الآن تنزيل أحدث Chikitsa zip ... <br/>', 'main_lang.php'),
( 'arabic', 'unzip_file', 'فك ضغط ملف zip <br/>', 'main_lang.php'),
( 'arabic', 'no_services', 'لم تتم إضافة خدمات. أضف خدمة', 'main_lang.php'),
( 'arabic', 'extension_requires', '%1 %2 هذا التمديد يتطلب ', 'main_lang.php'),
( 'arabic', 'compatible_version', '%1 متوافق مع هذا الإصدار من ', 'main_lang.php'),
( 'arabic', 'please_enter_first_name', 'يرجى إدخال الاسم الأول', 'main_lang.php'),
( 'arabic', 'please_enter_last_name', 'يرجى إدخال الاسم الأخير', 'main_lang.php'),
( 'arabic', 'please_enter_mobile_number', 'يرجى إدخال رقم الهاتف المحمول', 'main_lang.php'),
( 'arabic', 'please_enter_language_name', 'يرجى إدخال اسم اللغة', 'main_lang.php'),
( 'arabic', 'canadian_currency', 'الدولار الكندي (CAD)', 'main_lang.php'),
( 'arabic', 'brazilian_currency', 'ريال برازيلي (BRL)', 'main_lang.php'),
( 'arabic', 'australian_currency', 'الدولار الأسترالي (AUD)', 'main_lang.php'),
( 'arabic', 'czech_currency', 'كورونا تشيكية (CZK)', 'main_lang.php'),
( 'arabic', 'danish_currency', 'التاج الدنماركي (DKK)', 'main_lang.php'),
( 'arabic', 'hungarian_currency', 'الفورنت المجري (HUF)', 'main_lang.php'),
( 'arabic', 'hong_kong_currency', 'دولار هونج كونج (HKD)', 'main_lang.php'),
( 'arabic', 'euro_currency', 'اليورو (يورو)', 'main_lang.php'),
( 'arabic', 'israeli_currency', 'الشيكل الاسرائيلي الجديد (ILS)', 'main_lang.php'),
( 'arabic', 'mexican_currency', 'بيزو مكسيكي (MXN)', 'main_lang.php'),
( 'arabic', 'norwegian_currency', 'التاج النرويجي (NOK)', 'main_lang.php'),
( 'arabic', 'japanese_currency', 'الين الياباني (JPY)', 'main_lang.php'),
( 'arabic', 'malaysian_currency', 'رينغيت ماليزي (MYR)', 'main_lang.php'),
( 'arabic', 'new_zealand_currency', 'الدولار النيوزيلندي (NZD)', 'main_lang.php'),
( 'arabic', 'philippine_currency', 'بيزو فلبيني (PHP)', 'main_lang.php'),
( 'arabic', 'polish_currency', 'الزلوتي البولندي (PLN', 'main_lang.php'),
( 'arabic', 'pound_currency', 'الجنيه الإسترليني (GBP)', 'main_lang.php'),
( 'arabic', 'singapore_currency', 'الدولار السنغافوري (SGD)', 'main_lang.php'),
( 'arabic', 'swedish_currency', 'الكرونا السويدية (SEK)', 'main_lang.php'),
( 'arabic', 'swiss_currency', 'الفرنك السويسري (CHF)', 'main_lang.php'),
( 'arabic', 'taiwan_currency', 'الدولار التايواني الجديد (TWD)', 'main_lang.php'),
( 'arabic', 'us_currency', 'الدولار الأمريكي (USD)', 'main_lang.php'),
( 'arabic', 'uae_currency', 'الدرهم الإماراتي (AED)', 'main_lang.php'),
( 'arabic', 'thai_currency', 'البات التايلندي (THB)', 'main_lang.php'),
( 'arabic', 'bangladesh_currency', 'تاكا بنغلاديش (BDT)', 'main_lang.php'),
( 'arabic', 'bahraini_currency', 'دينار بحريني (BHD)', 'main_lang.php'),
( 'arabic', 'chinese_currency', 'يوان صيني (CNY)', 'main_lang.php'),
( 'arabic', 'indian_currency', 'روبية هندية (INR)', 'main_lang.php'),
( 'arabic', 'kenyan_currency', 'الشلن الكيني (KES)', 'main_lang.php'),
( 'arabic', 'kuwaiti_currency', 'دينار كويتي (KWD)', 'main_lang.php'),
( 'arabic', 'sri_lankan_currency', 'الروبية السريلانكية (LKR)', 'main_lang.php'),
( 'arabic', 'mauritius_currency', 'موريشيوس روبية (MUR)', 'main_lang.php'),
( 'arabic', 'nepalese_currency', 'روبية نيبالي (NPR)', 'main_lang.php'),
( 'arabic', 'omani_currency', 'الريال العماني (OMR)', 'main_lang.php'),
( 'arabic', 'qatari_currency', 'الريال القطري (ريال قطري)', 'main_lang.php'),
( 'arabic', 'saudi_currency', 'ريال سعودي (ريال سعودي)', 'main_lang.php'),
( 'arabic', 'grace_hours', 'ساعات السماح', 'main_lang.php'),
( 'arabic', 'south_african_currency', 'الراند الجنوب أفريقي (ZAR)', 'main_lang.php'),
( 'arabic', 'minimum', 'الحد الأدنى لساعات القبول', 'main_lang.php'),
( 'arabic', 'base_charge', 'الرسوم الأساسية لأقل عدد من الساعات', 'main_lang.php'),
( 'arabic', 'migration_none_found', 'لم يتم العثور على عمليات ترحيل.', 'migration_lang.php'),
( 'arabic', 'migration_sequence_gap', 'هناك فجوة في تسلسل الهجرة بالقرب من رقم الإصدار:٪ s.', 'migration_lang.php'),
( 'arabic', 'migration_not_found', 'تعذر العثور على ترحيل برقم الإصدار:٪ s.', 'migration_lang.php'),
( 'arabic', 'migration_multiple_version', 'هناك عمليات ترحيل متعددة برقم الإصدار نفسه:٪ s.', 'migration_lang.php'),
( 'arabic', 'migration_class_doesnt_exist', 'تعذر العثور على فئة الترحيل "٪ s".', 'migration_lang.php'),
( 'arabic', 'migration_missing_up_method', 'فئة الترحيل "٪ s" تفتقد طريقة "أوب".', 'migration_lang.php'),
( 'arabic', 'migration_missing_down_method', 'فئة الترحيل "٪ s" تفتقد طريقة "لأسفل".', 'migration_lang.php'),
( 'arabic', 'migration_invalid_filename', 'يحتوي الترحيل "٪ s" على اسم ملف غير صالح.', 'migration_lang.php'),
( 'arabic', 'terabyte_abbr', 'TB', 'number_lang.php'),
( 'arabic', 'gigabyte_abbr', 'GB', 'number_lang.php'),
( 'arabic', 'megabyte_abbr', 'MB', 'number_lang.php'),
( 'arabic', 'kilobyte_abbr', 'KB', 'number_lang.php'),
( 'arabic', 'bytes', 'Bytes', 'number_lang.php'),
( 'arabic', 'pagination_first_link', 'وlsaquo. أول', 'pagination_lang.php'),
( 'arabic', 'pagination_next_link', 'وGT.', 'pagination_lang.php'),
( 'arabic', 'pagination_prev_link', 'لعلامة & lt؛', 'pagination_lang.php'),
( 'arabic', 'pagination_last_link', 'الماضي & rsaquo؛', 'pagination_lang.php'),
( 'arabic', 'profiler_controller_info', 'صف دراسي/طريقة', 'profiler_lang.php'),
( 'arabic', 'profiler_benchmarks', 'العلامات المرجعية', 'profiler_lang.php'),
( 'arabic', 'profiler_database', 'قاعدة البيانات', 'profiler_lang.php'),
( 'arabic', 'profiler_queries', 'استفسارات', 'profiler_lang.php'),
( 'arabic', 'profiler_get_data', 'احصل على البيانات', 'profiler_lang.php'),
( 'arabic', 'profiler_uri_string', 'URI STRING', 'profiler_lang.php'),
( 'arabic', 'profiler_post_data', 'أرسل البيانات', 'profiler_lang.php'),
( 'arabic', 'profiler_memory_usage', 'استخدام الذاكرة', 'profiler_lang.php'),
( 'arabic', 'profiler_config', 'متغيرات CONFIG', 'profiler_lang.php'),
( 'arabic', 'profiler_session_data', 'بيانات الجلسة', 'profiler_lang.php'),
( 'arabic', 'profiler_headers', 'عناوين HTTP', 'profiler_lang.php'),
( 'arabic', 'profiler_no_db', 'برنامج تشغيل قاعدة البيانات غير محملة حاليا', 'profiler_lang.php'),
( 'arabic', 'profiler_no_queries', 'تم تشغيل أي استعلامات', 'profiler_lang.php'),
( 'arabic', 'profiler_no_post', 'لا توجد بيانات POST', 'profiler_lang.php'),
( 'arabic', 'profiler_no_get', 'لا توجد بيانات GET', 'profiler_lang.php'),
( 'arabic', 'profiler_no_uri', 'لا توجد بيانات URI', 'profiler_lang.php'),
( 'arabic', 'profiler_no_memory', 'استخدام الذاكرة غير متوفر', 'profiler_lang.php'),
( 'arabic', 'profiler_no_profiles', 'لا توجد بيانات للملف الشخصي - تم تعطيل جميع أقسام Profiler.', 'profiler_lang.php'),
( 'arabic', 'profiler_section_hide', 'إخفاء', 'profiler_lang.php'),
( 'arabic', 'profiler_section_show', 'تبين', 'profiler_lang.php'),
( 'arabic', 'profiler_seconds', 'ثواني', 'profiler_lang.php'),
( 'arabic', 'ut_test_datatype', 'اختبار نوع البيانات', 'unit_test_lang.php'),
( 'arabic', 'ut_res_datatype', 'من المتوقع نوع البيانات', 'unit_test_lang.php'),
( 'arabic', 'ut_test_name', 'اسم الاختبار', 'unit_test_lang.php'),
( 'arabic', 'ut_result', 'نتيجة', 'unit_test_lang.php'),
( 'arabic', 'ut_line', 'رقم السطر', 'unit_test_lang.php'),
( 'arabic', 'ut_file', 'اسم الملف', 'unit_test_lang.php'),
( 'arabic', 'ut_undefined', 'اسم اختبار غير معرف', 'unit_test_lang.php'),
( 'arabic', 'ut_failed', 'فشل', 'unit_test_lang.php'),
( 'arabic', 'ut_passed', 'مرت', 'unit_test_lang.php'),
( 'arabic', 'ut_boolean', 'منطقية', 'unit_test_lang.php'),
( 'arabic', 'ut_integer', 'عدد صحيح', 'unit_test_lang.php'),
( 'arabic', 'ut_float', 'تطفو', 'unit_test_lang.php'),
( 'arabic', 'ut_double', 'تطفو', 'unit_test_lang.php'),
( 'arabic', 'ut_string', 'خيط', 'unit_test_lang.php'),
( 'arabic', 'ut_array', 'مجموعة مصفوفة', 'unit_test_lang.php'),
( 'arabic', 'ut_object', 'موضوع', 'unit_test_lang.php'),
( 'arabic', 'ut_resource', 'مورد', 'unit_test_lang.php'),
( 'arabic', 'ut_null', 'لا شيء', 'unit_test_lang.php'),
( 'arabic', 'ut_notes', 'ملاحظات', 'unit_test_lang.php'),
( 'arabic', 'upload_userfile_not_set', 'غير قادر على العثور على متغير نشر يسمى userfile.', 'upload_lang.php'),
( 'arabic', 'upload_file_exceeds_limit', 'يتجاوز الملف الذي تم تحميله الحد الأقصى للحجم المسموح به في ملف تهيئة PHP.', 'upload_lang.php'),
( 'arabic', 'upload_file_exceeds_form_limit', 'يتجاوز الملف الذي تم تحميله الحد الأقصى للحجم المسموح به في نموذج التقديم.', 'upload_lang.php'),
( 'arabic', 'upload_no_temp_directory', 'المجلد المؤقت مفقود.', 'upload_lang.php'),
( 'arabic', 'upload_file_partial', 'الملف تم تحميله جزئيًا فقط.', 'upload_lang.php'),
( 'arabic', 'upload_stopped_by_extension', 'تم إيقاف تحميل الملف عن طريق التمديد.', 'upload_lang.php'),
( 'arabic', 'upload_unable_to_write_file', 'لا يمكن كتابة الملف على القرص.', 'upload_lang.php'),
( 'arabic', 'upload_no_file_selected', 'لم تحدد ملفًا لتحميله.', 'upload_lang.php'),
( 'arabic', 'upload_invalid_filesize', 'الملف الذي تحاول تحميله أكبر من الحجم المسموح به.', 'upload_lang.php'),
( 'arabic', 'upload_invalid_filetype', 'غير مسموح باستخدام filetype الذي تحاول تحميله.', 'upload_lang.php'),
( 'arabic', 'upload_destination_error', 'حدثت مشكلة أثناء محاولة نقل الملف الذي تم تحميله إلى الوجهة النهائية.', 'upload_lang.php'),
( 'arabic', 'upload_invalid_dimensions', 'الصورة التي تحاول تحميلها لا تتناسب مع الأبعاد المسموح بها.', 'upload_lang.php'),
( 'arabic', 'upload_bad_filename', 'اسم الملف الذي أرسلته موجود بالفعل على الخادم.', 'upload_lang.php'),
( 'arabic', 'upload_no_filepath', 'لا يبدو مسار التحميل صالحًا.', 'upload_lang.php'),
( 'arabic', 'upload_no_file_types', 'لم تحدد أي أنواع ملفات مسموح بها.', 'upload_lang.php'),
( 'arabic', 'upload_not_writable', 'لا يبدو مجلد وجهة التحميل قابلاً للكتابة.', 'upload_lang.php'),
( 'arabic', 'enable_patient_account', 'قم بتمكين حساب المريض', 'main_lang.php'),
( 'arabic', 'patient_account_msg', '(ستكون قادرًا على تسديد دفعة أكثر من مبلغ الفاتورة. سيتم الاحتفاظ بالدفع الإضافي في حساب المريض. هذا المبلغ يمكن تستخدم لضبط الفاتورة في المرة القادمة)', 'main_lang.php'),
( 'arabic', 'all_items', 'جميع المواد', 'main_lang.php'),
( 'arabic', 'all_purchase', 'كل شراء', 'main_lang.php'),
( 'arabic', 'stock_reports', 'تقرير الاسهم', 'main_lang.php'),
( 'arabic', 'favicon', 'فافيكون', 'main_lang.php'),
( 'arabic', 'preferred_size_icon', 'الأيقونة المفضلة الحجم 16 × 16', 'main_lang.php'),
( 'arabic', 'content_section', 'قسم المحتوى', 'main_lang.php'); 