INSERT INTO %dbprefix%language_master (language_name,is_default,is_loaded) VALUES ('english',1,1);
INSERT INTO %dbprefix%language_data (l_name, l_index, l_value, file_name) VALUES
( 'english', 'app_name', 'Chikitsa', 'main_lang.php'),
( 'english', 'app_tagline', 'Clinic Management System', 'main_lang.php'),
( 'english', 'main_title', 'Chikitsa - Clinic Management System', 'main_lang.php'),
( 'english', 'cmp_version', 'Chikitsa Version', 'main_lang.php'),
( 'english', 'cmp_name', 'Sanskruti Technologies', 'main_lang.php'),
( 'english', 'about_chikitsa', 'About Chikitsa', 'main_lang.php'),
( 'english', 'sign_in', 'Sign In', 'main_lang.php'),
( 'english', '7min', '7 Min', 'main_lang.php'),
( 'english', '30min', '30 Min', 'main_lang.php'),
( 'english', '15min', '15 Min', 'main_lang.php'),
( 'english', '1hr', '1 Hour', 'main_lang.php'),
( 'english', '5min', '5 Min', 'main_lang.php'),
( 'english', 'main_section', 'Main Section', 'main_lang.php'),
( 'english', 'second_section', 'Second Section', 'main_lang.php'),
( 'english', 'title_color', 'Title Color', 'main_lang.php'),
( 'english', 'background_color', 'Background Color', 'main_lang.php'),
( 'english', 'text_color', 'Text Color', 'main_lang.php'),
( 'english', 'third_section', 'Third Section', 'main_lang.php'),
( 'english', 'about', 'About', 'main_lang.php'),
( 'english', 'about_settings', 'About Settings', 'main_lang.php'),
( 'english', 'about_page_settings', 'About Page Settings', 'main_lang.php'),
( 'english', 'access_on_menu', 'Access on menu', 'main_lang.php'),
( 'english', 'access_code', 'Access Code', 'main_lang.php'),
( 'english', 'account_group_master', 'Account Group Master', 'main_lang.php'),
( 'english', 'account_group', 'Account Group', 'main_lang.php'),
( 'english', 'account_details_meta', 'Account Details Meta', 'main_lang.php'),
( 'english', 'account_group_name', 'Account Group Name', 'main_lang.php'),
( 'english', 'account_group_order', 'Account Group Order', 'main_lang.php'),
( 'english', 'accounts', 'Accounts', 'main_lang.php'),
( 'english', 'action', 'Action', 'main_lang.php'),
( 'english', 'account_groups', 'Account Groups', 'main_lang.php'),
( 'english', 'account', 'Account', 'main_lang.php'),
( 'english', 'actions', 'Actions', 'main_lang.php'),
( 'english', 'amount', 'Amount', 'main_lang.php'),
( 'english', 'activate', 'Activate', 'main_lang.php'),
( 'english', 'available_quantity', 'Available Quantity', 'main_lang.php'),
( 'english', 'add', 'Add', 'main_lang.php'),
( 'english', 'add_condition', 'Add Condition', 'main_lang.php'),
( 'english', 'additional_css', 'Additional CSS', 'main_lang.php'),
( 'english', 'add_another_medicine', 'Add Another Medicine', 'main_lang.php'),
( 'english', 'add_appointment', 'Add Appointment', 'main_lang.php'),
( 'english', 'add_slider', 'Add Slider', 'main_lang.php'),
( 'english', 'add_alerts', 'Add Alerts', 'main_lang.php'),
( 'english', 'add_about_page_post', 'Add About Page Post', 'main_lang.php'),
( 'english', 'add_footer_section', 'Add Footer Section', 'main_lang.php'),
( 'english', 'add_top_section', 'Add Top Section', 'main_lang.php'),
( 'english', 'add_image', 'Add New Image', 'main_lang.php'),
( 'english', 'add_category', 'Add Category', 'main_lang.php'),
( 'english', 'add_footer_credit', 'Add Footer credit Section', 'main_lang.php'),
( 'english', 'add_detail', 'Allow to add Detail', 'main_lang.php'),
( 'english', 'add_department', 'Add Department', 'main_lang.php'),
( 'english', 'add_from_users', 'Add From Users', 'main_lang.php'),
( 'english', 'add_new_user', 'Add New User', 'main_lang.php'),
( 'english', 'add_more_contact_number', 'Add More Contact Numbers', 'main_lang.php'),
( 'english', 'add_news', 'Add News', 'main_lang.php'),
( 'english', 'add_test', 'Add Test', 'main_lang.php'),
( 'english', 'add_as_medicine', 'Add as Medicine', 'main_lang.php'),
( 'english', 'add_inquiry', 'Add Inquiry', 'main_lang.php'),
( 'english', 'add_service', 'Add Service', 'main_lang.php'),
( 'english', 'add_section', 'Add Section', 'main_lang.php'),
( 'english', 'add_reference_by', 'Add Reference By', 'main_lang.php'),
( 'english', 'add_refund', 'Add Refund', 'main_lang.php'),
( 'english', 'add_user', 'Add User', 'main_lang.php'),
( 'english', 'add_treatment', 'Add Treatment', 'main_lang.php'),
( 'english', 'add_language', 'Add Language', 'main_lang.php'),
( 'english', 'add_fee', 'Add Fee', 'main_lang.php'),
( 'english', 'add_payment', 'Add Payment', 'main_lang.php'),
( 'english', 'add_extension', 'Add Extensions', 'main_lang.php'),
( 'english', 'add_bottom_section', 'Add Bottom Section', 'main_lang.php'),
( 'english', 'add_patient', 'Add Patient', 'main_lang.php'),
( 'english', 'add_license_key', 'Add License Key', 'main_lang.php'),
( 'english', 'added_date', 'Added Date', 'main_lang.php'),
( 'english', 'address', 'Address', 'main_lang.php'),
( 'english', 'addresstype', 'Address Type', 'main_lang.php'),
( 'english', 'address_line_1', 'Address Line 1', 'main_lang.php'),
( 'english', 'address_line_2', 'Address Line 2', 'main_lang.php'),
( 'english', 'administration', 'Administration', 'main_lang.php'),
( 'english', 'administrator', 'Administrator', 'main_lang.php'),
( 'english', 'appointment_calendar', 'Appointment Calendar', 'main_lang.php'),
( 'english', 'adult_teeth', 'Adult Teeth', 'main_lang.php'),
( 'english', 'amount_paid', 'Amount Paid', 'main_lang.php'),
( 'english', 'admin_log_in', 'Admin LogIn', 'main_lang.php'),
( 'english', 'after', 'After', 'main_lang.php'),
( 'english', 'afternoon_time', 'Afternoon Time', 'main_lang.php'),
( 'english', 'afternoon', 'A', 'main_lang.php'),
( 'english', 'age', 'Age', 'main_lang.php'),
( 'english', 'alerts', 'Alerts', 'main_lang.php'),
( 'english', 'alert_settings', 'Alert Setting', 'main_lang.php'),
( 'english', 'alert_sms_log', 'Alert Sms log', 'main_lang.php'),
( 'english', 'alert_email_log', 'Alert Email log', 'main_lang.php'),
( 'english', 'alert_time', 'Alert Time', 'main_lang.php'),
( 'english', 'alert_name', 'Alert Name', 'main_lang.php'),
( 'english', 'all', 'All', 'main_lang.php'),
( 'english', 'allot', 'Allot', 'main_lang.php'),
( 'english', 'allow_menu', 'Allow Menus', 'main_lang.php'),
( 'english', 'allow_center', 'Allow Centers', 'main_lang.php'),
( 'english', 'allocate', 'Allocate', 'main_lang.php'),
( 'english', 'allow_repeat', 'Allow Repeat', 'main_lang.php'),
( 'english', 'all_sell', 'All Sell', 'main_lang.php'),
( 'english', 'all_users', 'All Users', 'main_lang.php'),
( 'english', 'stock_all_sell', 'All Sell', 'main_lang.php'),
( 'english', 'all_patients', 'All Patients', 'main_lang.php'),
( 'english', 'all_clinic', 'All Clinic', 'main_lang.php'),
( 'english', 'all_folloups', 'All Follow Ups', 'main_lang.php'),
( 'english', 'appointment', 'Appointment', 'main_lang.php'),
( 'english', 'appointment_details', 'Appointment Details', 'main_lang.php'),
( 'english', 'appointments', 'Appointments', 'main_lang.php'),
( 'english', 'appointment_report', 'Appointment Report', 'main_lang.php'),
( 'english', 'appointment_reason', 'Appointment Reason', 'main_lang.php'),
( 'english', 'appointment_date', 'Appointment Date ', 'main_lang.php'),
( 'english', 'appointment_time_interval', 'Appointment Time Interval', 'main_lang.php'),
( 'english', 'availability', 'Availability', 'main_lang.php'),
( 'english', 'assets', 'Assets', 'main_lang.php'),
( 'english', 'available', 'Available', 'main_lang.php'),
( 'english', 'available_stock', 'Available Stock', 'main_lang.php'),
( 'english', 'average_price', 'Average Price', 'main_lang.php'),
( 'english', 'additional_detail_label', 'Additional Detail Label', 'main_lang.php'),
( 'english', 'amount_in_account', 'Amount In Account', 'main_lang.php'),
( 'english', 'approve', 'Approve', 'main_lang.php'),
( 'english', 'adjust_from_account', 'Adjust From Account', 'main_lang.php'),
( 'english', 'additional_detail', 'Additional Detail', 'main_lang.php'),
( 'english', 'baby_teeth', 'Baby Teeth', 'main_lang.php'),
( 'english', 'back', 'Back', 'main_lang.php'),
( 'english', 'batch', 'Batch', 'main_lang.php'),
( 'english', 'backup', 'Backup', 'main_lang.php'),
( 'english', 'back_to', 'Back To', 'main_lang.php'),
( 'english', 'backup_restore', 'Backup Restore', 'main_lang.php'),
( 'english', 'back_to_app', 'Back to Appointment', 'main_lang.php'),
( 'english', 'book_an_appoinment', 'Book An Appointment', 'main_lang.php'),
( 'english', 'balance', 'Balance', 'main_lang.php'),
( 'english', 'back_to_visit', 'Back To Visit', 'main_lang.php'),
( 'english', 'balance_amount', 'Balance Amount', 'main_lang.php'),
( 'english', 'bank_payment', 'Bank Payment', 'main_lang.php'),
( 'english', 'bank_payments', 'Bank Payments', 'main_lang.php'),
( 'english', 'bank_receipt', 'Bank Receipt', 'main_lang.php'),
( 'english', 'barcode', 'Barcode', 'main_lang.php'),
( 'english', 'bed', 'Bed', 'main_lang.php'),
( 'english', 'bank_receipts', 'Bank Receipts', 'main_lang.php'),
( 'english', 'before', 'Before', 'main_lang.php'),
( 'english', 'beds', 'Beds', 'main_lang.php'),
( 'english', 'bill', 'Bill', 'main_lang.php'),
( 'english', 'bill_no', 'Bill No.', 'main_lang.php'),
( 'english', 'bills', 'Bills', 'main_lang.php'),
( 'english', 'bill_amount', 'Billed Amount', 'main_lang.php'),
( 'english', 'bill_details', 'Bill Details', 'main_lang.php'),
( 'english', 'bill_id', 'Bill ID', 'main_lang.php'),
( 'english', 'bills_payments', 'Payment', 'main_lang.php'),
( 'english', 'bill_date', 'Bill Date', 'main_lang.php'),
( 'english', 'bill_number', 'Bill Number', 'main_lang.php'),
( 'english', 'bill_type', 'Bill Type', 'main_lang.php'),
( 'english', 'back_to_payment', 'Back to Payments', 'main_lang.php'),
( 'english', 'back_to_appointment', 'Back to Appointments', 'main_lang.php'),
( 'english', 'book', 'Book', 'main_lang.php'),
( 'english', 'body', 'Body', 'main_lang.php'),
( 'english', 'bought_at', 'Bought At', 'main_lang.php'),
( 'english', 'bill_report', 'Bill Detail Report', 'main_lang.php'),
( 'english', 'bought_quantity', 'Bought Quantity', 'main_lang.php'),
( 'english', 'bought_avg', 'Bought Avg', 'main_lang.php'),
( 'english', 'browse', 'Browse', 'main_lang.php'),
( 'english', 'blood_group', 'Blood Group', 'main_lang.php'),
( 'english', 'book_appoinment', 'Book Appointment', 'main_lang.php'),
( 'english', 'bottom_section_1', 'Bottom Section 1', 'main_lang.php'),
( 'english', 'bottom_section_3', 'Bottom Section 3', 'main_lang.php'),
( 'english', 'button', 'Button', 'main_lang.php'),
( 'english', 'button_text', 'Button Text', 'main_lang.php'),
( 'english', 'bottom_section_2', 'Bottom Section 2', 'main_lang.php'),
( 'english', 'button_url', 'Button URL', 'main_lang.php'),
( 'english', 'bonus_percentage', 'Bonus Percentage', 'main_lang.php'),
( 'english', 'bonus', 'Bonus', 'main_lang.php'),
( 'english', 'billed', 'Billed', 'main_lang.php'),
( 'english', 'calendar', 'Monthly Calendar', 'main_lang.php'),
( 'english', 'calendar_hours', 'Daily Calendar', 'main_lang.php'),
( 'english', 'cancel', 'Cancel', 'main_lang.php'),
( 'english', 'cash', 'Cash', 'main_lang.php'),
( 'english', 'cancelled', 'Cancelled', 'main_lang.php'),
( 'english', 'case_number', 'Case No.', 'main_lang.php'),
( 'english', 'case', 'Cases', 'main_lang.php'),
( 'english', 'cases', 'Cases', 'main_lang.php'),
( 'english', 'cash_receipt', 'Cash Receipt', 'main_lang.php'),
( 'english', 'cash_receipts', 'Cash Receipts', 'main_lang.php'),
( 'english', 'cash_payment', 'Cash Payment', 'main_lang.php'),
( 'english', 'case_date', 'Case Date', 'main_lang.php'),
( 'english', 'category', 'Category', 'main_lang.php'),
( 'english', 'categories', 'Categories', 'main_lang.php'),
( 'english', 'cash_payments', 'Cash Payments', 'main_lang.php'),
( 'english', 'center', 'Center', 'main_lang.php'),
( 'english', 'centers', 'Centers', 'main_lang.php'),
( 'english', 'center_logo', 'Center Logo', 'main_lang.php'),
( 'english', 'center_details', 'Center Details', 'main_lang.php'),
( 'english', 'center_name', 'Center Name', 'main_lang.php'),
( 'english', 'center_code', 'Center Code', 'main_lang.php'),
( 'english', 'change', 'Change', 'main_lang.php'),
( 'english', 'change_center', 'Change Center', 'main_lang.php'),
( 'english', 'change_theme_color', 'Theme Settings', 'main_lang.php'),
( 'english', 'change_language', 'Change Language', 'main_lang.php'),
( 'english', 'change_profile', 'Change Profile', 'main_lang.php'),
( 'english', 'change_status_of_field', 'Change status of field', 'main_lang.php'),
( 'english', 'change_timezone', 'Change Time Zone', 'main_lang.php'),
( 'english', 'change_template', 'Change Template', 'main_lang.php'),
( 'english', 'charges', 'Charges', 'main_lang.php'),
( 'english', 'charges_fees', 'Charges/Fees', 'main_lang.php'),
( 'english', 'cheque', 'Cheque', 'main_lang.php'),
( 'english', 'cheque_number', 'Cheque Number', 'main_lang.php'),
( 'english', 'chikitsa_new_version_available', ' is available. Update Now!', 'main_lang.php'),
( 'english', 'choose_file', 'Choose File', 'main_lang.php'),
( 'english', 'city', 'City', 'main_lang.php'),
( 'english', 'close', 'Close', 'main_lang.php'),
( 'english', 'clinic', 'Center', 'main_lang.php'),
( 'english', 'clear_data', 'Clear Data', 'main_lang.php'),
( 'english', 'clinic_address', 'Clinic Address', 'main_lang.php'),
( 'english', 'clinic_details', 'Clinic Details', 'main_lang.php'),
( 'english', 'clinic_end_time', 'Clinic End Time', 'main_lang.php'),
( 'english', 'clinic_landline', 'Clinic Landline', 'main_lang.php'),
( 'english', 'clinic_note', 'Clinic Note', 'main_lang.php'),
( 'english', 'clinic_logo', 'Clinic Logo', 'main_lang.php'),
( 'english', 'clinic_name', 'Clinic Name', 'main_lang.php'),
( 'english', 'clinic_phone_1', 'Clinic Phone 1', 'main_lang.php'),
( 'english', 'clinic_phone_2', 'Clinic Phone 2', 'main_lang.php'),
( 'english', 'clinic_start_time', 'Clinic Start Time', 'main_lang.php'),
( 'english', 'clinic_runs_full_day', 'Clinic Runs Full Day', 'main_lang.php'),
( 'english', 'cost', 'Cost', 'main_lang.php'),
( 'english', 'column_1', 'Column 1', 'main_lang.php'),
( 'english', 'column_2', 'Column 2', 'main_lang.php'),
( 'english', 'complete', 'Complete', 'main_lang.php'),
( 'english', 'completed_appointment', 'Completed Appointment', 'main_lang.php'),
( 'english', 'completed_sessions', 'Completed Sessions', 'main_lang.php'),
( 'english', 'company', 'Company', 'main_lang.php'),
( 'english', 'company_information', 'Company Information', 'main_lang.php'),
( 'english', 'compare', 'Compare', 'main_lang.php'),
( 'english', 'content', 'Content', 'main_lang.php'),
( 'english', 'conditions', 'Conditions', 'main_lang.php'),
( 'english', 'country_code', 'Country Code', 'main_lang.php'),
( 'english', 'contact', 'Contact', 'main_lang.php'),
( 'english', 'contact_details', 'Contact Details', 'main_lang.php'),
( 'english', 'continue', 'Continue', 'main_lang.php'),
( 'english', 'copyright', '&copy; 2016', 'main_lang.php'),
( 'english', 'copyright_text', 'Copyright Text', 'main_lang.php'),
( 'english', 'consultation_in', 'Consultation In', 'main_lang.php'),
( 'english', 'confirm_password', 'Confirm Password', 'main_lang.php'),
( 'english', 'consultation', 'Consultation', 'main_lang.php'),
( 'english', 'copyright_url', 'Copyright URL', 'main_lang.php'),
( 'english', 'consultation_out', 'Consultation Out', 'main_lang.php'),
( 'english', 'contact_number', 'Contact Number', 'main_lang.php'),
( 'english', 'cost_price', 'Cost Price', 'main_lang.php'),
( 'english', 'country', 'Country', 'main_lang.php'),
( 'english', 'curr_pre', 'Currency Prefix', 'main_lang.php'),
( 'english', 'curr_post', 'Currency Postfix', 'main_lang.php'),
( 'english', 'cr_ac_name', 'Cr. A/c Name', 'main_lang.php'),
( 'english', 'created_by', 'Created By', 'main_lang.php'),
( 'english', 'column_1_header', 'Column 1 - Header', 'main_lang.php'),
( 'english', 'custom_details', 'Custom Details', 'main_lang.php'),
( 'english', 'currency', 'Currency', 'main_lang.php'),
( 'english', 'column_1_content', 'Column 1 - Content', 'main_lang.php'),
( 'english', 'ccavenue', 'CCAvenue', 'main_lang.php'),
( 'english', 'contact_us', 'Contact Us', 'main_lang.php'),
( 'english', 'copy', 'Copy', 'main_lang.php'),
( 'english', 'change_language_file', 'Change Words in Language File', 'main_lang.php'),
( 'english', 'ccavenue_settings', 'CCAvenue Settings', 'main_lang.php'),
( 'english', 'create_language_file', 'Create New Language File', 'main_lang.php'),
( 'english', 'cancelled_appoinment_by_patient', 'In case of appointment cancellation by Patient, refund will have to be done manually', 'main_lang.php'),
( 'english', 'compare_image', 'Minimum two images required for comparision', 'main_lang.php'),
( 'english', 'dr_ac_name', 'Dr. A/c Name', 'main_lang.php'),
( 'english', 'day', 'Day', 'main_lang.php'),
( 'english', 'daily', 'Daily', 'main_lang.php'),
( 'english', 'does_not_have_value', 'Does not have value', 'main_lang.php'),
( 'english', 'days', 'Days', 'main_lang.php'),
( 'english', 'dose', 'Dose', 'main_lang.php'),
( 'english', 'daily_hour', 'Daily/ Per Hour', 'main_lang.php'),
( 'english', 'daily_per_bed_charge', 'Per Bed Charge ( Daily )', 'main_lang.php'),
( 'english', 'date', 'Date', 'main_lang.php'),
( 'english', 'dashboard', 'Dashboard', 'main_lang.php'),
( 'english', 'date_format', 'Date Format', 'main_lang.php'),
( 'english', 'deallocate', 'Deallocate', 'main_lang.php'),
( 'english', 'degrees', 'Degrees', 'main_lang.php'),
( 'english', 'deactivate', 'Deactivate', 'main_lang.php'),
( 'english', 'delete', 'Delete', 'main_lang.php'),
( 'english', 'delete_item', 'Delete Item', 'main_lang.php'),
( 'english', 'delete_supplier', 'Delete Sullpier', 'main_lang.php'),
( 'english', 'delete_treatment', 'Delete Treatment', 'main_lang.php'),
( 'english', 'delete_user', 'Delete User', 'main_lang.php'),
( 'english', 'department', 'Department', 'main_lang.php'),
( 'english', 'departments', 'Departments', 'main_lang.php'),
( 'english', 'department_name', 'Department Name', 'main_lang.php'),
( 'english', 'desired_stock', 'Desired Stock', 'main_lang.php'),
( 'english', 'detail', 'Detail', 'main_lang.php'),
( 'english', 'details', 'Details', 'main_lang.php'),
( 'english', 'default', 'Default', 'main_lang.php'),
( 'english', 'due_amount', 'Due Amount', 'main_lang.php'),
( 'english', 'discount', 'Discount', 'main_lang.php'),
( 'english', 'display', 'Display', 'main_lang.php'),
( 'english', 'dismiss', 'Dismiss', 'main_lang.php'),
( 'english', 'dismissed', 'Dismissed', 'main_lang.php'),
( 'english', 'display_google_ads', 'Display Google Ads', 'main_lang.php'),
( 'english', 'display_in', 'Display In', 'main_lang.php'),
( 'english', 'display_name', 'Display Name', 'main_lang.php'),
( 'english', 'discount_amount', 'Discount Amount', 'main_lang.php'),
( 'english', 'discount_percentage', 'Discount Percentage', 'main_lang.php'),
( 'english', 'dob', 'Date Of Birth', 'main_lang.php'),
( 'english', 'doctors', 'Doctors', 'main_lang.php'),
( 'english', 'doctor_share', 'Doctor Share', 'main_lang.php'),
( 'english', 'doctor_name', 'Doctor Name', 'main_lang.php'),
( 'english', 'doctor', 'Doctor', 'main_lang.php'),
( 'english', 'doctor_availability', 'Doctor Availability', 'main_lang.php'),
( 'english', 'doctor_detail', 'Doctor Detail', 'main_lang.php'),
( 'english', 'doctor_bonus_report', 'Doctor Bonus Report', 'main_lang.php'),
( 'english', 'doctor_inavailability', 'Doctor Unavailability', 'main_lang.php'),
( 'english', 'doctor_unavailability', 'Doctor Unavailability', 'main_lang.php'),
( 'english', 'doctor_schedule', 'Doctor Schedule', 'main_lang.php'),
( 'english', 'download', 'Download', 'main_lang.php'),
( 'english', 'download_extension', 'Download Extension', 'main_lang.php'),
( 'english', 'downloading_files', 'Downloading Files', 'main_lang.php'),
( 'english', 'doctor_preferences', 'Doctor Preferences', 'main_lang.php'),
( 'english', 'duration', 'Duration', 'main_lang.php'),
( 'english', 'dr', 'Dr.', 'main_lang.php'),
( 'english', 'description', 'Description', 'main_lang.php'),
( 'english', 'duplicate', 'Duplicate', 'main_lang.php'),
( 'english', 'disease', 'Disease', 'main_lang.php'),
( 'english', 'diagnosed_diseases', 'Diagnosed Disease', 'main_lang.php'),
( 'english', 'diseases', 'Diseases', 'main_lang.php'),
( 'english', 'eraser', 'Eraser', 'main_lang.php'),
( 'english', 'decimal_symbol', 'Decimal Symbol', 'main_lang.php'),
( 'english', 'erpnext_sync', 'Erpnext Sync', 'main_lang.php'),
( 'english', 'erpnext_url', 'Erpnext URL', 'main_lang.php'),
( 'english', 'enable_about_page', 'Enable About Page', 'main_lang.php'),
( 'english', 'end_date', 'End Date', 'main_lang.php'),
( 'english', 'edit', 'Edit', 'main_lang.php'),
( 'english', 'end_time', 'End Time', 'main_lang.php'),
( 'english', 'edit_Contact', 'Edit Contact', 'main_lang.php'),
( 'english', 'edit_section', 'Edit Section', 'main_lang.php'),
( 'english', 'edit_treatment', 'Edit Treatment', 'main_lang.php'),
( 'english', 'edit_medicine_too', 'Edit Medicine too', 'main_lang.php'),
( 'english', 'edit_user', 'Edit User', 'main_lang.php'),
( 'english', 'email', 'Email', 'main_lang.php'),
( 'english', 'edit_test', 'Edit Test', 'main_lang.php'),
( 'english', 'email_alert_name', 'Email Alert Name', 'main_lang.php'),
( 'english', 'email_log', 'Email Log', 'main_lang.php'),
( 'english', 'email_id', 'Email ID', 'main_lang.php'),
( 'english', 'email_bill', 'Email Bill', 'main_lang.php'),
( 'english', 'email_settings', 'Email Settings', 'main_lang.php'),
( 'english', 'established_patient', 'Established Patient', 'main_lang.php'),
( 'english', 'enter_details_to_login', 'Enter Details To Login ', 'main_lang.php'),
( 'english', 'enter_email_address', 'Enter Email Address ', 'main_lang.php'),
( 'english', 'extracting', 'Extracting', 'main_lang.php'),
( 'english', 'extraction_failed', 'Extraction Failed', 'main_lang.php'),
( 'english', 'extensions', 'Extensions', 'main_lang.php'),
( 'english', 'expenditure', 'Expenditure', 'main_lang.php'),
( 'english', 'experience', 'Experience', 'main_lang.php'),
( 'english', 'exceptional_days', 'Exceptional Days', 'main_lang.php'),
( 'english', 'export_to_excel', 'Export to Excel', 'main_lang.php'),
( 'english', 'expiry_date', 'Expiry Date', 'main_lang.php'),
( 'english', 'enter_new_password', 'Enter your new password below', 'main_lang.php'),
( 'english', 'enable_news', 'Enable News Page', 'main_lang.php'),
( 'english', 'enable_online_appointment', 'Enable Online Appointment Booking', 'main_lang.php'),
( 'english', 'enable_ccavenue', 'Enable CCAvenue', 'main_lang.php'),
( 'english', 'enable_paypal', 'Enable PayPal', 'main_lang.php'),
( 'english', 'enable_admin_approval', 'Enable Admin Approval', 'main_lang.php'),
( 'english', 'enable_sandbox', 'Enable Sandbox', 'main_lang.php'),
( 'english', 'enable_service_page', 'Enable Service Page', 'main_lang.php'),
( 'english', 'email_alert_time', 'Email Alert Time', 'main_lang.php'),
( 'english', 'edit_format', 'Edit Format', 'main_lang.php'),
( 'english', 'email_format', 'Email Format', 'main_lang.php'),
( 'english', 'edit_language', 'Edit Language', 'main_lang.php'),
( 'english', 'face', 'Face', 'main_lang.php'),
( 'english', 'facebook_link', 'Facebook Link', 'main_lang.php'),
( 'english', 'facebook', 'Facebook', 'main_lang.php'),
( 'english', 'fax', 'Fax', 'main_lang.php'),
( 'english', 'fees', 'Fees', 'main_lang.php'),
( 'english', 'fees_detail', 'Fees', 'main_lang.php'),
( 'english', 'female', 'Female', 'main_lang.php'),
( 'english', 'file', 'File', 'main_lang.php'),
( 'english', 'file_content', 'File Content', 'main_lang.php'),
( 'english', 'filter', 'Filter', 'main_lang.php'),
( 'english', 'first', 'First', 'main_lang.php'),
( 'english', 'first_name', 'First Name', 'main_lang.php'),
( 'english', 'fields', 'Fields', 'main_lang.php'),
( 'english', 'field_label', 'Field Label', 'main_lang.php'),
( 'english', 'find_us_here', 'Find Us Here', 'main_lang.php'),
( 'english', 'field_options', 'Field Option', 'main_lang.php'),
( 'english', 'field_order', 'Field Order', 'main_lang.php'),
( 'english', 'field_name', 'Field Name', 'main_lang.php'),
( 'english', 'field_type', 'Field Type', 'main_lang.php'),
( 'english', 'field_width', 'Field Width', 'main_lang.php'),
( 'english', 'field_status', 'Field Status', 'main_lang.php'),
( 'english', 'foc', 'F.O.C.', 'main_lang.php'),
( 'english', 'follow', 'Follow', 'main_lang.php'),
( 'english', 'follow_on', 'Follow On', 'main_lang.php'),
( 'english', 'follow_up', 'Follow Up', 'main_lang.php'),
( 'english', 'follow_ups', 'Follow Ups', 'main_lang.php'),
( 'english', 'footer_credits', 'Footer Credits', 'main_lang.php'),
( 'english', 'footer_settings', 'Footer Settings', 'main_lang.php'),
( 'english', 'footer_credit_settings', 'Footer Credit Settings', 'main_lang.php'),
( 'english', 'for', 'For', 'main_lang.php'),
( 'english', 'forgot_password', 'Forgot Password?', 'main_lang.php'),
( 'english', 'form', 'Form', 'main_lang.php'),
( 'english', 'found', 'Found', 'main_lang.php'),
( 'english', 'frequency', 'Frequency', 'main_lang.php'),
( 'english', 'from_date', 'From Date', 'main_lang.php'),
( 'english', 'from_time', 'From Time', 'main_lang.php'),
( 'english', 'from_name', 'From Name', 'main_lang.php'),
( 'english', 'to_time', 'To Time', 'main_lang.php'),
( 'english', 'from_doctor', 'From Doctor', 'main_lang.php'),
( 'english', 'frontend', 'Frontend', 'main_lang.php'),
( 'english', 'framework', 'Framework', 'main_lang.php'),
( 'english', 'full_day', 'Full Day', 'main_lang.php'),
( 'english', 'fixed_amount', 'Fixed Amount', 'main_lang.php'),
( 'english', 'from_email', 'From Email', 'main_lang.php'),
( 'english', 'featured', 'Featured', 'main_lang.php'),
( 'english', 'featured_image', 'Featured Image', 'main_lang.php'),
( 'english', 'footer_section_1', 'Footer Section 1', 'main_lang.php'),
( 'english', 'footer_section_2', 'Footer Section 2', 'main_lang.php'),
( 'english', 'footer_section_3', 'Footer Section 3', 'main_lang.php'),
( 'english', 'gender', 'Gender', 'main_lang.php'),
( 'english', 'footer_section_4', 'Footer Section 4', 'main_lang.php'),
( 'english', 'file_size', 'Allow Maximum File size (in KB)', 'main_lang.php'),
( 'english', 'file_type', 'Allowed File Types', 'main_lang.php'),
( 'english', 'file_type_msg', 'Seperate File types by jpeg|jpg|png etc.', 'main_lang.php'),
( 'english', 'gain', 'Gain', 'main_lang.php'),
( 'english', 'gallery', 'Gallery', 'main_lang.php'),
( 'english', 'go', 'Go', 'main_lang.php'),
( 'english', 'google_plus', 'Google Plus', 'main_lang.php'),
( 'english', 'general_settings', 'General Settings', 'main_lang.php'),
( 'english', 'group_by', 'Group By', 'main_lang.php'),
( 'english', 'group', 'Group', 'main_lang.php'),
( 'english', 'group_name', 'Group Name', 'main_lang.php'),
( 'english', 'gallery_setting_msg', '(You can manage the allowed File Types and allowed File Size from Administration > Settings > Gallery)', 'main_lang.php'),
( 'english', 'header', 'Header', 'main_lang.php'),
( 'english', 'hidden', 'Hidden', 'main_lang.php'),
( 'english', 'home', 'Home', 'main_lang.php'),
( 'english', 'hour', 'hour', 'main_lang.php'),
( 'english', 'hourly', 'Hourly', 'main_lang.php'),
( 'english', 'hourly_per_bed_charge', 'Per Bed Charge ( Hourly )', 'main_lang.php'),
( 'english', 'html_content', 'HTML Content', 'main_lang.php'),
( 'english', 'header_settings', 'Header Settings', 'main_lang.php'),
( 'english', 'header_contact_number', 'Header Contact Number', 'main_lang.php'),
( 'english', 'has_additional_details', 'Has Additional Details', 'main_lang.php'),
( 'english', 'home_settings', 'Home Page Settings', 'main_lang.php'),
( 'english', 'has_value', 'Has Value', 'main_lang.php'),
( 'english', 'heading', 'Heading', 'main_lang.php'),
( 'english', 'history', 'History', 'main_lang.php'),
( 'english', 'home_page_settings', 'Home Page Settings', 'main_lang.php'),
( 'english', 'home_page_slider', 'Home Page Slider', 'main_lang.php'),
( 'english', 'home_page_bottom_section', 'Home Page Bottom Section', 'main_lang.php'),
( 'english', 'home_page_top_section', 'Home Page Top Section', 'main_lang.php'),
( 'english', 'half_day', 'Half Day', 'main_lang.php'),
( 'english', 'invoice', 'Invoice', 'main_lang.php'),
( 'english', 'if_field', 'If Field', 'main_lang.php'),
( 'english', 'id', 'Id', 'main_lang.php'),
( 'english', 'icon', 'Icon', 'main_lang.php'),
( 'english', 'inavailablity', 'Inavailablity', 'main_lang.php'),
( 'english', 'install', 'Install', 'main_lang.php'),
( 'english', 'invoice_prefix', 'Invoice Prefix', 'main_lang.php'),
( 'english', 'installing', 'Installing', 'main_lang.php'),
( 'english', 'invoice_number', 'Invoice Number', 'main_lang.php'),
( 'english', 'invoice_details', 'Invoice Details', 'main_lang.php'),
( 'english', 'invoice_settings', 'Invoice Settings', 'main_lang.php'),
( 'english', 'in_minutes', 'in minutes', 'main_lang.php'),
( 'english', 'in_group', 'In Group', 'main_lang.php'),
( 'english', 'instructions', 'Instructions', 'main_lang.php'),
( 'english', 'is_active', 'Is Active', 'main_lang.php'),
( 'english', 'is_checked', 'Is checked', 'main_lang.php'),
( 'english', 'is_unchecked', 'Is unchecked', 'main_lang.php'),
( 'english', 'item', 'Item', 'main_lang.php'),
( 'english', 'item_number', 'Item Number', 'main_lang.php'),
( 'english', 'is_default', 'Is Default', 'main_lang.php'),
( 'english', 'item_name', 'Item Name', 'main_lang.php'),
( 'english', 'item_type', 'Item Type', 'main_lang.php'),
( 'english', 'items', 'Items', 'main_lang.php'),
( 'english', 'image', 'Image', 'main_lang.php'),
( 'english', 'import', 'Import CSV', 'main_lang.php'),
( 'english', 'images', 'Images', 'main_lang.php'),
( 'english', 'image_id', 'Image ID', 'main_lang.php'),
( 'english', 'image_name', 'Image Name', 'main_lang.php'),
( 'english', 'image_path', 'Image Path', 'main_lang.php'),
( 'english', 'issue_refund', 'Issue Refund', 'main_lang.php'),
( 'english', 'income', 'Income', 'main_lang.php'),
( 'english', 'individual', 'Individual', 'main_lang.php'),
( 'english', 'information', 'Information', 'main_lang.php'),
( 'english', 'joining_date', 'Joining Date', 'main_lang.php'),
( 'english', 'journal_voucher', 'Journal Voucher', 'main_lang.php'),
( 'english', 'jurisdiction', 'Subject to Surat Jurisdiction', 'main_lang.php'),
( 'english', 'journal_vouchers', 'Journal Vouchers', 'main_lang.php'),
( 'english', 'key', 'Key', 'main_lang.php'),
( 'english', 'landline', 'Landline', 'main_lang.php'),
( 'english', 'languages', 'Languages', 'main_lang.php'),
( 'english', 'last_name', 'Last Name', 'main_lang.php'),
( 'english', 'last', 'Last', 'main_lang.php'),
( 'english', 'lab_tests', 'Lab Tests', 'main_lang.php'),
( 'english', 'lab_instructions', 'Lab instructions', 'main_lang.php'),
( 'english', 'lab_reports', 'Lab Reports', 'main_lang.php'),
( 'english', 'lab_test', 'Lab Test', 'main_lang.php'),
( 'english', 'latest_news', 'Latest News', 'main_lang.php'),
( 'english', 'length_invoice', 'Length of Invoice Number', 'main_lang.php'),
( 'english', 'login', 'Login', 'main_lang.php'),
( 'english', 'login_yourself_to_get_access', 'Login yourself to get access', 'main_lang.php'),
( 'english', 'log_out', 'Log Out', 'main_lang.php'),
( 'english', 'license_key', 'License Key', 'main_lang.php'),
( 'english', 'licence_number', 'License Number', 'main_lang.php'),
( 'english', 'line2', 'Line 2', 'main_lang.php'),
( 'english', 'line1', 'Line 1', 'main_lang.php'),
( 'english', 'list_master', 'List Master', 'main_lang.php'),
( 'english', 'liabilities', 'Liabilities', 'main_lang.php'),
( 'english', 'language', 'Language', 'main_lang.php'),
( 'english', 'language_name', 'Language Name', 'main_lang.php'),
( 'english', 'latest', 'Latest', 'main_lang.php'),
( 'english', 'link', 'Link', 'main_lang.php'),
( 'english', 'link_text', 'Link Text', 'main_lang.php'),
( 'english', 'link_url', 'Link URL', 'main_lang.php'),
( 'english', 'marker', 'Marker', 'main_lang.php'),
( 'english', 'male', 'Male', 'main_lang.php'),
( 'english', 'marking', 'Marking', 'main_lang.php'),
( 'english', 'marking_images', 'Marking Images', 'main_lang.php'),
( 'english', 'max_patient', 'Max Patients At a Time', 'main_lang.php'),
( 'english', 'medicine', 'Medicine', 'main_lang.php'),
( 'english', 'menu_access', 'Menu Access', 'main_lang.php'),
( 'english', 'medicine_store_bill', 'Medicine Store Bill', 'main_lang.php'),
( 'english', 'medicine_name', 'Medicine Name', 'main_lang.php'),
( 'english', 'mobile', 'Mobile', 'main_lang.php'),
( 'english', 'mobile_no', 'Mobile No', 'main_lang.php'),
( 'english', 'middle', 'Middle', 'main_lang.php'),
( 'english', 'medicines', 'Medicines', 'main_lang.php'),
( 'english', 'module', 'Module', 'main_lang.php'),
( 'english', 'mode', 'Mode', 'main_lang.php'),
( 'english', 'morning', 'M', 'main_lang.php'),
( 'english', 'mrp', 'M.R.P.', 'main_lang.php'),
( 'english', 'modules', 'Modules', 'main_lang.php'),
( 'english', 'middle_name', 'Middle Name', 'main_lang.php'),
( 'english', 'morning_time', 'Morning Time', 'main_lang.php'),
( 'english', 'message', 'Message', 'main_lang.php'),
( 'english', 'minutes', 'minutes', 'main_lang.php'),
( 'english', 'make', 'Make', 'main_lang.php'),
( 'english', 'media', 'Media', 'main_lang.php'),
( 'english', 'make_appointment', 'Make Appointment', 'main_lang.php'),
( 'english', 'merchant_id', 'Merchant ID', 'main_lang.php'),
( 'english', 'my_account', 'My Account', 'main_lang.php'),
( 'english', 'minimum_stock', 'Minimum Stock Required', 'main_lang.php'),
( 'english', 'make_an_appointment', 'Make an Appointment', 'main_lang.php'),
( 'english', 'maximum_about_posts', '(You have reached the Maximum About Posts that can be added)', 'main_lang.php'),
( 'english', 'maximum_footer_posts', '(You have reached the Maximum Footer Sections Posts that can be added)', 'main_lang.php'),
( 'english', 'maximum_top_posts', '(You have reached the Maximum Top Sections Posts that can be added) ', 'main_lang.php'),
( 'english', 'maximum_footer_credits', '(You have reached the Maximum Footer credit Posts that can be added) ', 'main_lang.php'),
( 'english', 'maximum_bottom_posts', '(You have reached the Maximum Bottom Sections Posts that can be added) ', 'main_lang.php'),
( 'english', 'minimum_income', 'Minimum Income', 'main_lang.php'),
( 'english', 'month', 'Month', 'main_lang.php'),
( 'english', 'medical', 'Medical', 'main_lang.php'),
( 'english', 'name', 'Name', 'main_lang.php'),
( 'english', 'none', 'None', 'main_lang.php'),
( 'english', 'next_follow_up', 'Next Followup After', 'main_lang.php'),
( 'english', 'net_total', 'Net Total', 'main_lang.php'),
( 'english', 'news_date', 'News Date', 'main_lang.php'),
( 'english', 'next_follow_date', 'Next Followup Date', 'main_lang.php'),
( 'english', 'news_title', 'Title', 'main_lang.php'),
( 'english', 'news', 'News', 'main_lang.php'),
( 'english', 'new', 'New', 'main_lang.php'),
( 'english', 'new_appointment', 'New Appointment', 'main_lang.php'),
( 'english', 'new_contact', 'New Contact', 'main_lang.php'),
( 'english', 'new_inquiry', 'New Inquiry', 'main_lang.php'),
( 'english', 'new_inquires', 'New Inquiries', 'main_lang.php'),
( 'english', 'new_password', 'New Password', 'main_lang.php'),
( 'english', 'new_sell', 'New Sell', 'main_lang.php'),
( 'english', 'news_setting', 'News Page Settings', 'main_lang.php'),
( 'english', 'no', 'No', 'main_lang.php'),
( 'english', 'night', 'N', 'main_lang.php'),
( 'english', 'non_taxable_revenue', 'Non Taxable Revenue', 'main_lang.php'),
( 'english', 'no_of_beds', 'No. of Beds', 'main_lang.php'),
( 'english', 'not_available', 'Not Available', 'main_lang.php'),
( 'english', 'notes', 'Notes', 'main_lang.php'),
( 'english', 'notes_for_patient', 'Notes for Patient', 'main_lang.php'),
( 'english', 'number', 'Number', 'main_lang.php'),
( 'english', 'number_of_columns', 'Number Of Columns', 'main_lang.php'),
( 'english', 'news_page_settings', 'News Page Settings', 'main_lang.php'),
( 'english', 'night_time', 'Night Time', 'main_lang.php'),
( 'english', 'needs_cash_calc', 'Needs Cash Calculator', 'main_lang.php'),
( 'english', 'nurse', 'Nurse', 'main_lang.php'),
( 'english', 'no_prescription', 'No Prescription Found', 'main_lang.php'),
( 'english', 'number_of_decimal', 'Decimal Places', 'main_lang.php'),
( 'english', 'no_image_for_comparision', 'No Images Selected for comparision', 'main_lang.php'),
( 'english', 'on', 'On', 'main_lang.php'),
( 'english', 'our', 'Our', 'main_lang.php'),
( 'english', 'our_team', 'Our Team', 'main_lang.php'),
( 'english', 'office', 'Office', 'main_lang.php'),
( 'english', 'our_services', 'Our services', 'main_lang.php'),
( 'english', 'office_branch', 'Office Branch', 'main_lang.php'),
( 'english', 'old_password', 'Old Password', 'main_lang.php'),
( 'english', 'option', 'Option', 'main_lang.php'),
( 'english', 'opening', 'Opening', 'main_lang.php'),
( 'english', 'opening_stock', 'Opening Stock', 'main_lang.php'),
( 'english', 'other', 'Other', 'main_lang.php'),
( 'english', 'of_appoinment_time', 'of appoinment time', 'main_lang.php'),
( 'english', 'paid', 'Paid', 'main_lang.php'),
( 'english', 'page_title', 'Page Title', 'main_lang.php'),
( 'english', 'paid_cash', 'Paid Cash', 'main_lang.php'),
( 'english', 'paid_amount', 'Paid Amount', 'main_lang.php'),
( 'english', 'parent', 'Parent', 'main_lang.php'),
( 'english', 'particular', 'Particular', 'main_lang.php'),
( 'english', 'password', 'Password', 'main_lang.php'),
( 'english', 'patient', 'Patient', 'main_lang.php'),
( 'english', 'patient_detail', 'Patient Detail', 'main_lang.php'),
( 'english', 'patient_details', 'Patient Detail', 'main_lang.php'),
( 'english', 'patient_account', 'Patient Account', 'main_lang.php'),
( 'english', 'patient_id', 'Patient ID', 'main_lang.php'),
( 'english', 'patient_name', 'Patient Name', 'main_lang.php'),
( 'english', 'patients', 'Patients', 'main_lang.php'),
( 'english', 'patient_notes', 'Patient Notes', 'main_lang.php'),
( 'english', 'patient_report', 'Patient Report', 'main_lang.php'),
( 'english', 'patient_added_after', 'Patient Added After', 'main_lang.php'),
( 'english', 'payment', 'Payment', 'main_lang.php'),
( 'english', 'payments', 'Payments', 'main_lang.php'),
( 'english', 'patient_wise_alert_settings', 'Patient wise Alert Settings', 'main_lang.php'),
( 'english', 'payment_methods', 'Payment Methods', 'main_lang.php'),
( 'english', 'payment_form', 'Payment Form', 'main_lang.php'),
( 'english', 'payment_amount', 'Payment Amount', 'main_lang.php'),
( 'english', 'payment_adjustement', 'Payment Adjustement', 'main_lang.php'),
( 'english', 'payment_date', 'Payment Date', 'main_lang.php'),
( 'english', 'payment_method', 'Payment Method', 'main_lang.php'),
( 'english', 'payment_mode', 'Payment Mode', 'main_lang.php'),
( 'english', 'payment_history', 'Payment History', 'main_lang.php'),
( 'english', 'payment_status', 'Payment Status', 'main_lang.php'),
( 'english', 'paypal_settings', 'PayPal Settings', 'main_lang.php'),
( 'english', 'paypal_business_email', 'PayPal Business Email', 'main_lang.php'),
( 'english', 'pending', 'Pending', 'main_lang.php'),
( 'english', 'pending_payments', 'Pending Payments', 'main_lang.php'),
( 'english', 'per_bed_charge', 'Per Bed Charge', 'main_lang.php'),
( 'english', 'per_day', 'Per Day', 'main_lang.php'),
( 'english', 'phone_number', 'Phone Number', 'main_lang.php'),
( 'english', 'per_hour', 'Per Hour', 'main_lang.php'),
( 'english', 'placeholder', 'Placeholder', 'main_lang.php'),
( 'english', 'post', 'Post', 'main_lang.php'),
( 'english', 'posts', 'Posts', 'main_lang.php'),
( 'english', 'post_content', 'Post Content', 'main_lang.php'),
( 'english', 'postal_code', 'Postal Code', 'main_lang.php'),
( 'english', 'post_title', 'Post Title', 'main_lang.php'),
( 'english', 'post_type', 'Post Type', 'main_lang.php'),
( 'english', 'print', 'Print', 'main_lang.php'),
( 'english', 'print_receipt', 'Print Receipt', 'main_lang.php'),
( 'english', 'profile', 'Profile', 'main_lang.php'),
( 'english', 'progress', 'Progress', 'main_lang.php'),
( 'english', 'prev_bal', 'Previous Balance', 'main_lang.php'),
( 'english', 'prev_due', 'Previous Due', 'main_lang.php'),
( 'english', 'preferred_size', 'Preferred size 260X60', 'main_lang.php'),
( 'english', 'price', 'Price', 'main_lang.php'),
( 'english', 'print_report', 'Print Report', 'main_lang.php'),
( 'english', 'prescription', 'Prescription', 'main_lang.php'),
( 'english', 'preferences', 'Preferences', 'main_lang.php'),
( 'english', 'purchase', 'Purchase', 'main_lang.php'),
( 'english', 'purchase_date', 'Purchase Date', 'main_lang.php'),
( 'english', 'purchase_return', 'Purchase Return', 'main_lang.php'),
( 'english', 'purchase_register', 'Purchase Register', 'main_lang.php'),
( 'english', 'promocode', 'Promocode', 'main_lang.php'),
( 'english', 'promocodes', 'Promocodes', 'main_lang.php'),
( 'english', 'percentage', 'Percentage', 'main_lang.php'),
( 'english', 'pending_appointments', 'Pending Appointments', 'main_lang.php'),
( 'english', 'pending_payment', 'Pending Payment', 'main_lang.php'),
( 'english', 'planned_appointment', 'This is Appointment is a Planned Session', 'main_lang.php'),
( 'english', 'planned_visit', 'This is Visit is a Planned Session', 'main_lang.php'),
( 'english', 'planned_sessions', 'Planned Sessions', 'main_lang.php'),
( 'english', 'payment_pending', 'Keep Payment pending until approved', 'main_lang.php'),
( 'english', 'phone', 'Phone', 'main_lang.php'),
( 'english', 'paypal', 'PayPal', 'main_lang.php'),
( 'english', 'pay', 'Pay', 'main_lang.php'),
( 'english', 'prefered_language', 'Prefered Language', 'main_lang.php'),
( 'english', 'prescribed_medicine', 'Prescribed Medicine', 'main_lang.php'),
( 'english', 'quantity', 'Quantity', 'main_lang.php'),
( 'english', 'qrcode', 'QRcode', 'main_lang.php'),
( 'english', 'fixed', 'Fixed', 'main_lang.php'),
( 'english', 'variable', 'Variable', 'main_lang.php'),
( 'english', 'decimal_places', 'Decimal Places', 'main_lang.php'),
( 'english', 'in', 'In', 'main_lang.php'),
( 'english', 'rate', 'Rate', 'main_lang.php'),
( 'english', 'reason', 'Reason', 'main_lang.php'),
( 'english', 'response', 'Response', 'main_lang.php'),
( 'english', 'rebrand', 'Rebrand', 'main_lang.php'),
( 'english', 'receipt_template', 'Receipt Templates', 'main_lang.php'),
( 'english', 'refund', 'Refund', 'main_lang.php'),
( 'english', 'reference_by', 'Reference By', 'main_lang.php'),
( 'english', 'receipt', 'Receipt', 'main_lang.php'),
( 'english', 'report', 'Report', 'main_lang.php'),
( 'english', 'restore', 'Restore', 'main_lang.php'),
( 'english', 'remark', 'Remark', 'main_lang.php'),
( 'english', 'reset_password', 'Reset Password', 'main_lang.php'),
( 'english', 'remove_logo', 'Remove Logo', 'main_lang.php'),
( 'english', 'reports', 'Reports', 'main_lang.php'),
( 'english', 'remove', 'Remove', 'main_lang.php'),
( 'english', 'remove_patient_image', 'Remove Patient Image', 'main_lang.php'),
( 'english', 'renew_license', 'Renew License', 'main_lang.php'),
( 'english', 'renew_license_to_update', 'Renew License To Update', 'main_lang.php'),
( 'english', 'quantity_exceeds', 'Required Quantity exceeds Available Stock', 'main_lang.php'),
( 'english', 'receive_fee', 'Received fees for Professional services and other charges of our', 'main_lang.php'),
( 'english', 'room', 'Room', 'main_lang.php'),
( 'english', 'rooms_categories', 'Rooms Categories', 'main_lang.php'),
( 'english', 'rooms_allocate', 'Rooms Allocate', 'main_lang.php'),
( 'english', 'rooms', 'Rooms', 'main_lang.php'),
( 'english', 'rooms_calendar', 'Rooms Calendar', 'main_lang.php'),
( 'english', 'rooms_beds', 'Rooms/ Beds', 'main_lang.php'),
( 'english', 'register', 'Register', 'main_lang.php'),
( 'english', 'registration', 'Registration', 'main_lang.php'),
( 'english', 'reference_details', 'Reference Details', 'main_lang.php'),
( 'english', 'resend_code', 'Resend Code', 'main_lang.php'),
( 'english', 'residence', 'Residence', 'main_lang.php'),
( 'english', 'restore_backup', 'Restore Backup', 'main_lang.php'),
( 'english', 'return', 'Return', 'main_lang.php'),
( 'english', 'return_change', 'Return Change', 'main_lang.php'),
( 'english', 'return_date', 'Return Date', 'main_lang.php'),
( 'english', 'room_charges', 'Room Charges Reports', 'main_lang.php'),
( 'english', 'room_number', 'Room Number', 'main_lang.php'),
( 'english', 'refund_date', 'Refund Date', 'main_lang.php'),
( 'english', 'refund_amount', 'Refund Amount', 'main_lang.php'),
( 'english', 'refund_note', 'Refund Note', 'main_lang.php'),
( 'english', 'refresh', 'Refresh', 'main_lang.php'),
( 'english', 'reject', 'Reject', 'main_lang.php'),
( 'english', 'required_quantity', 'Required Quantity', 'main_lang.php'),
( 'english', 'reason_for_appointment', 'Reason for Appointment', 'main_lang.php'),
( 'english', 'rtl', 'RTL', 'main_lang.php'),
( 'english', 'reload_language_file', 'Reload Language File', 'main_lang.php'),
( 'english', 'right_to_left', 'Right to Left Language', 'main_lang.php'),
( 'english', 'reload_language_file_instruction', 'This will overwrite the changes from language file.', 'main_lang.php'),
( 'english', 'slider_image', 'Slider Image', 'main_lang.php'),
( 'english', 'sign_up', 'Sign up', 'main_lang.php'),
( 'english', 'slider_1', 'Slider 1', 'main_lang.php'),
( 'english', 'slider_3', 'Slider 3', 'main_lang.php'),
( 'english', 'slider_2', 'Slider 2', 'main_lang.php'),
( 'english', 'slider', 'Slider', 'main_lang.php'),
( 'english', 'section', 'Section', 'main_lang.php'),
( 'english', 'section_1', 'Section 1', 'main_lang.php'),
( 'english', 'section_3', 'Section 3', 'main_lang.php'),
( 'english', 'section_2', 'Section 2', 'main_lang.php'),
( 'english', 'section_4', 'Section 4', 'main_lang.php'),
( 'english', 'section_name', 'Section Name', 'main_lang.php'),
( 'english', 'senderid', 'Sender ID', 'main_lang.php'),
( 'english', 'schedule', 'Schedule', 'main_lang.php'),
( 'english', 'save', 'Save', 'main_lang.php'),
( 'english', 'second_number', 'Second Number', 'main_lang.php'),
( 'english', 'search', 'Search', 'main_lang.php'),
( 'english', 'search_by_name', 'Search By Name', 'main_lang.php'),
( 'english', 'select', 'Select', 'main_lang.php'),
( 'english', 'select_lang', 'Select your Language', 'main_lang.php'),
( 'english', 'select_currency', 'Select Currency', 'main_lang.php'),
( 'english', 'select_duration', 'Select Duration', 'main_lang.php'),
( 'english', 'select_date', 'Select Date', 'main_lang.php'),
( 'english', 'select_media_image', 'Select Media Image', 'main_lang.php'),
( 'english', 'select_time_zone', 'Select Your Time zone', 'main_lang.php'),
( 'english', 'select_all', 'Select All', 'main_lang.php'),
( 'english', 'select_blood_group', 'Select Blood Group', 'main_lang.php'),
( 'english', 'select_mode', 'Select Mode', 'main_lang.php'),
( 'english', 'sell', 'Sell', 'main_lang.php'),
( 'english', 'subject', 'Subject', 'main_lang.php'),
( 'english', 'shortcode_label', 'Shortcodes you need to use:', 'main_lang.php'),
( 'english', 'shortcode_patient_name', '[patient_name] - Patient Name', 'main_lang.php'),
( 'english', 'shortcode_patient_id', '[patient_id] - Patient ID', 'main_lang.php'),
( 'english', 'shortcode_clinic_logo', '[clinic_logo] - Clinic Logo - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_clinic_name', '[clinic_name] - Clinic Name - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_clinic_address', '[clinic_address] - Clinic Address - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_clinic_mobile', '[mobile] - Mobile - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_clinic_landline', '[landline] - Landline - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_clinic_email', '[email] - Email - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_tag_line', '[tag_line] - Tag Line - Can be set in Clinic Detail', 'main_lang.php'),
( 'english', 'shortcode_doctor_name', '[doctor_name] - Doctor Name', 'main_lang.php'),
( 'english', 'shortcode_dose_time', '[dose_time] - Morning | Tuesday | Wednesday', 'main_lang.php'),
( 'english', 'shortcode_sms_medicine_details', '[sms_medicine_details] - All Medicine Details in Table Format', 'main_lang.php'),
( 'english', 'shortcode_medicine_details', '[medicine_details] - All Medicine Details in Table Format', 'main_lang.php'),
( 'english', 'shortcode_appointment_time', '[appointment_time] - Appointment Time', 'main_lang.php'),
( 'english', 'shortcode_appointment_date', '[appointment_date] - Appointment Date', 'main_lang.php'),
( 'english', 'shortcode_appointment_status', '[appointment_status] - Appointment Status', 'main_lang.php'),
( 'english', 'shortcode_bill', '[bill] - Soft Copy of Bill', 'main_lang.php'),
( 'english', 'shortcode_appointment_reason', '[appointment_reason] - Appointment Reason', 'main_lang.php'),
( 'english', 'shortcode_bill_id', '[bill_id] - ID of Bill', 'main_lang.php'),
( 'english', 'shortcode_bill_date', '[bill_date] - Date of Bill', 'main_lang.php'),
( 'english', 'shortcode_bill_time', '[bill_time] - Time of Bill', 'main_lang.php'),
( 'english', 'shortcode_previous_due', '[previous_due] - Previous Dues', 'main_lang.php'),
( 'english', 'shortcode_patient_email', '[patient_email] - Email ID', 'main_lang.php'),
( 'english', 'shortcode_visit_date', '[visit_date] - Date of Visit', 'main_lang.php'),
( 'english', 'shortcode_patient_sex', '[sex] - Patient Sex', 'main_lang.php'),
( 'english', 'shortcode_patient_age', '[age] - Patient Age', 'main_lang.php'),
( 'english', 'shortcode_total', '[total] - Total of this Bill', 'main_lang.php'),
( 'english', 'shortcode_patient_phone_number', '[patient_phone_number] - Phone Number', 'main_lang.php'),
( 'english', 'shortcode_paid_amount', '[paid_amount] - Paid Amount', 'main_lang.php'),
( 'english', 'shortcode_username', '[username] - Will be replaced by Username', 'main_lang.php'),
( 'english', 'shortcode_password', '[password] - Will be replaced by Password', 'main_lang.php'),
( 'english', 'shortcode_senderid', '[senderid] - Will be replaced by Sender ID', 'main_lang.php'),
( 'english', 'shortcode_mobileno', '[mobileno] - Will be replaced by Receipient Mobile Number', 'main_lang.php'),
( 'english', 'shortcode_message', '[message] - Will be replaced by Message', 'main_lang.php'),
( 'english', 'shortcode_template_id', '[template_id] - Will be replaced by Template ID', 'main_lang.php'),
( 'english', 'shortcode_bill_columns', 'Columns to display in table For Bill', 'main_lang.php'),
( 'english', 'share_type', 'Share Type', 'main_lang.php'),
( 'english', 'shortcode_prescription_columns', 'Columns to display in table For Prescription', 'main_lang.php'),
( 'english', 'sms_settings', 'SMS Settings', 'main_lang.php'),
( 'english', 'smtp_instructions', 'Below fields only required for sending SMTP Emails', 'main_lang.php'),
( 'english', 'services_settings', 'Services Settings', 'main_lang.php'),
( 'english', 'stock_sell', 'Sell', 'main_lang.php'),
( 'english', 'sell_id', 'Sell Id', 'main_lang.php'),
( 'english', 'set', 'Set', 'main_lang.php'),
( 'english', 'sell_amount', 'Sell Amount', 'main_lang.php'),
( 'english', 'sell_date', 'Sell Date', 'main_lang.php'),
( 'english', 'sell_price', 'Sell Price', 'main_lang.php'),
( 'english', 'set_as_default', 'Set as Default', 'main_lang.php'),
( 'english', 'settings', 'Settings', 'main_lang.php'),
( 'english', 'services', 'Services', 'main_lang.php'),
( 'english', 'service', 'Service', 'main_lang.php'),
( 'english', 'services_type', 'Services Types', 'main_lang.php'),
( 'english', 'session', 'Session', 'main_lang.php'),
( 'english', 'sessions', 'Sessions', 'main_lang.php'),
( 'english', 'session_report', 'Session Report', 'main_lang.php'),
( 'english', 'setting', 'Setting', 'main_lang.php'),
( 'english', 'signature', 'Signature', 'main_lang.php'),
( 'english', 'software_name', 'Software Name', 'main_lang.php'),
( 'english', 'sold_at', 'Sold At', 'main_lang.php'),
( 'english', 'sold_avg', 'Sold Avg', 'main_lang.php'),
( 'english', 'sold_quantity', 'Sold Quantity', 'main_lang.php'),
( 'english', 'special_access', 'Special Access', 'main_lang.php'),
( 'english', 'sr_no', 'Sr. No.', 'main_lang.php'),
( 'english', 'start_date', 'Start Date', 'main_lang.php'),
( 'english', 'staff', 'Staff', 'main_lang.php'),
( 'english', 'start_time', 'Start Time', 'main_lang.php'),
( 'english', 'specialization', 'Specialization', 'main_lang.php'),
( 'english', 'state', 'State', 'main_lang.php'),
( 'english', 'static_prefix', 'Static Prefix', 'main_lang.php'),
( 'english', 'status', 'Status', 'main_lang.php'),
( 'english', 'stock', 'Stock', 'main_lang.php'),
( 'english', 'stock_item', 'Item', 'main_lang.php'),
( 'english', 'stock_report', 'Report', 'main_lang.php'),
( 'english', 'stock_stock_report', 'Stock Report', 'main_lang.php'),
( 'english', 'submit', 'Submit', 'main_lang.php'),
( 'english', 'supplier', 'Supplier', 'main_lang.php'),
( 'english', 'sub_total', 'Sub Total', 'main_lang.php'),
( 'english', 'suppliers', 'Suppliers', 'main_lang.php'),
( 'english', 'stock_suppliers', 'Suppliers', 'main_lang.php'),
( 'english', 'stock_purchase_report', 'Purchase Report', 'main_lang.php'),
( 'english', 'stock_purchase', 'Purchase', 'main_lang.php'),
( 'english', 'support', 'Support', 'main_lang.php'),
( 'english', 'supplier_name', 'Supplier Name', 'main_lang.php'),
( 'english', 'support_text', 'Support Text', 'main_lang.php'),
( 'english', 'select_beautician', 'Select Doctor', 'main_lang.php'),
( 'english', 'select_doctor', 'Select Doctor', 'main_lang.php'),
( 'english', 'support_url', 'Support URL', 'main_lang.php'),
( 'english', 'select_a_Slot', 'Select a Slot', 'main_lang.php'),
( 'english', 'select_fields', 'Select Fields', 'main_lang.php'),
( 'english', 'sell_return', 'Sell Return', 'main_lang.php'),
( 'english', 'select_tax_rate', 'Select Tax Rate', 'main_lang.php'),
( 'english', 'select_patient', 'Select Patient', 'main_lang.php'),
( 'english', 'stock_sell_report', 'All Sell Report', 'main_lang.php'),
( 'english', 'total_sell_report', 'Total Sell Report', 'main_lang.php'),
( 'english', 'synchronize', 'Synchronize', 'main_lang.php'),
( 'english', 'smtp_host', 'SMTP Host', 'main_lang.php'),
( 'english', 'smtp_port', 'SMTP Port', 'main_lang.php'),
( 'english', 'sms_url', 'URL to send SMS', 'main_lang.php'),
( 'english', 'sms_alert_time', 'SMS Alert Time', 'main_lang.php'),
( 'english', 'sms_template_id', 'SMS Template ID', 'main_lang.php'),
( 'english', 'sms_format', 'SMS Format', 'main_lang.php'),
( 'english', 'sms_log', 'SMS Log', 'main_lang.php'),
( 'english', 'ssn_id', 'Adhar Number', 'main_lang.php'),
( 'english', 'save_complete', 'Save and Complete', 'main_lang.php'),
( 'english', 'save_and_bill', 'Save and Create Bill', 'main_lang.php'),
( 'english', 'set_alert_time', 'Set Alert Time', 'main_lang.php'),
( 'english', 'slot', 'Slot', 'main_lang.php'),
( 'english', 'total_appointments', 'Total Appointments', 'main_lang.php'),
( 'english', 'to', 'To', 'main_lang.php'),
( 'english', 'take_backup', 'Take Backup', 'main_lang.php'),
( 'english', 'tag_line', 'Tag Line', 'main_lang.php'),
( 'english', 'task', 'Task', 'main_lang.php'),
( 'english', 'tax', 'Tax', 'main_lang.php'),
( 'english', 'tasks', 'Tasks', 'main_lang.php'),
( 'english', 'tax_amount', 'Tax Amount', 'main_lang.php'),
( 'english', 'tax_revenue', 'Tax Revenue', 'main_lang.php'),
( 'english', 'taxable', 'Taxable', 'main_lang.php'),
( 'english', 'taxable_revenue', 'Taxable Revenue', 'main_lang.php'),
( 'english', 'tax_rates', 'Tax Rates', 'main_lang.php'),
( 'english', 'tax_report', 'Tax Report', 'main_lang.php'),
( 'english', 'tax_rate', 'Tax Rate', 'main_lang.php'),
( 'english', 'template_name', 'Template Name', 'main_lang.php'),
( 'english', 'template_content', 'Template Content', 'main_lang.php'),
( 'english', 'thanks', 'Received with Thanks', 'main_lang.php'),
( 'english', 'time', 'Time', 'main_lang.php'),
( 'english', 'test', 'Test', 'main_lang.php'),
( 'english', 'timings', 'Timings', 'main_lang.php'),
( 'english', 'timestamp', 'Timestamp', 'main_lang.php'),
( 'english', 'time_format', 'Time Format', 'main_lang.php'),
( 'english', 'time_zone', 'Time Zone', 'main_lang.php'),
( 'english', 'to_admin_panel', ' To Admin Pannel', 'main_lang.php'),
( 'english', 'time_interval', 'Time Interval', 'main_lang.php'),
( 'english', 'to_date', 'To Date', 'main_lang.php'),
( 'english', 'title', 'Title', 'main_lang.php'),
( 'english', 'to_be_paid', 'To Be Paid', 'main_lang.php'),
( 'english', 'total', 'Total', 'main_lang.php'),
( 'english', 'total_due_after_payment', 'Total Due After Payment', 'main_lang.php'),
( 'english', 'treatment', 'Treatment', 'main_lang.php'),
( 'english', 'transport', 'Transport', 'main_lang.php'),
( 'english', 'treatment_report', 'Treatment Report', 'main_lang.php'),
( 'english', 'treatments', 'Treatments', 'main_lang.php'),
( 'english', 'treatment_name', 'Treatment Name', 'main_lang.php'),
( 'english', 'treatment_charges', 'Treatment Charges/Fees', 'main_lang.php'),
( 'english', 'type', 'Type', 'main_lang.php'),
( 'english', 'twitter', 'Twitter', 'main_lang.php'),
( 'english', 'twitter_link', 'Twitter Link', 'main_lang.php'),
( 'english', 'theme', 'Theme', 'main_lang.php'),
( 'english', 'txn_id', 'TXN ID', 'main_lang.php'),
( 'english', 'tax_rate_name', 'Tax Rate Name', 'main_lang.php'),
( 'english', 'test_name', 'Test Name', 'main_lang.php'),
( 'english', 'tests', 'Tests', 'main_lang.php'),
( 'english', 'text', 'Text', 'main_lang.php'),
( 'english', 'top_section_2', 'Top Section 2', 'main_lang.php'),
( 'english', 'top_section_1', 'Top Section 1', 'main_lang.php'),
( 'english', 'top_section_3', 'Top Section 3', 'main_lang.php'),
( 'english', 'this_payment_is_rejected', 'This Payment is rejected', 'main_lang.php'),
( 'english', 'types', 'Types', 'main_lang.php'),
( 'english', 'thousands_separator', 'Thousands Separator', 'main_lang.php'),
( 'english', 'upload', 'Upload', 'main_lang.php'),
( 'english', 'upload_extension', 'Upload Extensions', 'main_lang.php'),
( 'english', 'update', 'Update', 'main_lang.php'),
( 'english', 'username', 'Username', 'main_lang.php'),
( 'english', 'updates', 'Updates', 'main_lang.php'),
( 'english', 'update_now', 'Update Now', 'main_lang.php'),
( 'english', 'user', 'User', 'main_lang.php'),
( 'english', 'url', 'URL', 'main_lang.php'),
( 'english', 'users', 'Users', 'main_lang.php'),
( 'english', 'using', 'Using', 'main_lang.php'),
( 'english', 'upload_language_file', 'Upload existing language file', 'main_lang.php'),
( 'english', 'unpacking_zip_package', 'Unpacking Zip Package', 'main_lang.php'),
( 'english', 'vaccine', 'Vaccine', 'main_lang.php'),
( 'english', 'vaccines', 'Vaccines', 'main_lang.php'),
( 'english', 'upcoming_appointments', 'Upcoming Appointments', 'main_lang.php'),
( 'english', 'vaccine_master', 'Vaccination', 'main_lang.php'),
( 'english', 'vaccine_name', 'Vaccine Name', 'main_lang.php'),
( 'english', 'view', 'View', 'main_lang.php'),
( 'english', 'viewed', 'Viewed', 'main_lang.php'),
( 'english', 'visit', 'Visit', 'main_lang.php'),
( 'english', 'visit_date', 'Visit Date', 'main_lang.php'),
( 'english', 'visit_time', 'Visit Time', 'main_lang.php'),
( 'english', 'verify', 'Verify', 'main_lang.php'),
( 'english', 'version', 'Version', 'main_lang.php'),
( 'english', 'visits', 'Visits', 'main_lang.php'),
( 'english', 'visit_type', 'Visit Type', 'main_lang.php'),
( 'english', 'verification_code', 'Verification Code', 'main_lang.php'),
( 'english', 'verify_email', 'Verify Email', 'main_lang.php'),
( 'english', 'voucher_no', 'Voucher No.', 'main_lang.php'),
( 'english', 'voucher_date', 'Voucher Date', 'main_lang.php'),
( 'english', 'view_larger_map', 'View Larger Map', 'main_lang.php'),
( 'english', 'view_prescription', 'View Prescription', 'main_lang.php'),
( 'english', 'value', 'Value', 'main_lang.php'),
( 'english', 'visit_report', 'Medical History Report', 'main_lang.php'),
( 'english', 'welcome', 'Welcome', 'main_lang.php'),
( 'english', 'waiting', 'Waiting', 'main_lang.php'),
( 'english', 'waiting_in', 'Waiting In', 'main_lang.php'),
( 'english', 'whole_day', 'Whole Day', 'main_lang.php'),
( 'english', 'website', 'Website', 'main_lang.php'),
( 'english', 'website_url', 'Website URL', 'main_lang.php'),
( 'english', 'website_text', 'Website Text', 'main_lang.php'),
( 'english', 'working_days', 'Working Days', 'main_lang.php'),
( 'english', 'working_key', 'Working Key', 'main_lang.php'),
( 'english', 'working', 'Working', 'main_lang.php'),
( 'english', 'non_working', 'Non Working', 'main_lang.php'),
( 'english', 'we_provide', 'We Provide', 'main_lang.php'),
( 'english', 'year', 'Year', 'main_lang.php'),
( 'english', 'sunday', 'Sunday', 'main_lang.php'),
( 'english', 'monday', 'Monday', 'main_lang.php'),
( 'english', 'tuesday', 'Tuesday', 'main_lang.php'),
( 'english', 'wednesday', 'Wednesday', 'main_lang.php'),
( 'english', 'friday', 'Friday', 'main_lang.php'),
( 'english', 'thursday', 'Thursday', 'main_lang.php'),
( 'english', 'saturday', 'Saturday', 'main_lang.php'),
( 'english', 'your_username', 'Your Username', 'main_lang.php'),
( 'english', 'your_password', 'Your Password', 'main_lang.php'),
( 'english', 'room_numbers_for', 'Room Numbers for', 'main_lang.php'),
( 'english', 'aplha_space', 'The %s field may only contain alpha characters & White spaces', 'main_lang.php'),
( 'english', 'irreversible_process', 'This is a irreversible process.It may cause loss of data. Be really really sure before restoring data.', 'main_lang.php'),
( 'english', 'first_or_last', 'Please enter First Name or Last Name', 'main_lang.php'),
( 'english', 'password_not_match', 'Old Password Not Matched', 'main_lang.php'),
( 'english', 'numbersof_days_between_two_appointments', 'Set it to basic numbers of days between two appointments. Set it to 0, to disable automatically setting next followup.', 'main_lang.php'),
( 'english', 'calculation_purpose_only', '*These fields are for calculation purpose only. Add actual payment amount in Payment Amount field.', 'main_lang.php'),
( 'english', 'clickto_toggle_display', '(Click to toggle display)', 'main_lang.php'),
( 'english', 'nobillsfound_for_selected_parameters', 'No Bills found for selected parameters', 'main_lang.php'),
( 'english', 'norecfound', 'No Record Found', 'main_lang.php'),
( 'english', 'areyousure', 'Are you sure you want to', 'main_lang.php'),
( 'english', 'areyousure_delete', 'Are you sure you want to delete?', 'main_lang.php'),
( 'english', 'areyousure_reject', 'Are you sure you want to reject?', 'main_lang.php'),
( 'english', 'areyousure_approve', 'Are you sure you want to approve?', 'main_lang.php'),
( 'english', 'please_select', 'Please Select', 'main_lang.php'),
( 'english', 'areyousure_cleardata', 'Are you sure you want to Clear Data? This Process cannot be undone!', 'main_lang.php'),
( 'english', 'areyousure_deactivate', 'Are you sure you want to deactivate?', 'main_lang.php'),
( 'english', 'jpg_format_not_allow', 'Jpg File format is allowed &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Image Size: 800 * 800', 'main_lang.php'),
( 'english', 'tempnote', '&nbsp;&nbsp;&nbsp;&nbsp;* Changing an existing template name will not rename the template. Instead it will create a copy of the template.', 'main_lang.php'),
( 'english', 'invalid_username', 'Invalid Username and/or Password', 'main_lang.php'),
( 'english', 'no_file_chosen', 'No File Chosen', 'main_lang.php'),
( 'english', 'no_treatment_added_add_treatment', 'No Treatments added. Add a treatment.', 'main_lang.php'),
( 'english', 'no_vaccine_added_add_vaccine', 'No Vaccines added. Add a Vaccine.', 'main_lang.php'),
( 'english', 'no_vaccine_schedule_added_add_vaccine', 'No Vaccines schedule added. Add a Vaccine Schedule.', 'main_lang.php'),
( 'english', 'temptext', 'The template directory must be set to writable to use the template editor.', 'main_lang.php'),
( 'english', 'upload_extention_instruction', 'If you have a extension in a .zip format, you may install it by uploading it here.', 'main_lang.php'),
( 'english', 'no_visits', 'No Visits for this patient', 'main_lang.php'),
( 'english', 'toggle_display', '(Click to toggle display)', 'main_lang.php'),
( 'english', 'initial_password_message', 'Initial password is same as username', 'main_lang.php'),
( 'english', 'thanks_to_amazing_works', 'Chikitsa would not have been possible without the amazing works listed below', 'main_lang.php'),
( 'english', 'no_disease', 'No Diseases added. Add a disease.', 'main_lang.php'),
( 'english', 'is_active_email', 'The {field} is not active. Kindly contact administrator', 'main_lang.php'),
( 'english', 'validate_date_or_day', 'Please enter Date or select Days.', 'main_lang.php'),
( 'english', 'non_working_day', 'This is a Non Working Day', 'main_lang.php'),
( 'english', 'max_post_allowed', '(You have reached the Maximum About Posts that can be added)', 'main_lang.php'),
( 'english', 'time_booked', 'This time is already booked with maximum patients!', 'main_lang.php'),
( 'english', 'image_for_compare', 'Please Select images for compare', 'main_lang.php'),
( 'english', 'doctor_not_available', 'Doctor is not available during this time', 'main_lang.php'),
( 'english', 'error_saving_image', 'Some Error occured while trying to save Image.', 'main_lang.php'),
( 'english', 'select_two', 'Please Select only Two', 'main_lang.php'),
( 'english', 'save_language_instructions', '(Just change the text and move to next to save)', 'main_lang.php'),
( 'english', 'validate_code', 'Verification Code is not valid', 'main_lang.php'),
( 'english', 'no_email_registered', 'There is no user registered with that Username or Email.', 'main_lang.php'),
( 'english', 'reset_password_instructions', 'Please enter your username or email address. You will receive a link to create a new password via email.', 'main_lang.php'),
( 'english', 'check_confirmation_link', 'Check your email for the Confirmation Link.', 'main_lang.php'),
( 'english', 'paypal_cancel_salutation', 'Dear Member', 'main_lang.php'),
( 'english', 'appointment_payment_success', 'Your payment was successful, thank you for booking appointment.', 'main_lang.php'),
( 'english', 'paypal_cancel_message', 'We are sorry! Your last transaction was cancelled.', 'main_lang.php'),
( 'english', 'file_missing', 'Folder Missing', 'main_lang.php'),
( 'english', 'sms_username_instruction', 'Enter the username provided by the SMS API Provider', 'main_lang.php'),
( 'english', 'sms_password_instruction', 'Enter the password provided by the SMS API Provider', 'main_lang.php'),
( 'english', 'sms_senderid_instruction', 'Enter the sender ID provided by the SMS API Provider', 'main_lang.php'),
( 'english', 'sms_countrycode_instruction', 'Keep it blank to not include Country Code in Mobile Number', 'main_lang.php'),
( 'english', 'updating_to_latest', 'Updating Chikitsa to Latest Version.<br/> This process may take several minutes.<br/>', 'main_lang.php'),
( 'english', 'donot_close_browser', '<strong>Please do not close the browser till the process completes.</strong><br/>', 'main_lang.php'),
( 'english', 'sms_url_instruction', 'Enter the URL provided by the SMS API Provider', 'main_lang.php'),
( 'english', 'download_chikitsa', 'Downloading Latest Chikitsa zip...<br/>', 'main_lang.php'),
( 'english', 'unzip_file', 'Unzipping the zip file. <br/>', 'main_lang.php'),
( 'english', 'no_services', 'No Services added. Add a Service.', 'main_lang.php'),
( 'english', 'extension_requires', 'This extension requires %1 %2', 'main_lang.php'),
( 'english', 'compatible_version', 'Compatible with this version of %1', 'main_lang.php'),
( 'english', 'please_enter_first_name', 'Please Enter First Name', 'main_lang.php'),
( 'english', 'please_enter_last_name', 'Please Enter Last Name', 'main_lang.php'),
( 'english', 'please_enter_mobile_number', 'Please Enter Mobile Number', 'main_lang.php'),
( 'english', 'please_enter_language_name', 'Please Enter Language Name', 'main_lang.php'),
( 'english', 'australian_currency', 'Australian Dollar (AUD)', 'main_lang.php'),
( 'english', 'brazilian_currency', 'Brazilian Real (BRL)', 'main_lang.php'),
( 'english', 'canadian_currency', 'Canadian Dollar (CAD)', 'main_lang.php'),
( 'english', 'czech_currency', 'Czech Koruna (CZK)', 'main_lang.php'),
( 'english', 'danish_currency', 'Danish Krone (DKK)', 'main_lang.php'),
( 'english', 'israeli_currency', 'Israeli New Sheqel (ILS)', 'main_lang.php'),
( 'english', 'euro_currency', 'Euro (EUR)', 'main_lang.php'),
( 'english', 'hungarian_currency', 'Hungarian Forint (HUF)', 'main_lang.php'),
( 'english', 'hong_kong_currency', 'Hong Kong Dollar (HKD)', 'main_lang.php'),
( 'english', 'japanese_currency', 'Japanese Yen (JPY)', 'main_lang.php'),
( 'english', 'malaysian_currency', 'Malaysian Ringgit (MYR)', 'main_lang.php'),
( 'english', 'mexican_currency', 'Mexican Peso (MXN)', 'main_lang.php'),
( 'english', 'norwegian_currency', 'Norwegian Krone (NOK)', 'main_lang.php'),
( 'english', 'new_zealand_currency', 'New Zealand Dollar (NZD)', 'main_lang.php'),
( 'english', 'philippine_currency', 'Philippine Peso (PHP)', 'main_lang.php'),
( 'english', 'polish_currency', 'Polish Zloty (PLN)', 'main_lang.php'),
( 'english', 'pound_currency', 'Pound Sterling (GBP)', 'main_lang.php'),
( 'english', 'singapore_currency', 'Singapore Dollar (SGD)', 'main_lang.php'),
( 'english', 'swiss_currency', 'Swiss Franc (CHF)', 'main_lang.php'),
( 'english', 'swedish_currency', 'Swedish Krona (SEK)', 'main_lang.php'),
( 'english', 'taiwan_currency', 'Taiwan New Dollar (TWD)', 'main_lang.php'),
( 'english', 'uae_currency', 'UAE Dirham (AED)', 'main_lang.php'),
( 'english', 'us_currency', 'U.S. Dollar (USD)', 'main_lang.php'),
( 'english', 'thai_currency', 'Thai Baht (THB)', 'main_lang.php'),
( 'english', 'bangladesh_currency', 'Bangladesh Taka (BDT)', 'main_lang.php'),
( 'english', 'bahraini_currency', 'Bahraini Dinar (BHD)', 'main_lang.php'),
( 'english', 'chinese_currency', 'Chinese Yuan Renminbi (CNY)', 'main_lang.php'),
( 'english', 'indian_currency', 'Indian Rupee (INR)', 'main_lang.php'),
( 'english', 'kenyan_currency', 'Kenyan Shilling (KES)', 'main_lang.php'),
( 'english', 'kuwaiti_currency', 'Kuwaiti Dinar (KWD)', 'main_lang.php'),
( 'english', 'mauritius_currency', 'Mauritius Rupee (MUR)', 'main_lang.php'),
( 'english', 'sri_lankan_currency', 'Sri Lankan Rupee (LKR)', 'main_lang.php'),
( 'english', 'omani_currency', 'Omani Rial (OMR)', 'main_lang.php'),
( 'english', 'qatari_currency', 'Qatari Riyal (QAR)', 'main_lang.php'),
( 'english', 'nepalese_currency', 'Nepalese Rupee (NPR)', 'main_lang.php'),
( 'english', 'saudi_currency', 'Saudi Riyal (SAR)', 'main_lang.php'),
( 'english', 'grace_hours', 'Grace Hours', 'main_lang.php'),
( 'english', 'south_african_currency', 'South African Rand (ZAR)', 'main_lang.php'),
( 'english', 'base_charge', 'Base Charges for minimum hours', 'main_lang.php'),
( 'english', 'minimum_hours_for_admission', 'Minimum hours for admission', 'main_lang.php'),
( 'english', 'enable_patient_account', 'Enable Patient Account', 'main_lang.php'),
( 'english', 'patient_account_msg', '(You will be able to take more payment than invoice amount. The additional payment will be maintained in Patient Account. This amount can be used to adjust the bill next time)', 'main_lang.php'),
( 'english', 'favicon', 'favicon', 'main_lang.php'),
( 'english', 'preferred_size_icon', 'Favicon Preferred size 16X16', 'main_lang.php'),
( 'english', 'all_items', 'All Items', 'main_lang.php'),
( 'english', 'all_purchase', 'All Purchas', 'main_lang.php'),
( 'english', 'stock_reports', 'Stock Report', 'main_lang.php'),
( 'english', 'content_section', 'Content Section', 'main_lang.php');