INSERT INTO %dbprefix%language_master (language_name,is_default,is_loaded) VALUES ('gujarati',0,1);
INSERT INTO %dbprefix%language_data (l_name, l_index, l_value, file_name) VALUES
( 'gujarati', 'cal_su', 'રવિ', 'calendar_lang.php'),
( 'gujarati', 'cal_tu', 'મંગળ', 'calendar_lang.php'),
( 'gujarati', 'cal_mo', 'સોમ', 'calendar_lang.php'),
( 'gujarati', 'cal_we', 'બુધ', 'calendar_lang.php'),
( 'gujarati', 'cal_th', 'ગુરુ', 'calendar_lang.php'),
( 'gujarati', 'cal_fr', 'શુક્ર', 'calendar_lang.php'),
( 'gujarati', 'cal_sa', 'શનિ', 'calendar_lang.php'),
( 'gujarati', 'cal_sun', 'રવિ', 'calendar_lang.php'),
( 'gujarati', 'cal_wed', 'બુધ', 'calendar_lang.php'),
( 'gujarati', 'cal_mon', 'સોમ', 'calendar_lang.php'),
( 'gujarati', 'cal_tue', 'મંગળ', 'calendar_lang.php'),
( 'gujarati', 'cal_thu', 'ગુરુ', 'calendar_lang.php'),
( 'gujarati', 'cal_fri', 'શુક્ર', 'calendar_lang.php'),
( 'gujarati', 'cal_sat', 'શનિ', 'calendar_lang.php'),
( 'gujarati', 'cal_sunday', 'રવિવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_monday', 'સોમવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_tuesday', 'મંગળવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_wednesday', 'બુધવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_thursday', 'ગુરુવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_friday', 'શુક્રવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_saturday', 'શનિવાર', 'calendar_lang.php'),
( 'gujarati', 'cal_feb', 'ફેબ્રુ', 'calendar_lang.php'),
( 'gujarati', 'cal_jan', 'જાન્યુ', 'calendar_lang.php'),
( 'gujarati', 'cal_mar', 'માર્ચ', 'calendar_lang.php'),
( 'gujarati', 'cal_apr', 'એપ્રિ', 'calendar_lang.php'),
( 'gujarati', 'cal_jun', 'જૂન', 'calendar_lang.php'),
( 'gujarati', 'cal_may', 'મે', 'calendar_lang.php'),
( 'gujarati', 'cal_jul', 'જુલાઈ', 'calendar_lang.php'),
( 'gujarati', 'cal_aug', 'ઑગ', 'calendar_lang.php'),
( 'gujarati', 'cal_sep', 'સપ્ટે', 'calendar_lang.php'),
( 'gujarati', 'cal_oct', 'ઓક્ટો', 'calendar_lang.php'),
( 'gujarati', 'cal_nov', 'નવે', 'calendar_lang.php'),
( 'gujarati', 'cal_dec', 'ડિસે', 'calendar_lang.php'),
( 'gujarati', 'cal_january', 'જાન્યુઆરી', 'calendar_lang.php'),
( 'gujarati', 'cal_february', 'ફેબ્રુવારી', 'calendar_lang.php'),
( 'gujarati', 'cal_march', 'માર્ચ', 'calendar_lang.php'),
( 'gujarati', 'cal_mayl', 'મે', 'calendar_lang.php'),
( 'gujarati', 'cal_april', 'એપ્રિલ', 'calendar_lang.php'),
( 'gujarati', 'cal_june', 'જૂન', 'calendar_lang.php'),
( 'gujarati', 'cal_july', 'જુલાઈ', 'calendar_lang.php'),
( 'gujarati', 'cal_august', 'ઑગસ્ટ', 'calendar_lang.php'),
( 'gujarati', 'cal_september', 'સપ્ટેમ્બર', 'calendar_lang.php'),
( 'gujarati', 'cal_october', 'ઓક્ટોબર', 'calendar_lang.php'),
( 'gujarati', 'cal_november', 'નવેમ્બર', 'calendar_lang.php'),
( 'gujarati', 'cal_december', 'ડિસેમ્બર', 'calendar_lang.php'),
( 'gujarati', 'date_year', 'વર્ષ', 'date_lang.php'),
( 'gujarati', 'date_months', 'મહિના', 'date_lang.php'),
( 'gujarati', 'date_week', 'સપ્તાહ', 'date_lang.php'),
( 'gujarati', 'date_years', 'વર્ષ', 'date_lang.php'),
( 'gujarati', 'date_weeks', 'અઠવાડિયા', 'date_lang.php'),
( 'gujarati', 'date_month', 'મહિનો', 'date_lang.php'),
( 'gujarati', 'date_day', 'દિવસ', 'date_lang.php'),
( 'gujarati', 'date_hour', 'કલાક', 'date_lang.php'),
( 'gujarati', 'date_days', 'દિવસો', 'date_lang.php'),
( 'gujarati', 'date_minute', 'મિનિટ', 'date_lang.php'),
( 'gujarati', 'date_minutes', 'મિનિટો', 'date_lang.php'),
( 'gujarati', 'date_hours', 'કલાકો', 'date_lang.php'),
( 'gujarati', 'date_second', 'સેકંડ', 'date_lang.php'),
( 'gujarati', 'date_seconds', 'સેકંડ', 'date_lang.php'),
( 'gujarati', 'UM12', '(UTC -12:00) Baker/Howland Island', 'date_lang.php'),
( 'gujarati', 'UM11', '(UTC -11:00) Niue', 'date_lang.php'),
( 'gujarati', 'UM95', '(UTC -9:30) Marquesas Islands', 'date_lang.php'),
( 'gujarati', 'UM10', '(UTC -10:00) Hawaii-Aleutian Standard Time, Cook Islands, Tahiti', 'date_lang.php'),
( 'gujarati', 'UM9', '(UTC -9:00) Alaska Standard Time, Gambier Islands', 'date_lang.php'),
( 'gujarati', 'UM8', '(UTC -8:00) Pacific Standard Time, Clipperton Island', 'date_lang.php'),
( 'gujarati', 'UM7', '(UTC -7:00) Mountain Standard Time', 'date_lang.php'),
( 'gujarati', 'UM6', '(UTC -6:00) Central Standard Time', 'date_lang.php'),
( 'gujarati', 'UM45', '(UTC -4:30) Venezuelan Standard Time', 'date_lang.php'),
( 'gujarati', 'UM4', '(UTC -4:00) Atlantic Standard Time, Eastern Caribbean Standard Time', 'date_lang.php'),
( 'gujarati', 'UM5', '(UTC -5:00) Eastern Standard Time, Western Caribbean Standard Time', 'date_lang.php'),
( 'gujarati', 'UM35', '(UTC -3:30) Newfoundland Standard Time', 'date_lang.php'),
( 'gujarati', 'UM3', '(UTC -3:00) Argentina, Brazil, French Guiana, Uruguay', 'date_lang.php'),
( 'gujarati', 'UTC', '(UTC) Greenwich Mean Time, Western European Time', 'date_lang.php'),
( 'gujarati', 'UM1', '(UTC -1:00) Azores, Cape Verde Islands', 'date_lang.php'),
( 'gujarati', 'UM2', '(UTC -2:00) South Georgia/South Sandwich Islands', 'date_lang.php'),
( 'gujarati', 'UP1', '(UTC +1:00) Central European Time, West Africa Time', 'date_lang.php'),
( 'gujarati', 'UP2', '(UTC +2:00) Central Africa Time, Eastern European Time, Kaliningrad Time', 'date_lang.php'),
( 'gujarati', 'UP3', '(UTC +3:00) Moscow Time, East Africa Time, Arabia Standard Time', 'date_lang.php'),
( 'gujarati', 'UP4', '(UTC +4:00) Azerbaijan Standard Time, Samara Time', 'date_lang.php'),
( 'gujarati', 'UP45', '(UTC +4:30) Afghanistan', 'date_lang.php'),
( 'gujarati', 'UP35', '(UTC +3:30) Iran Standard Time', 'date_lang.php'),
( 'gujarati', 'UP5', '(UTC +5:00) Pakistan Standard Time, Yekaterinburg Time', 'date_lang.php'),
( 'gujarati', 'UP55', '(UTC +5:30) Indian Standard Time, Sri Lanka Time', 'date_lang.php'),
( 'gujarati', 'UP575', '(UTC +5:45) Nepal Time', 'date_lang.php'),
( 'gujarati', 'UP6', '(UTC +6:00) Bangladesh Standard Time, Bhutan Time, Omsk Time', 'date_lang.php'),
( 'gujarati', 'UP65', '(UTC +6:30) Cocos Islands, Myanmar', 'date_lang.php'),
( 'gujarati', 'UP7', '(UTC +7:00) Krasnoyarsk Time, Cambodia, Laos, Thailand, Vietnam', 'date_lang.php'),
( 'gujarati', 'UP8', '(UTC +8:00) Australian Western Standard Time, Beijing Time, Irkutsk Time', 'date_lang.php'),
( 'gujarati', 'UP875', '(UTC +8:45) Australian Central Western Standard Time', 'date_lang.php'),
( 'gujarati', 'UP9', '(UTC +9:00) Japan Standard Time, Korea Standard Time, Yakutsk Time', 'date_lang.php'),
( 'gujarati', 'UP95', '(UTC +9:30) Australian Central Standard Time', 'date_lang.php'),
( 'gujarati', 'UP10', '(UTC +10:00) Australian Eastern Standard Time, Vladivostok Time', 'date_lang.php'),
( 'gujarati', 'UP105', '(UTC +10:30) Lord Howe Island', 'date_lang.php'),
( 'gujarati', 'UP11', '(UTC +11:00) Srednekolymsk Time, Solomon Islands, Vanuatu', 'date_lang.php'),
( 'gujarati', 'UP115', '(UTC +11:30) Norfolk Island', 'date_lang.php'),
( 'gujarati', 'UP12', '(UTC +12:00) Fiji, Gilbert Islands, Kamchatka Time, New Zealand Standard Time', 'date_lang.php'),
( 'gujarati', 'UP1275', '(UTC +12:45) Chatham Islands Standard Time', 'date_lang.php'),
( 'gujarati', 'UP13', '(UTC +13:00) Samoa Time Zone, Phoenix Islands Time, Tonga', 'date_lang.php'),
( 'gujarati', 'UP14', '(UTC +14:00) Line Islands', 'date_lang.php'),
( 'gujarati', 'db_invalid_connection_str', 'Unable to determine the database settings based on the connection string you submitted.', 'db_lang.php'),
( 'gujarati', 'db_unable_to_connect', 'Unable to connect to your database server using the provided settings.', 'db_lang.php'),
( 'gujarati', 'db_unable_to_select', 'Unable to select the specified database: %s', 'db_lang.php'),
( 'gujarati', 'db_must_set_table', 'You must set the database table to be used with your query.', 'db_lang.php'),
( 'gujarati', 'db_invalid_query', 'The query you submitted is not valid.', 'db_lang.php'),
( 'gujarati', 'db_unable_to_create', 'Unable to create the specified database: %s', 'db_lang.php'),
( 'gujarati', 'db_must_use_set', 'You must use the "set" method to update an entry.', 'db_lang.php'),
( 'gujarati', 'db_must_use_index', 'You must specify an index to match on for batch updates.', 'db_lang.php'),
( 'gujarati', 'db_batch_missing_index', 'One or more rows submitted for batch updating is missing the specified index.', 'db_lang.php'),
( 'gujarati', 'db_field_param_missing', 'To fetch fields requires the name of the table as a parameter.', 'db_lang.php'),
( 'gujarati', 'db_del_must_use_where', 'Deletes are not allowed unless they contain a "where" or "like" clause.', 'db_lang.php'),
( 'gujarati', 'db_transaction_failure', 'Transaction failure: Rollback performed.', 'db_lang.php'),
( 'gujarati', 'db_unsupported_function', 'This feature is not available for the database you are using.', 'db_lang.php'),
( 'gujarati', 'db_must_use_where', 'Updates are not allowed unless they contain a "where" clause.', 'db_lang.php'),
( 'gujarati', 'db_unable_to_drop', 'Unable to drop the specified database.', 'db_lang.php'),
( 'gujarati', 'db_unsupported_feature', 'Unsupported feature of the database platform you are using.', 'db_lang.php'),
( 'gujarati', 'db_unsupported_compression', 'The file compression format you chose is not supported by your server.', 'db_lang.php'),
( 'gujarati', 'db_filepath_error', 'Unable to write data to the file path you have submitted.', 'db_lang.php'),
( 'gujarati', 'db_invalid_cache_path', 'The cache path you submitted is not valid or writable.', 'db_lang.php'),
( 'gujarati', 'db_table_name_required', 'A table name is required for that operation.', 'db_lang.php'),
( 'gujarati', 'db_column_name_required', 'A column name is required for that operation.', 'db_lang.php'),
( 'gujarati', 'db_column_definition_required', 'A column definition is required for that operation.', 'db_lang.php'),
( 'gujarati', 'db_unable_to_set_charset', 'Unable to set client connection character set: %s', 'db_lang.php'),
( 'gujarati', 'db_error_heading', 'A Database Error Occurred', 'db_lang.php'),
( 'gujarati', 'email_must_be_array', 'The email validation method must be passed an array.', 'email_lang.php'),
( 'gujarati', 'email_invalid_address', 'Invalid email address: %s', 'email_lang.php'),
( 'gujarati', 'email_attachment_missing', 'Unable to locate the following email attachment: %s', 'email_lang.php'),
( 'gujarati', 'email_no_from', 'Cannot send mail with no "From" header.', 'email_lang.php'),
( 'gujarati', 'email_attachment_unreadable', 'Unable to open this attachment: %s', 'email_lang.php'),
( 'gujarati', 'email_no_recipients', 'You must include recipients: To, Cc, or Bcc', 'email_lang.php'),
( 'gujarati', 'email_send_failure_phpmail', 'Unable to send email using PHP mail(). Your server might not be configured to send mail using this method.', 'email_lang.php'),
( 'gujarati', 'email_send_failure_sendmail', 'Unable to send email using PHP Sendmail. Your server might not be configured to send mail using this method.', 'email_lang.php'),
( 'gujarati', 'email_send_failure_smtp', 'Unable to send email using PHP SMTP. Your server might not be configured to send mail using this method.', 'email_lang.php'),
( 'gujarati', 'email_no_hostname', 'You did not specify a SMTP hostname.', 'email_lang.php'),
( 'gujarati', 'email_no_socket', 'Unable to open a socket to Sendmail. Please check settings.', 'email_lang.php'),
( 'gujarati', 'email_sent', 'Your message has been successfully sent using the following protocol: %s', 'email_lang.php'),
( 'gujarati', 'email_smtp_error', 'The following SMTP error was encountered: %s', 'email_lang.php'),
( 'gujarati', 'email_no_smtp_unpw', 'Error: You must assign a SMTP username and password.', 'email_lang.php'),
( 'gujarati', 'email_failed_smtp_login', 'Failed to send AUTH LOGIN command. Error: %s', 'email_lang.php'),
( 'gujarati', 'email_smtp_auth_un', 'Failed to authenticate username. Error: %s', 'email_lang.php'),
( 'gujarati', 'email_smtp_auth_pw', 'Failed to authenticate password. Error: %s', 'email_lang.php'),
( 'gujarati', 'email_smtp_data_failure', 'Unable to send data: %s', 'email_lang.php'),
( 'gujarati', 'email_exit_status', 'Exit status code: %s', 'email_lang.php'),
( 'gujarati', 'form_validation_required', '{field} ફિલ્ડ જરૂરી છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_isset', '{field} ફિલ્ડ વેલ્યૂ હોવી જ જોઈએ .', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_valid_email', '{field} ફીલ્ડમાં એક માન્ય ઇમેઇલ સરનામું હોવું આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_valid_url', '{field} ફીલ્ડમાં એક માન્ય URL હોવું આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_valid_emails', '{field} ફીલ્ડમાં બધા માન્ય ઇમેઇલ સરનામાંઓ હોવા આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_valid_ip', '{field} ફીલ્ડમાં એક માન્ય IP હોવું આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_max_length', '{field} ફીલ્ડમાં લંબાઈ {param} અક્ષરોથી વધી શકતો નથી.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_min_length', '{field} ફીલ્ડમાં ઓછામાં ઓછા {param} અક્ષર લંબાઈમાં હોવો આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_exact_length', '{field} ફીલ્ડમાં બરાબર {param} લંબાઈના અક્ષરો હોવા જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_alpha', '{field} ફીલ્ડમાં ફક્ત મૂળાક્ષર અક્ષરો જ હોઈ શકે છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_alpha_numeric_spaces', '{field} ફીલ્ડમાં ફક્ત આંકડાકીય અક્ષરો અને જગ્યા હોઈ શકે છે', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_alpha_numeric', '{field} ફીલ્ડમાં ફક્ત આંકડાકીય અક્ષરો હોઈ શકે છે', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_numeric', '{field} ફીલ્ડમાં ફક્ત સંખ્યાઓ જ હોવી જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_alpha_dash', '{field} ફીલ્ડમાં ફક્ત આંકડાકીય અક્ષરો, અંડરસ્કોર્સ અને ડૅશ હોઈ શકે છે', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_is_numeric', '{field} ફીલ્ડમાં માત્ર આંકડાકીય અક્ષરો જ હોવા જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_integer', '{field} ફીલ્ડમાં પૂર્ણાંક હોવો આવશ્યક છે', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_regex_match', '{field} ફીલ્ડ યોગ્ય ફોર્મેટમાં નથી.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_matches', '{field} ફીલ્ડ {param} ફીલ્ડથી મેળ ખાતો નથી', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_differs', '{field} ફીલ્ડ {param} ફીલ્ડથી અલગ હોવું જોઈએ', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_is_unique', '{field} ફીલ્ડમાં એક અનન્ય મૂલ્ય હોવું આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_is_natural', '{field} ફીલ્ડમાં માત્ર અંકો જ હોવા જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_is_natural_no_zero', '{field} ફીલ્ડમાં માત્ર અંકો હોવો જોઈએ અને શૂન્ય કરતા વધારે હોવા જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_less_than', '{field} ફીલ્ડમાં {param} કરતાં ઓછી સંખ્યા ધરાવતું હોવું જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_decimal', '{field} ફીલ્ડમાં દશાંશ નંબર હોવો આવશ્યક છે.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_less_than_equal_to', '{field} ફીલ્ડમાં {param} કરતાં ઓછા અથવા બરાબર સંખ્યા હોવી જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_greater_than', '{field} ફીલ્ડમાં {param} કરતાં મોટી સંખ્યા હોવી જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_greater_than_equal_to', '{field} ફીલ્ડમાં {param} થી મોટી અથવા તેનાથી વધુ સંખ્યા હોવી જોઈએ.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_error_message_not_set', 'તમારા ફીલ્ડના નામથી સંબંધિત ભૂલ સંદેશાને ઍક્સેસ કરવામાં અસમર્થ{field}.', 'form_validation_lang.php'),
( 'gujarati', 'form_validation_in_list', '{field} ફીલ્ડના એક હોવો જોઈએ: {param}', 'form_validation_lang.php'),
( 'gujarati', 'ftp_no_connection', 'Unable to locate a valid connection ID. Please make sure you are connected before performing any file routines.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_connect', 'Unable to connect to your FTP server using the supplied hostname.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_mkdir', 'Unable to create the directory you have specified.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_changedir', 'Unable to change directories.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_login', 'Unable to login to your FTP server. Please check your username and password.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_chmod', 'Unable to set file permissions. Please check your path.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_upload', 'Unable to upload the specified file. Please check your path.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_download', 'Unable to download the specified file. Please check your path.', 'ftp_lang.php'),
( 'gujarati', 'ftp_no_source_file', 'Unable to locate the source file. Please check your path.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_rename', 'Unable to rename the file.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_move', 'Unable to move the file. Please make sure the destination directory exists.', 'ftp_lang.php'),
( 'gujarati', 'ftp_unable_to_delete', 'Unable to delete the file.', 'ftp_lang.php'),
( 'gujarati', 'imglib_gd_required', 'The GD image library is required for this feature.', 'imglib_lang.php'),
( 'gujarati', 'imglib_source_image_required', 'You must specify a source image in your preferences.', 'imglib_lang.php'),
( 'gujarati', 'imglib_gd_required_for_props', 'Your server must support the GD image library in order to determine the image properties.', 'imglib_lang.php'),
( 'gujarati', 'imglib_jpg_not_supported', 'JPG images are not supported.', 'imglib_lang.php'),
( 'gujarati', 'imglib_gif_not_supported', 'GIF images are often not supported due to licensing restrictions. You may have to use JPG or PNG images instead.', 'imglib_lang.php'),
( 'gujarati', 'imglib_unsupported_imagecreate', 'Your server does not support the GD function required to process this type of image.', 'imglib_lang.php'),
( 'gujarati', 'imglib_png_not_supported', 'PNG images are not supported.', 'imglib_lang.php'),
( 'gujarati', 'imglib_jpg_or_png_required', 'The image resize protocol specified in your preferences only works with JPEG or PNG image types.', 'imglib_lang.php'),
( 'gujarati', 'imglib_copy_error', 'An error was encountered while attempting to replace the file. Please make sure your file directory is writable.', 'imglib_lang.php'),
( 'gujarati', 'imglib_libpath_invalid', 'The path to your image library is not correct. Please set the correct path in your image preferences.', 'imglib_lang.php'),
( 'gujarati', 'imglib_rotate_unsupported', 'Image rotation does not appear to be supported by your server.', 'imglib_lang.php'),
( 'gujarati', 'imglib_image_process_failed', 'Image processing failed. Please verify that your server supports the chosen protocol and that the path to your image library is correct.', 'imglib_lang.php'),
( 'gujarati', 'imglib_rotation_angle_required', 'An angle of rotation is required to rotate the image.', 'imglib_lang.php'),
( 'gujarati', 'imglib_invalid_path', 'The path to the image is not correct.', 'imglib_lang.php'),
( 'gujarati', 'imglib_copy_failed', 'The image copy routine failed.', 'imglib_lang.php'),
( 'gujarati', 'imglib_missing_font', 'Unable to find a font to use.', 'imglib_lang.php'),
( 'gujarati', 'imglib_save_failed', 'Unable to save the image. Please make sure the image and file directory are writable.', 'imglib_lang.php'),
( 'gujarati', 'app_name', 'Chikitsa', 'main_lang.php'),
( 'gujarati', 'app_tagline', 'ક્લિનિક મેનેજમેન્ટ સિસ્ટમ', 'main_lang.php'),
( 'gujarati', 'main_title', 'ચિકિત્સા - ક્લિનિક મેનેજમેન્ટ સિસ્ટમ', 'main_lang.php'),
( 'gujarati', 'cmp_name', 'સંસ્કૃતિ ટેક્નોલોજીસ', 'main_lang.php'),
( 'gujarati', 'cmp_version', 'ચિકિત્સા આવૃત્તિ', 'main_lang.php'),
( 'gujarati', 'about_chikitsa', 'ચિકિત્સા વિશે', 'main_lang.php'),
( 'gujarati', 'sign_in', 'સાઇન ઇન કરો', 'main_lang.php'),
( 'gujarati', '5min', '5 મીન', 'main_lang.php'),
( 'gujarati', '15min', '15 મિનિટ', 'main_lang.php'),
( 'gujarati', '7min', '7 મીન', 'main_lang.php'),
( 'gujarati', '30min', '30 મીન', 'main_lang.php'),
( 'gujarati', 'second_section', 'બીજો વિભાગ', 'main_lang.php'),
( 'gujarati', '1hr', '1 કલાક', 'main_lang.php'),
( 'gujarati', 'main_section', 'મુખ્ય વિભાગ', 'main_lang.php'),
( 'gujarati', 'third_section', 'ત્રીજો વિભાગ', 'main_lang.php'),
( 'gujarati', 'background_color', 'પૃષ્ઠભૂમિ રંગ', 'main_lang.php'),
( 'gujarati', 'title_color', 'શીર્ષક રંગ', 'main_lang.php'),
( 'gujarati', 'text_color', 'ટેક્સ્ટ રંગ', 'main_lang.php'),
( 'gujarati', 'about_settings', 'સેટિંગ્સ વિશે', 'main_lang.php'),
( 'gujarati', 'about', 'વિશે', 'main_lang.php'),
( 'gujarati', 'about_page_settings', 'વિશે પેજમાં સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'access_on_menu', 'મેનુ પર ઍક્સેસ', 'main_lang.php'),
( 'gujarati', 'access_code', 'ઍક્સેસ કોડ', 'main_lang.php'),
( 'gujarati', 'account_group_master', 'એકાઉન્ટ ગ્રુપ માસ્ટર', 'main_lang.php'),
( 'gujarati', 'account_details_meta', 'એકાઉન્ટ વિગતો મેટા', 'main_lang.php'),
( 'gujarati', 'account_group_name', 'એકાઉન્ટ ગ્રુપનું નામ', 'main_lang.php'),
( 'gujarati', 'account_group', 'એકાઉન્ટ ગ્રુપ', 'main_lang.php'),
( 'gujarati', 'account_group_order', 'એકાઉન્ટ ગ્રુપ ઓર્ડર', 'main_lang.php'),
( 'gujarati', 'account_groups', 'એકાઉન્ટ જૂથો', 'main_lang.php'),
( 'gujarati', 'account', 'એકાઉન્ટ', 'main_lang.php'),
( 'gujarati', 'action', 'ક્રિયા', 'main_lang.php'),
( 'gujarati', 'accounts', 'એકાઉન્ટ્સ', 'main_lang.php'),
( 'gujarati', 'activate', 'સક્રિય', 'main_lang.php'),
( 'gujarati', 'actions', 'ક્રિયાઓ', 'main_lang.php'),
( 'gujarati', 'amount', 'રકમ', 'main_lang.php'),
( 'gujarati', 'available_quantity', 'ઉપલબ્ધ જથ્થો', 'main_lang.php'),
( 'gujarati', 'add_condition', 'શરત ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add', 'ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_another_medicine', 'અન્ય દવા ઉમેરો', 'main_lang.php'),
( 'gujarati', 'additional_css', 'વધારાની સીએસએસ', 'main_lang.php'),
( 'gujarati', 'add_appointment', 'નિમણૂંક ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_alerts', 'ચેતવણીઓ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_slider', 'સ્લાઇડર ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_about_page_post', 'પૃષ્ઠ પોસ્ટ વિશે ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_footer_section', 'ફૂટર વિભાગ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_footer_credit', 'ફૂટર ક્રેડિટ વિભાગ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_top_section', 'ટોચના વિભાગ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_image', 'નવી છબી ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_category', 'કેટેગરી ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_detail', 'વિગતવાર ઉમેરવા માટે પરવાનગી આપે છે', 'main_lang.php'),
( 'gujarati', 'add_department', 'વિભાગ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_from_users', 'વપરાશકર્તાઓ પ્રતિ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_more_contact_number', 'વધુ સંપર્ક નંબર્સ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_new_user', 'નવા વપરાશકર્તાને ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_news', 'સમાચાર ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_test', 'ટેસ્ટ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_as_medicine', 'દવા તરીકે ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_inquiry', 'ઇન્ક્વાયરી ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_section', 'વિભાગ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_service', 'સેવા ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_treatment', 'સારવાર ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_reference_by', 'દ્વારા સંદર્ભ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_refund', 'રીફંડ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_user', 'વપરાશકર્તાને ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_language', 'ભાષા ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_bottom_section', 'બોટમ વિભાગ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_patient', 'પેશન્ટ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_fee', 'ફી ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_extension', 'એક્સ્ટેન્શન્સ ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_payment', 'ચુકવણી ઉમેરો', 'main_lang.php'),
( 'gujarati', 'add_license_key', 'લાઇસેંસ કી ઉમેરો', 'main_lang.php'),
( 'gujarati', 'added_date', 'ઉમેરાયેલ તારીખ', 'main_lang.php'),
( 'gujarati', 'address', 'સરનામું', 'main_lang.php'),
( 'gujarati', 'addresstype', 'સરનામું પ્રકાર', 'main_lang.php'),
( 'gujarati', 'address_line_1', 'સરનામાં લાઇન 1', 'main_lang.php'),
( 'gujarati', 'address_line_2', 'સરનામાં લાઇન 2', 'main_lang.php'),
( 'gujarati', 'administrator', 'સંચાલક', 'main_lang.php'),
( 'gujarati', 'administration', 'વહીવટ', 'main_lang.php'),
( 'gujarati', 'appointment_calendar', 'નિમણૂંક કૅલેન્ડર', 'main_lang.php'),
( 'gujarati', 'adult_teeth', 'પુખ્ત દાંત', 'main_lang.php'),
( 'gujarati', 'admin_log_in', 'સંચાલક લૉગિન', 'main_lang.php'),
( 'gujarati', 'amount_paid', 'ચુકવેલ રકમ', 'main_lang.php'),
( 'gujarati', 'after', 'પછી', 'main_lang.php'),
( 'gujarati', 'afternoon_time', 'બપોર પછીનો સમય', 'main_lang.php'),
( 'gujarati', 'age', 'ઉંમર', 'main_lang.php'),
( 'gujarati', 'afternoon', 'A', 'main_lang.php'),
( 'gujarati', 'alerts', 'ચેતવણીઓ', 'main_lang.php'),
( 'gujarati', 'alert_settings', 'ચેતવણી સેટિંગ', 'main_lang.php'),
( 'gujarati', 'alert_sms_log', 'ચેતવણી એસએમએસ લોગ', 'main_lang.php'),
( 'gujarati', 'alert_email_log', 'ચેતવણી ઇમેઇલ લૉગ', 'main_lang.php'),
( 'gujarati', 'alert_time', 'ચેતવણી સમય', 'main_lang.php'),
( 'gujarati', 'alert_name', 'ચેતવણી નામ', 'main_lang.php'),
( 'gujarati', 'allot', 'ફાળવવું', 'main_lang.php'),
( 'gujarati', 'all', 'બધા', 'main_lang.php'),
( 'gujarati', 'allow_menu', 'મેનુ માટે પરવાનગી આપે છે', 'main_lang.php'),
( 'gujarati', 'allow_center', 'કેન્દ્રને મંજૂરી આપો', 'main_lang.php'),
( 'gujarati', 'allocate', 'ફાળવો', 'main_lang.php'),
( 'gujarati', 'all_sell', 'બધા વેચાણ', 'main_lang.php'),
( 'gujarati', 'allow_repeat', 'પુનરાવર્તનની મંજૂરી આપો', 'main_lang.php'),
( 'gujarati', 'stock_all_sell', 'બધા વેચો', 'main_lang.php'),
( 'gujarati', 'all_users', 'બધા વપરાશકર્તાઓ', 'main_lang.php'),
( 'gujarati', 'all_patients', 'બધા દર્દીઓ', 'main_lang.php'),
( 'gujarati', 'all_clinic', 'બધા ક્લિનિક', 'main_lang.php'),
( 'gujarati', 'all_folloups', 'બધા અનુસરો અપ્સ', 'main_lang.php'),
( 'gujarati', 'appointment', 'નિમણૂંક', 'main_lang.php'),
( 'gujarati', 'appointment_details', 'નિમણૂંક વિગતો', 'main_lang.php'),
( 'gujarati', 'appointment_report', 'નિમણૂંક રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'appointments', 'નિમણૂંકો', 'main_lang.php'),
( 'gujarati', 'appointment_reason', 'નિમણૂંક કારણ', 'main_lang.php'),
( 'gujarati', 'appointment_time_interval', 'નિમણૂંક સમય અંતરાલ', 'main_lang.php'),
( 'gujarati', 'appointment_date', 'નિમણૂંક તારીખ ', 'main_lang.php'),
( 'gujarati', 'assets', 'અસ્કયામતો', 'main_lang.php'),
( 'gujarati', 'availability', 'ઉપલબ્ધતા', 'main_lang.php'),
( 'gujarati', 'available', 'ઉપલબ્ધ', 'main_lang.php'),
( 'gujarati', 'available_stock', 'ઉપલબ્ધ સ્ટોક', 'main_lang.php'),
( 'gujarati', 'additional_detail_label', 'વધારાની વિગતવાર લેબલ', 'main_lang.php'),
( 'gujarati', 'adjust_from_account', 'એકાઉન્ટમાંથી સમાયોજિત કરો', 'main_lang.php'),
( 'gujarati', 'average_price', 'સરેરાશ કિંમત', 'main_lang.php'),
( 'gujarati', 'amount_in_account', 'ખાતામાં રકમ', 'main_lang.php'),
( 'gujarati', 'approve', 'મંજૂર', 'main_lang.php'),
( 'gujarati', 'additional_detail', 'વધારાની વિગત', 'main_lang.php'),
( 'gujarati', 'baby_teeth', 'બેબી દાંત', 'main_lang.php'),
( 'gujarati', 'backup', 'બેકઅપ', 'main_lang.php'),
( 'gujarati', 'back', 'પાછા', 'main_lang.php'),
( 'gujarati', 'backup_restore', 'બેકઅપ પુનઃસ્થાપિત કરો', 'main_lang.php'),
( 'gujarati', 'back_to', 'પાછળ', 'main_lang.php'),
( 'gujarati', 'balance', 'બેલેન્સ', 'main_lang.php'),
( 'gujarati', 'back_to_app', 'પાછા નિમણૂંક માટે', 'main_lang.php'),
( 'gujarati', 'back_to_visit', 'પાછા મુલાકાત લો ', 'main_lang.php'),
( 'gujarati', 'book_an_appoinment', 'એક નિમણૂંક બુક', 'main_lang.php'),
( 'gujarati', 'balance_amount', 'બેલેન્સ રકમ', 'main_lang.php'),
( 'gujarati', 'bank_payment', 'બેન્ક ચુકવણી', 'main_lang.php'),
( 'gujarati', 'bank_payments', 'બેન્ક ચુકવણીઓ', 'main_lang.php'),
( 'gujarati', 'bank_receipt', 'બેંક રસીદ', 'main_lang.php'),
( 'gujarati', 'barcode', 'બારકોડ', 'main_lang.php'),
( 'gujarati', 'bank_receipts', 'બેન્ક રસીદો', 'main_lang.php'),
( 'gujarati', 'bed', 'બેડ', 'main_lang.php'),
( 'gujarati', 'before', 'પહેલાં', 'main_lang.php'),
( 'gujarati', 'beds', 'બેડ્સ', 'main_lang.php'),
( 'gujarati', 'bills', 'બિલ્સ', 'main_lang.php'),
( 'gujarati', 'bill', 'બિલ', 'main_lang.php'),
( 'gujarati', 'bill_amount', 'બિલ રકમ', 'main_lang.php'),
( 'gujarati', 'bill_no', 'બિલ નં', 'main_lang.php'),
( 'gujarati', 'bill_details', 'બિલ વિગતો', 'main_lang.php'),
( 'gujarati', 'bill_id', 'બિલ આઈડી', 'main_lang.php'),
( 'gujarati', 'bill_date', 'બિલ તારીખ', 'main_lang.php'),
( 'gujarati', 'bills_payments', 'ચુકવણી', 'main_lang.php'),
( 'gujarati', 'bill_number', 'બિલ નં.', 'main_lang.php'),
( 'gujarati', 'back_to_payment', 'ચુકવણી પર પાછા', 'main_lang.php'),
( 'gujarati', 'back_to_appointment', 'નિમણૂંક પર પાછા', 'main_lang.php'),
( 'gujarati', 'bill_type', 'બિલનો પ્રકાર', 'main_lang.php'),
( 'gujarati', 'body', 'બોડી', 'main_lang.php'),
( 'gujarati', 'bill_report', 'બિલ રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'book', 'પુસ્તક', 'main_lang.php'),
( 'gujarati', 'bought_at', 'ખરીદી પર', 'main_lang.php'),
( 'gujarati', 'bought_avg', 'ખરીદી સરેરાશ', 'main_lang.php'),
( 'gujarati', 'bought_quantity', 'ખરીદી જથ્થો', 'main_lang.php'),
( 'gujarati', 'browse', 'બ્રાઉઝ', 'main_lang.php'),
( 'gujarati', 'bottom_section_1', 'નીચે વિભાગ 1', 'main_lang.php'),
( 'gujarati', 'blood_group', 'બ્લડ ગ્રુપ', 'main_lang.php'),
( 'gujarati', 'bottom_section_2', 'નીચે ભાગ 2', 'main_lang.php'),
( 'gujarati', 'book_appoinment', 'બુક નિમણૂક', 'main_lang.php'),
( 'gujarati', 'button', 'બટન', 'main_lang.php'),
( 'gujarati', 'button_text', 'બટન ટેક્સ્ટ', 'main_lang.php'),
( 'gujarati', 'bottom_section_3', 'નીચે ભાગ 3', 'main_lang.php'),
( 'gujarati', 'button_url', 'બટન URL', 'main_lang.php'),
( 'gujarati', 'bonus_percentage', 'બોનસ ટકા', 'main_lang.php'),
( 'gujarati', 'bonus', 'બોનસ', 'main_lang.php'),
( 'gujarati', 'billed', 'બિલ', 'main_lang.php'),
( 'gujarati', 'calendar', 'માસિક કૅલેન્ડર', 'main_lang.php'),
( 'gujarati', 'calendar_hours', 'દૈનિક કૅલેન્ડર', 'main_lang.php'),
( 'gujarati', 'cancel', 'રદ કરો', 'main_lang.php'),
( 'gujarati', 'cancelled', 'રદ', 'main_lang.php'),
( 'gujarati', 'cash', 'કેશ', 'main_lang.php'),
( 'gujarati', 'cases', 'કેસ', 'main_lang.php'),
( 'gujarati', 'case', 'કેસ', 'main_lang.php'),
( 'gujarati', 'cash_receipt', 'રોકડ રસીદ', 'main_lang.php'),
( 'gujarati', 'case_number', 'કેસ નં.', 'main_lang.php'),
( 'gujarati', 'cash_receipts', 'રોકડ રસીદો', 'main_lang.php'),
( 'gujarati', 'cash_payment', 'રોકડ ચુકવણી', 'main_lang.php'),
( 'gujarati', 'cash_payments', 'રોકડ ચુકવણીઓ', 'main_lang.php'),
( 'gujarati', 'category', 'વર્ગ', 'main_lang.php'),
( 'gujarati', 'categories', 'શ્રેણીઓ', 'main_lang.php'),
( 'gujarati', 'center', 'કેન્દ્ર', 'main_lang.php'),
( 'gujarati', 'case_date', 'કેસ તારીખ', 'main_lang.php'),
( 'gujarati', 'centers', 'કેન્દ્રો', 'main_lang.php'),
( 'gujarati', 'center_details', 'કેન્દ્ર વિગતો', 'main_lang.php'),
( 'gujarati', 'center_logo', 'કેન્દ્ર લોગો', 'main_lang.php'),
( 'gujarati', 'center_name', 'કેન્દ્રનું નામ', 'main_lang.php'),
( 'gujarati', 'center_code', 'કેન્દ્ર કોડ', 'main_lang.php'),
( 'gujarati', 'change', 'બદલો', 'main_lang.php'),
( 'gujarati', 'change_theme_color', 'થીમ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'change_center', 'સેન્ટર બદલો', 'main_lang.php'),
( 'gujarati', 'change_language', 'ભાષા બદલો', 'main_lang.php'),
( 'gujarati', 'change_profile', 'પ્રોફાઇલ બદલો', 'main_lang.php'),
( 'gujarati', 'change_status_of_field', 'ક્ષેત્રની સ્થિતિ બદલો', 'main_lang.php'),
( 'gujarati', 'change_timezone', 'ટાઈમ ઝોન બદલો', 'main_lang.php'),
( 'gujarati', 'charges', 'ચાર્જિસ ', 'main_lang.php'),
( 'gujarati', 'charges_fees', 'ચાર્જેસ /ફી', 'main_lang.php'),
( 'gujarati', 'change_template', 'ટેંમ્પ્લેટ બદલો', 'main_lang.php'),
( 'gujarati', 'cheque', 'ચેક', 'main_lang.php'),
( 'gujarati', 'close', 'બંધ', 'main_lang.php'),
( 'gujarati', 'chikitsa_new_version_available', 'ચિકિત્સા નવું સંસ્કરણ ઉપલબ્ધ', 'main_lang.php'),
( 'gujarati', 'city', 'સિટી', 'main_lang.php'),
( 'gujarati', 'choose_file', 'ફાઇલ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'cheque_number', 'ચેક નમ્બર ', 'main_lang.php'),
( 'gujarati', 'clear_data', 'ડેટા સાફ કરો', 'main_lang.php'),
( 'gujarati', 'clinic', 'ક્લિનિક', 'main_lang.php'),
( 'gujarati', 'clinic_address', 'ક્લિનિક સરનામું', 'main_lang.php'),
( 'gujarati', 'clinic_details', 'ક્લિનિક વિગતો', 'main_lang.php'),
( 'gujarati', 'clinic_landline', 'ક્લિનિક લેન્ડલાઇન', 'main_lang.php'),
( 'gujarati', 'clinic_end_time', 'ક્લિનિક અંત સમય', 'main_lang.php'),
( 'gujarati', 'clinic_note', 'ક્લિનિક નોંધ', 'main_lang.php'),
( 'gujarati', 'clinic_logo', 'ક્લિનિક લોગો', 'main_lang.php'),
( 'gujarati', 'clinic_name', 'ક્લિનિક નામ', 'main_lang.php'),
( 'gujarati', 'clinic_phone_1', 'ક્લિનિક ફોન 1', 'main_lang.php'),
( 'gujarati', 'clinic_phone_2', 'ક્લિનિક ફોન 2', 'main_lang.php'),
( 'gujarati', 'clinic_start_time', 'ક્લિનિક શરૂઆત સમય', 'main_lang.php'),
( 'gujarati', 'clinic_runs_full_day', 'ક્લિનિક રન ફુલ ડે', 'main_lang.php'),
( 'gujarati', 'cost', 'ખર્ચ', 'main_lang.php'),
( 'gujarati', 'column_1', 'કૉલમ 1', 'main_lang.php'),
( 'gujarati', 'column_2', 'કૉલમ 2', 'main_lang.php'),
( 'gujarati', 'complete', 'પૂર્ણ', 'main_lang.php'),
( 'gujarati', 'company', 'કંપની', 'main_lang.php'),
( 'gujarati', 'completed_appointment', 'નિમણૂક પૂર્ણ થઈ', 'main_lang.php'),
( 'gujarati', 'company_information', 'કંપની માહિતી', 'main_lang.php'),
( 'gujarati', 'completed_sessions', 'પૂર્ણ સત્રો', 'main_lang.php'),
( 'gujarati', 'compare', 'તુલના', 'main_lang.php'),
( 'gujarati', 'content', 'સામગ્રી', 'main_lang.php'),
( 'gujarati', 'contact', 'સંપર્ક કરો', 'main_lang.php'),
( 'gujarati', 'contact_details', 'સંપર્ક વિગતો', 'main_lang.php'),
( 'gujarati', 'conditions', 'શરતો', 'main_lang.php'),
( 'gujarati', 'country_code', 'દેશનો કોડ', 'main_lang.php'),
( 'gujarati', 'continue', 'ચાલુ રાખો', 'main_lang.php'),
( 'gujarati', 'copyright', '&નકલ; 2016', 'main_lang.php'),
( 'gujarati', 'copyright_text', 'કૉપિરાઇટ ટેક્સ્ટ', 'main_lang.php'),
( 'gujarati', 'copyright_url', 'કૉપિરાઇટ URL', 'main_lang.php'),
( 'gujarati', 'confirm_password', 'પાસવર્ડ ખાતરી કરો', 'main_lang.php'),
( 'gujarati', 'consultation', 'કન્સલ્ટેશન', 'main_lang.php'),
( 'gujarati', 'consultation_in', 'કન્સલ્ટેશન ઇન', 'main_lang.php'),
( 'gujarati', 'consultation_out', 'કન્સલ્ટેશન આઉટ', 'main_lang.php'),
( 'gujarati', 'contact_number', 'સંપર્ક નંબર', 'main_lang.php'),
( 'gujarati', 'cost_price', 'કિંમત ભાવ', 'main_lang.php'),
( 'gujarati', 'country', 'દેશ', 'main_lang.php'),
( 'gujarati', 'curr_post', 'કરન્સી પોસ્ટફિક્સ', 'main_lang.php'),
( 'gujarati', 'curr_pre', 'કરન્સી પ્રેફિક્ષ ', 'main_lang.php'),
( 'gujarati', 'cr_ac_name', 'સી.આર. એ / સી નામ', 'main_lang.php'),
( 'gujarati', 'created_by', 'દ્વારા બનાવવામાં', 'main_lang.php'),
( 'gujarati', 'custom_details', 'કસ્ટમ વિગતો', 'main_lang.php'),
( 'gujarati', 'currency', 'ચલણ', 'main_lang.php'),
( 'gujarati', 'column_1_content', 'કૉલમ 1 - સામગ્રી', 'main_lang.php'),
( 'gujarati', 'column_1_header', 'કૉલમ 1 - મથાળું', 'main_lang.php'),
( 'gujarati', 'contact_us', 'અમારો સંપર્ક કરો', 'main_lang.php'),
( 'gujarati', 'ccavenue', 'CCAvenue', 'main_lang.php'),
( 'gujarati', 'copy', 'નકલ કરો', 'main_lang.php'),
( 'gujarati', 'ccavenue_settings', 'સીસીએવેન્યુ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'cancelled_appoinment_by_patient', 'દર્દી દ્વારા નિમણૂંક રદ કરવાના કિસ્સામાં, રિફંડ જાતે જ કરવું પડશે', 'main_lang.php'),
( 'gujarati', 'change_language_file', 'ભાષા ફાઇલમાં શબ્દો બદલો', 'main_lang.php'),
( 'gujarati', 'create_language_file', 'નવી ભાષા ફાઇલ બનાવો', 'main_lang.php'),
( 'gujarati', 'dose', 'ડોઝ', 'main_lang.php'),
( 'gujarati', 'day', 'દિવસ', 'main_lang.php'),
( 'gujarati', 'does_not_has_value', 'તેની કિંમત નથી', 'main_lang.php'),
( 'gujarati', 'dr_ac_name', 'ડો. એ / સી નામ', 'main_lang.php'),
( 'gujarati', 'compare_image', 'તુલના માટે ઓછામાં ઓછી બે છબીઓ આવશ્યક છે', 'main_lang.php'),
( 'gujarati', 'days', 'દિવસ', 'main_lang.php'),
( 'gujarati', 'daily', 'દૈનિક', 'main_lang.php'),
( 'gujarati', 'daily_hour', 'દૈનિક / કલાક દીઠ', 'main_lang.php'),
( 'gujarati', 'daily_per_bed_charge', 'દીઠ બેડ ચાર્જ ( દૈનિક )', 'main_lang.php'),
( 'gujarati', 'date', 'તારીખ', 'main_lang.php'),
( 'gujarati', 'dashboard', 'ડેશબોર્ડ', 'main_lang.php'),
( 'gujarati', 'date_format', 'તારીખ ફોર્મેટ', 'main_lang.php'),
( 'gujarati', 'deallocate', 'ખાલી કરો ', 'main_lang.php'),
( 'gujarati', 'deactivate', 'નિષ્ક્રિય કરવા', 'main_lang.php'),
( 'gujarati', 'degrees', 'ડિગ્રી', 'main_lang.php'),
( 'gujarati', 'delete', 'કાઢી નાખો', 'main_lang.php'),
( 'gujarati', 'delete_item', 'વસ્તુ કાઢી નાખો', 'main_lang.php'),
( 'gujarati', 'delete_treatment', 'સારવાર કાઢી નાખો', 'main_lang.php'),
( 'gujarati', 'delete_supplier', 'સપ્લાયર કાઢી નાખો', 'main_lang.php'),
( 'gujarati', 'delete_user', 'વપરાશકર્તા કાઢી નાંખો', 'main_lang.php'),
( 'gujarati', 'department', 'વિભાગ', 'main_lang.php'),
( 'gujarati', 'department_name', 'વિભાગ નામ', 'main_lang.php'),
( 'gujarati', 'departments', 'વિભાગો', 'main_lang.php'),
( 'gujarati', 'desired_stock', 'ઇચ્છિત સ્ટોક', 'main_lang.php'),
( 'gujarati', 'detail', 'વિગત', 'main_lang.php'),
( 'gujarati', 'details', 'વિગતો', 'main_lang.php'),
( 'gujarati', 'default', 'ડિફૉલ્ટ', 'main_lang.php'),
( 'gujarati', 'due_amount', 'નિયત રકમ', 'main_lang.php'),
( 'gujarati', 'discount', 'ડિસ્કાઉન્ટ', 'main_lang.php'),
( 'gujarati', 'dismissed', 'બરતરફ', 'main_lang.php'),
( 'gujarati', 'dismiss', 'કાઢી નાખો', 'main_lang.php'),
( 'gujarati', 'display', 'ડિસ્પ્લે', 'main_lang.php'),
( 'gujarati', 'display_google_ads', 'Google જાહેરાતો દર્શાવો', 'main_lang.php'),
( 'gujarati', 'display_name', 'ડિસ્પ્લે નામ', 'main_lang.php'),
( 'gujarati', 'display_in', 'પ્રદર્શિત', 'main_lang.php'),
( 'gujarati', 'discount_amount', 'ડિસ્કાઉન્ટ રકમ', 'main_lang.php'),
( 'gujarati', 'discount_percentage', 'ડિસ્કાઉન્ટ ટકાવારી', 'main_lang.php'),
( 'gujarati', 'dob', 'જ્ન્મતારીખ', 'main_lang.php'),
( 'gujarati', 'doctor', 'ડોક્ટર', 'main_lang.php'),
( 'gujarati', 'doctors', 'ડૉક્ટર્સ', 'main_lang.php'),
( 'gujarati', 'doctor_name', 'ડોક્ટરનું નામ', 'main_lang.php'),
( 'gujarati', 'doctor_share', 'ડોક્ટર શેર', 'main_lang.php'),
( 'gujarati', 'doctor_availability', 'ડોક્ટર ઉપલબ્ધતા', 'main_lang.php'),
( 'gujarati', 'doctor_detail', 'ડોક્ટર વિગત', 'main_lang.php'),
( 'gujarati', 'doctor_bonus_report', 'ડોક્ટર બોનસ રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'doctor_unavailability', 'ડોક્ટર ઉપલબ્ધ નથી', 'main_lang.php'),
( 'gujarati', 'doctor_inavailability', 'ડોક્ટર ઉપલબ્ધ નથી', 'main_lang.php'),
( 'gujarati', 'doctor_schedule', 'ડોક્ટર સૂચિ', 'main_lang.php'),
( 'gujarati', 'doctor_preferences', 'ડોક્ટરની પસંદગી', 'main_lang.php'),
( 'gujarati', 'download', 'ડાઉનલોડ ', 'main_lang.php'),
( 'gujarati', 'download_extension', 'એક્સ્ટેંશન ડાઉનલોડ કરો', 'main_lang.php'),
( 'gujarati', 'downloading_files', 'ડાઉનલોડ ફાઇલો ', 'main_lang.php'),
( 'gujarati', 'duration', 'સમયગાળો', 'main_lang.php'),
( 'gujarati', 'dr', 'Dr.', 'main_lang.php'),
( 'gujarati', 'duplicate', 'ડુપ્લિકેટ', 'main_lang.php'),
( 'gujarati', 'description', 'વર્ણન', 'main_lang.php'),
( 'gujarati', 'disease', 'રોગ', 'main_lang.php'),
( 'gujarati', 'diagnosed_diseases', 'નિદાન રોગ', 'main_lang.php'),
( 'gujarati', 'diseases', 'રોગો', 'main_lang.php'),
( 'gujarati', 'decimal_symbol', 'દશાંશ પ્રતીક', 'main_lang.php'),
( 'gujarati', 'eraser', 'ઇરેઝર', 'main_lang.php'),
( 'gujarati', 'erpnext_sync', 'Erpnext Sync', 'main_lang.php'),
( 'gujarati', 'erpnext_url', 'Erpnext URL', 'main_lang.php'),
( 'gujarati', 'end_date', 'અંતિમ તારીખ', 'main_lang.php'),
( 'gujarati', 'end_time', 'અંત સમય', 'main_lang.php'),
( 'gujarati', 'enable_about_page', 'વિશે પેજમાં સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'edit_Contact', 'સંપર્ક સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'edit', 'સંપાદિત ', 'main_lang.php'),
( 'gujarati', 'edit_section', 'વિભાગ સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'edit_treatment', 'સારવાર સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'edit_user', 'વપરાશકર્તા સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'edit_medicine_too', 'દવા પણ સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'edit_test', 'પરીક્ષણ સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'email_log', 'ઇમેઇલ લોગ', 'main_lang.php'),
( 'gujarati', 'email', 'ઇમેઇલ', 'main_lang.php'),
( 'gujarati', 'email_alert_name', 'ઇમેઇલ ચેતવણી નામ', 'main_lang.php'),
( 'gujarati', 'email_id', 'ઇમેઇલ આઈડી', 'main_lang.php'),
( 'gujarati', 'email_bill', 'ઇમેઇલ બિલ', 'main_lang.php'),
( 'gujarati', 'email_settings', 'ઇમેઇલ સેટિંગ્સ ', 'main_lang.php'),
( 'gujarati', 'established_patient', 'સ્થાપિત પેશન્ટ', 'main_lang.php'),
( 'gujarati', 'enter_details_to_login', 'લોગીન થવા માટે વીગતો ભરો ', 'main_lang.php'),
( 'gujarati', 'enter_email_address', 'ઇમેઇલ સરનામું દાખલ કરો ', 'main_lang.php'),
( 'gujarati', 'extracting', 'એક્સટ્રેક્ટિંગ', 'main_lang.php'),
( 'gujarati', 'extraction_failed', 'એક્સટ્રેક્શન નિષ્ફળ', 'main_lang.php'),
( 'gujarati', 'extensions', 'એક્સ્ટેન્શન્સ', 'main_lang.php'),
( 'gujarati', 'expenditure', 'ખર્ચ', 'main_lang.php'),
( 'gujarati', 'experience', 'અનુભવ', 'main_lang.php'),
( 'gujarati', 'exceptional_days', 'અપવાદરૂપ દિવસો', 'main_lang.php'),
( 'gujarati', 'export_to_excel', 'Excel માં નિકાસ કરો', 'main_lang.php'),
( 'gujarati', 'expiry_date', 'અંતિમ તારીખ', 'main_lang.php'),
( 'gujarati', 'enter_new_password', 'નીચે તમારો નવો પાસવર્ડ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'enable_news', 'સમાચાર પૃષ્ઠને સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'enable_online_appointment', 'ઓનલાઇન નિમણૂંક બુકિંગ સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'enable_paypal', 'PayPal સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'enable_admin_approval', 'એડમિન મંજૂરી સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'enable_ccavenue', 'CCAvenue સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'enable_sandbox', 'Sandbox સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'enable_service_page', 'સેવા પૃષ્ઠને સક્ષમ કરો', 'main_lang.php'),
( 'gujarati', 'email_alert_time', 'ઇમેઇલ ચેતવણી સમય', 'main_lang.php'),
( 'gujarati', 'email_format', 'ઇમેઇલ ફોર્મેટ', 'main_lang.php'),
( 'gujarati', 'edit_format', 'ફોર્મેટ સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'edit_language', 'ભાષા સંપાદિત કરો', 'main_lang.php'),
( 'gujarati', 'face', 'ફેસ', 'main_lang.php'),
( 'gujarati', 'facebook', 'ફેસબુક', 'main_lang.php'),
( 'gujarati', 'facebook_link', 'ફેસબુક લિંક', 'main_lang.php'),
( 'gujarati', 'fax', 'ફેક્સ', 'main_lang.php'),
( 'gujarati', 'fees', 'ફી', 'main_lang.php'),
( 'gujarati', 'fees_detail', 'ફી', 'main_lang.php'),
( 'gujarati', 'female', 'સ્ત્રી', 'main_lang.php'),
( 'gujarati', 'file', 'ફાઇલ', 'main_lang.php'),
( 'gujarati', 'file_content', 'ફાઇલ સામગ્રી', 'main_lang.php'),
( 'gujarati', 'filter', 'ફિલ્ટર', 'main_lang.php'),
( 'gujarati', 'first', 'પ્રથમ', 'main_lang.php'),
( 'gujarati', 'first_name', 'પ્રથમ નામ', 'main_lang.php'),
( 'gujarati', 'fields', 'ક્ષેત્રો', 'main_lang.php'),
( 'gujarati', 'find_us_here', 'અમને અહીં શોધો', 'main_lang.php'),
( 'gujarati', 'field_label', 'ફીલ્ડ લેબલ', 'main_lang.php'),
( 'gujarati', 'field_options', 'ક્ષેત્ર વિકલ્પ', 'main_lang.php'),
( 'gujarati', 'field_order', 'ક્ષેત્રનો ઓર્ડર', 'main_lang.php'),
( 'gujarati', 'field_name', 'ક્ષેત્રનું નામ', 'main_lang.php'),
( 'gujarati', 'field_type', 'ક્ષેત્રનો પ્રકાર', 'main_lang.php'),
( 'gujarati', 'field_width', 'ક્ષેત્રની પહોળાઈ', 'main_lang.php'),
( 'gujarati', 'field_status', 'ક્ષેત્રની સ્થિતિ', 'main_lang.php'),
( 'gujarati', 'foc', 'એફ.ઓ.સી .', 'main_lang.php'),
( 'gujarati', 'follow', 'અનુસરો', 'main_lang.php'),
( 'gujarati', 'follow_on', 'અનુસારવાનું ચાલુ રાખો', 'main_lang.php'),
( 'gujarati', 'follow_up', 'ફોલોઅપ', 'main_lang.php'),
( 'gujarati', 'footer_credits', 'ફૂટર ક્રેડિટ્સ', 'main_lang.php'),
( 'gujarati', 'follow_ups', 'ફોલોઅપ્સ', 'main_lang.php'),
( 'gujarati', 'footer_credit_settings', 'ફૂટર ક્રેડિટ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'footer_settings', 'ફૂટર સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'for', 'માટે', 'main_lang.php'),
( 'gujarati', 'forgot_password', 'પાસવર્ડ ભૂલી ગયા છો?', 'main_lang.php'),
( 'gujarati', 'frequency', 'આવર્તન', 'main_lang.php'),
( 'gujarati', 'form', 'ફોર્મ', 'main_lang.php'),
( 'gujarati', 'found', 'મળી', 'main_lang.php'),
( 'gujarati', 'from_date', 'તારીખ થી', 'main_lang.php'),
( 'gujarati', 'from_time', 'સમય થી', 'main_lang.php'),
( 'gujarati', 'from_name', 'નામ પ્રતિ', 'main_lang.php'),
( 'gujarati', 'to_time', 'સમય સુધી ', 'main_lang.php'),
( 'gujarati', 'frontend', 'અગ્ર', 'main_lang.php'),
( 'gujarati', 'from_doctor', 'ડૉક્ટર પાસેથી', 'main_lang.php'),
( 'gujarati', 'framework', 'ફ્રેમવર્ક', 'main_lang.php'),
( 'gujarati', 'full_day', 'આખો દિવસ', 'main_lang.php'),
( 'gujarati', 'fixed_amount', 'સ્થિર રકમ', 'main_lang.php'),
( 'gujarati', 'featured', 'ફીચર્ડ', 'main_lang.php'),
( 'gujarati', 'from_email', 'ઇમેઇલ પ્રતિ', 'main_lang.php'),
( 'gujarati', 'featured_image', 'ફીચર્ડ છબી', 'main_lang.php'),
( 'gujarati', 'footer_section_1', 'ફૂટર વિભાગ1', 'main_lang.php'),
( 'gujarati', 'footer_section_2', 'ફૂટર વિભાગ 2', 'main_lang.php'),
( 'gujarati', 'footer_section_3', 'ફૂટર વિભાગ 3', 'main_lang.php'),
( 'gujarati', 'footer_section_4', 'ફૂટર વિભાગ 4', 'main_lang.php'),
( 'gujarati', 'file_size', 'મહત્તમ ફાઇલ કદને મંજૂરી આપો (KB માં)', 'main_lang.php'),
( 'gujarati', 'file_type', 'માન્ય ફાઇલ પ્રકારો', 'main_lang.php'),
( 'gujarati', 'file_type_msg', 'jpeg|jpg|png વગેરે દ્વારા ફાઇલ પ્રકારોને અલગ કરો.', 'main_lang.php'),
( 'gujarati', 'gender', 'લિંગ', 'main_lang.php'),
( 'gujarati', 'gain', 'લાભ', 'main_lang.php'),
( 'gujarati', 'gallery', 'ગેલેરી', 'main_lang.php'),
( 'gujarati', 'go', 'જાઓ', 'main_lang.php'),
( 'gujarati', 'google_plus', 'ગૂગલ પ્લસ', 'main_lang.php'),
( 'gujarati', 'general_settings', 'સામાન્ય સુયોજનો', 'main_lang.php'),
( 'gujarati', 'group_name', 'જૂથનું નામ', 'main_lang.php'),
( 'gujarati', 'group_by', 'ગ્રુપ દ્વારા', 'main_lang.php'),
( 'gujarati', 'group', 'ગ્રુપ', 'main_lang.php'),
('gujarati', 'gallery_setting_msg', '(તમે એડમિનિસ્ટ્રેશન > સેટિંગ્સ > ગેલેરીમાંથી માન્ય ફાઇલ પ્રકારો અને માન્ય ફાઇલ કદનું સંચાલન કરી શકો છો)', 'main_lang.php') ,
( 'gujarati', 'header', 'હેડર', 'main_lang.php'),
( 'gujarati', 'home', 'હોમ', 'main_lang.php'),
( 'gujarati', 'hidden', 'છુપાયેલ', 'main_lang.php'),
( 'gujarati', 'hour', 'કલાક', 'main_lang.php'),
( 'gujarati', 'html_content', 'HTML સામગ્રી', 'main_lang.php'),
( 'gujarati', 'hourly', 'કલાકના ', 'main_lang.php'),
( 'gujarati', 'hourly_per_bed_charge', 'બેડ દીઠ ચાર્જ ( કલાકના )', 'main_lang.php'),
( 'gujarati', 'header_settings', 'હેડર સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'header_contact_number', 'મથાળું સંપર્ક નંબર', 'main_lang.php'),
( 'gujarati', 'home_settings', 'મુખ્ય પૃષ્ઠ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'has_additional_details', 'વધારાની વિગતો છે', 'main_lang.php'),
( 'gujarati', 'has_value', 'મૂલ્ય ધરાવે છે', 'main_lang.php'),
( 'gujarati', 'heading', 'મથાળું', 'main_lang.php'),
( 'gujarati', 'history', 'ઇતિહાસ', 'main_lang.php'),
( 'gujarati', 'home_page_slider', 'મુખ્ય પૃષ્ઠ સ્લાઇડર', 'main_lang.php'),
( 'gujarati', 'home_page_settings', 'મુખ્ય પૃષ્ઠ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'home_page_top_section', 'હોમ પેજ ટોચના વિભાગ', 'main_lang.php'),
( 'gujarati', 'home_page_bottom_section', 'મુખ્ય પૃષ્ઠ તળિયે વિભાગ', 'main_lang.php'),
( 'gujarati', 'half_day', 'અર્ધ દિવસ', 'main_lang.php'),
( 'gujarati', 'invoice', 'ભરતિયું', 'main_lang.php'),
( 'gujarati', 'if_field', 'જો ક્ષેત્ર ', 'main_lang.php'),
( 'gujarati', 'id', 'આઈડી', 'main_lang.php'),
( 'gujarati', 'icon', 'ચિહ્ન', 'main_lang.php'),
( 'gujarati', 'inavailablity', 'અસફળતા', 'main_lang.php'),
( 'gujarati', 'install', 'સ્થાપિત', 'main_lang.php'),
( 'gujarati', 'installing', 'સ્થાપન કરી રહ્યા છીએ', 'main_lang.php'),
( 'gujarati', 'invoice_number', 'બીલ નંબર', 'main_lang.php'),
( 'gujarati', 'invoice_prefix', 'ભરતિયું ઉપસર્ગ', 'main_lang.php'),
( 'gujarati', 'invoice_details', 'ભરતિયું વિગતો', 'main_lang.php'),
( 'gujarati', 'invoice_settings', 'ભરતિયું સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'instructions', 'સૂચનાઓ', 'main_lang.php'),
( 'gujarati', 'in_minutes', 'મિનિટમાં', 'main_lang.php'),
( 'gujarati', 'is_active', 'સક્રિય છે', 'main_lang.php'),
( 'gujarati', 'in_group', 'જૂથમાં', 'main_lang.php'),
( 'gujarati', 'is_checked', 'તપાસવામાં આવે છે', 'main_lang.php'),
( 'gujarati', 'is_unchecked', 'અનચેક થયેલ છે', 'main_lang.php'),
( 'gujarati', 'is_default', 'મૂળભૂત છે', 'main_lang.php'),
( 'gujarati', 'item_name', 'વસ્તુનું નામ', 'main_lang.php'),
( 'gujarati', 'item', 'વસ્તુ', 'main_lang.php'),
( 'gujarati', 'item_number', 'આઇટમ નંબર', 'main_lang.php'),
( 'gujarati', 'items', 'વસ્તુઓ', 'main_lang.php'),
( 'gujarati', 'item_type', 'આઇટમનો પ્રકાર', 'main_lang.php'),
( 'gujarati', 'import', 'CSV આયાત કરો', 'main_lang.php'),
( 'gujarati', 'image', 'છબી', 'main_lang.php'),
( 'gujarati', 'images', 'છબીઓ', 'main_lang.php'),
( 'gujarati', 'image_id', 'છબી આઈડી', 'main_lang.php'),
( 'gujarati', 'image_name', 'છબી નામ', 'main_lang.php'),
( 'gujarati', 'image_path', 'છબી પાથ', 'main_lang.php'),
( 'gujarati', 'income', 'આવક', 'main_lang.php'),
( 'gujarati', 'issue_refund', 'મુદ્દો રિફંડ', 'main_lang.php'),
( 'gujarati', 'individual', 'વ્યક્તિગત', 'main_lang.php'),
( 'gujarati', 'information', 'માહિતી', 'main_lang.php'),
( 'gujarati', 'joining_date', 'તારીખ જોડાયા', 'main_lang.php'),
( 'gujarati', 'jurisdiction', 'સુરત અધિકારક્ષેત્ર માટે વિષય', 'main_lang.php'),
( 'gujarati', 'journal_vouchers', 'જર્નલ વાઉચર', 'main_lang.php'),
( 'gujarati', 'journal_voucher', 'જર્નલ વાઉચર', 'main_lang.php'),
( 'gujarati', 'key', 'કી', 'main_lang.php'),
( 'gujarati', 'landline', 'લેન્ડલાઇન', 'main_lang.php'),
( 'gujarati', 'languages', 'ભાષાઓ', 'main_lang.php'),
( 'gujarati', 'last', 'છેલ્લા', 'main_lang.php'),
( 'gujarati', 'lab_reports', 'લેબ રિપોર્ટ્સ', 'main_lang.php'),
( 'gujarati', 'lab_tests', 'લેબ ટેસ્ટ', 'main_lang.php'),
( 'gujarati', 'last_name', 'છેલ્લું નામ', 'main_lang.php'),
( 'gujarati', 'lab_instructions', 'લેબ સૂચનો', 'main_lang.php'),
( 'gujarati', 'latest_news', 'તાજા સમાચાર', 'main_lang.php'),
( 'gujarati', 'lab_test', 'લેબ ટેસ્ટ', 'main_lang.php'),
( 'gujarati', 'length_invoice', 'ભરતિયું સંખ્યાની લંબાઈ', 'main_lang.php'),
( 'gujarati', 'login', 'પ્રવેશ કરો', 'main_lang.php'),
( 'gujarati', 'login_yourself_to_get_access', 'પ્રવેશ મેળવવા માટે સ્વયં પ્રવેશ કરો', 'main_lang.php'),
( 'gujarati', 'log_out', 'લૉગ આઉટ', 'main_lang.php'),
( 'gujarati', 'license_key', 'લાઈસન્સ કી', 'main_lang.php'),
( 'gujarati', 'licence_number', 'લાઇસેંસ નંબર', 'main_lang.php'),
( 'gujarati', 'line1', 'લાઇન 1', 'main_lang.php'),
( 'gujarati', 'line2', 'લાઇન 2', 'main_lang.php'),
( 'gujarati', 'liabilities', 'જવાબદારીઓ', 'main_lang.php'),
( 'gujarati', 'list_master', 'યાદી માસ્ટર', 'main_lang.php'),
( 'gujarati', 'language', 'ભાષા', 'main_lang.php'),
( 'gujarati', 'language_name', 'ભાષા નામ', 'main_lang.php'),
( 'gujarati', 'latest', 'નવીનતમ', 'main_lang.php'),
( 'gujarati', 'link', 'લિંક', 'main_lang.php'),
( 'gujarati', 'link_text', 'લિંક ટેક્સ્ટ', 'main_lang.php'),
( 'gujarati', 'link_url', 'લિંક URL', 'main_lang.php'),
( 'gujarati', 'male', 'પુરૂષ', 'main_lang.php'),
( 'gujarati', 'marker', 'માર્કર', 'main_lang.php'),
( 'gujarati', 'marking', 'નિશાન', 'main_lang.php'),
( 'gujarati', 'marking_images', 'છબીઓ ચિહ્નિત કરી રહ્યા છીએ', 'main_lang.php'),
( 'gujarati', 'max_patient', 'એક સમયે મહત્તમદર્દીઓ', 'main_lang.php'),
( 'gujarati', 'medicine', 'દવા', 'main_lang.php'),
( 'gujarati', 'medicine_store_bill', 'મેડિસિન સ્ટોર બિલ', 'main_lang.php'),
( 'gujarati', 'menu_access', 'મેનુ ઍક્સેસ', 'main_lang.php'),
( 'gujarati', 'medicine_name', 'દવા નામ', 'main_lang.php'),
( 'gujarati', 'middle', 'મિડલ', 'main_lang.php'),
( 'gujarati', 'medicines', 'દવાઓ', 'main_lang.php'),
( 'gujarati', 'mobile', 'મોબાઇલ', 'main_lang.php'),
( 'gujarati', 'mobile_no', 'મોબાઈલ નંબર', 'main_lang.php'),
( 'gujarati', 'module', 'મોડ્યુલ', 'main_lang.php'),
( 'gujarati', 'mode', 'મોડ', 'main_lang.php'),
( 'gujarati', 'mrp', 'M.R.P.', 'main_lang.php'),
( 'gujarati', 'morning', 'M', 'main_lang.php'),
( 'gujarati', 'middle_name', 'પિતાનું નામ', 'main_lang.php'),
( 'gujarati', 'modules', 'મોડ્યુલો', 'main_lang.php'),
( 'gujarati', 'minutes', 'મિનિટ', 'main_lang.php'),
( 'gujarati', 'make', 'બનાવો', 'main_lang.php'),
( 'gujarati', 'morning_time', 'સવારનો સમય', 'main_lang.php'),
( 'gujarati', 'media', 'મીડિયા', 'main_lang.php'),
( 'gujarati', 'message', 'સંદેશ', 'main_lang.php'),
( 'gujarati', 'merchant_id', 'વેપારી ID', 'main_lang.php'),
( 'gujarati', 'my_account', 'મારું ખાતું', 'main_lang.php'),
( 'gujarati', 'make_appointment', 'નિમણૂક કરો', 'main_lang.php'),
( 'gujarati', 'minimum_stock', 'ન્યૂનતમ સ્ટોક આવશ્યક છે', 'main_lang.php'),
( 'gujarati', 'make_an_appointment', 'મુલાકાત માટે સમય ફાળવો', 'main_lang.php'),
( 'gujarati', 'maximum_about_posts', '(તમે મહત્તમ પોસ્ટ્સ વિશે પહોંચી ગયા છો જેને ઉમેરી શકાય છે)', 'main_lang.php'),
( 'gujarati', 'maximum_top_posts', '(તમે મહત્તમ ટોપ સેક્શન પોસ્ટ્સ પર પહોંચી ગયા છો જે ઉમેરી શકાય છે) ', 'main_lang.php'),
( 'gujarati', 'maximum_footer_posts', '(તમે મહત્તમ ફૂટર વિભાગોની પોસ્ટ્સ સુધી પહોંચી ગયા છો જેને ઉમેરી શકાય છે)', 'main_lang.php'),
( 'gujarati', 'maximum_bottom_posts', '(તમે મહત્તમ બોટમ સેક્શન પોસ્ટ્સ પર પહોંચી ગયા છો જે ઉમેરી શકાય છે) ', 'main_lang.php'),
( 'gujarati', 'maximum_footer_credits', '(તમે મહત્તમ ફૂટર ક્રેડિટ પોસ્ટ્સ પર પહોંચી ગયા છો જે ઉમેરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'month', 'માસ', 'main_lang.php'),
( 'gujarati', 'minimum_income', 'ન્યૂનતમ આવક', 'main_lang.php'),
( 'gujarati', 'medical', 'તબીબી', 'main_lang.php'),
( 'gujarati', 'name', 'નામ', 'main_lang.php'),
( 'gujarati', 'none', 'કોઈ નહીં', 'main_lang.php'),
( 'gujarati', 'net_total', 'કુલ રકમ', 'main_lang.php'),
( 'gujarati', 'next_follow_up', 'આગળ ફોલોઅપ પછી', 'main_lang.php'),
( 'gujarati', 'next_follow_date', 'આગળ ફોલોઅપની તારીખ', 'main_lang.php'),
( 'gujarati', 'news_date', 'સમાચાર તારીખ', 'main_lang.php'),
( 'gujarati', 'news_title', 'શીર્ષક', 'main_lang.php'),
( 'gujarati', 'new', 'નવું', 'main_lang.php'),
( 'gujarati', 'news', 'સમાચાર', 'main_lang.php'),
( 'gujarati', 'new_contact', 'નવા સંપર્ક', 'main_lang.php'),
( 'gujarati', 'new_appointment', 'નવી નિમણૂક', 'main_lang.php'),
( 'gujarati', 'new_inquiry', 'નવી તપાસ', 'main_lang.php'),
( 'gujarati', 'new_inquires', 'નવી પૂછપરછ', 'main_lang.php'),
( 'gujarati', 'new_password', 'નવો પાસવર્ડ', 'main_lang.php'),
( 'gujarati', 'new_sell', 'નવા વેચાણ', 'main_lang.php'),
( 'gujarati', 'news_setting', 'સમાચાર પૃષ્ઠ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'no', 'નં.', 'main_lang.php'),
( 'gujarati', 'night', 'N', 'main_lang.php'),
( 'gujarati', 'no_of_beds', 'બેડ્સ ની સંખ્યા ', 'main_lang.php'),
( 'gujarati', 'not_available', 'ઉપલબ્ધ નથી', 'main_lang.php'),
( 'gujarati', 'non_taxable_revenue', 'બિન કરપાત્ર આવક', 'main_lang.php'),
( 'gujarati', 'notes', 'નોંધો', 'main_lang.php'),
( 'gujarati', 'notes_for_patient', 'પેશન્ટ માટે નોંધો', 'main_lang.php'),
( 'gujarati', 'number', 'સંખ્યા', 'main_lang.php'),
( 'gujarati', 'number_of_columns', 'સ્તંભોની સંખ્યા', 'main_lang.php'),
( 'gujarati', 'news_page_settings', 'સમાચાર પૃષ્ઠ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'night_time', 'નાઇટ ટાઇમ', 'main_lang.php'),
( 'gujarati', 'no_prescription', 'કોઈ પ્રિસ્ક્રિપ્શન મળી નથી', 'main_lang.php'),
( 'gujarati', 'needs_cash_calc', 'કેશ કેલ્ક્યુલેટરની જરૂર છે', 'main_lang.php'),
( 'gujarati', 'nurse', 'નર્સ', 'main_lang.php'),
( 'gujarati', 'number_of_decimal', 'દશાંશ સ્થાન', 'main_lang.php'),
( 'gujarati', 'no_image_for_comparision', 'તુલના માટે કોઈ છબીઓ પસંદ નથી', 'main_lang.php'),
( 'gujarati', 'on', 'ચાલુ', 'main_lang.php'),
( 'gujarati', 'our', 'અમારું', 'main_lang.php'),
( 'gujarati', 'our_team', 'અમારી ટીમ', 'main_lang.php'),
( 'gujarati', 'our_services', 'અમારી સેવાઓ', 'main_lang.php'),
( 'gujarati', 'office', 'ઓફિસ', 'main_lang.php'),
( 'gujarati', 'office_branch', 'ઓફિસ શાખા', 'main_lang.php'),
( 'gujarati', 'old_password', 'જુનો પાસવર્ડ', 'main_lang.php'),
( 'gujarati', 'opening', 'ખુલે છે', 'main_lang.php'),
( 'gujarati', 'option', 'વિકલ્પ', 'main_lang.php'),
( 'gujarati', 'opening_stock', 'શેર ખુલે છે', 'main_lang.php'),
( 'gujarati', 'other', 'અન્ય', 'main_lang.php'),
( 'gujarati', 'paid', 'ચૂકવેલ', 'main_lang.php'),
( 'gujarati', 'of_appoinment_time', 'નિમણૂક સમય', 'main_lang.php'),
( 'gujarati', 'paid_cash', 'ચૂકવણી કેશ', 'main_lang.php'),
( 'gujarati', 'page_title', 'પૃષ્ઠ શીર્ષક', 'main_lang.php'),
( 'gujarati', 'paid_amount', 'ચુકવેલ રકમ', 'main_lang.php'),
( 'gujarati', 'parent', 'માતાપિતા', 'main_lang.php'),
( 'gujarati', 'particular', 'ખાસ', 'main_lang.php'),
( 'gujarati', 'password', 'પાસવર્ડ', 'main_lang.php'),
( 'gujarati', 'patient', 'દર્દી', 'main_lang.php'),
( 'gujarati', 'patient_details', 'દર્દીની વિગતો', 'main_lang.php'),
( 'gujarati', 'patient_account', 'પેશન્ટ એકાઉન્ટ', 'main_lang.php'),
( 'gujarati', 'patient_detail', 'દર્દીની વિગત', 'main_lang.php'),
( 'gujarati', 'patients', 'દર્દીઓ', 'main_lang.php'),
( 'gujarati', 'patient_id', 'દર્દી આઈડી', 'main_lang.php'),
( 'gujarati', 'patient_name', 'દર્દીનું નામ', 'main_lang.php'),
( 'gujarati', 'patient_notes', 'દર્દી નોંધો', 'main_lang.php'),
( 'gujarati', 'patient_report', 'દર્દી રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'patient_added_after', 'દર્દી પછી ઉમેર્યા', 'main_lang.php'),
( 'gujarati', 'patient_wise_alert_settings', 'દર્દી મુજબની ચેતવણી સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'payment', 'ચુકવણી', 'main_lang.php'),
( 'gujarati', 'payments', 'ચુકવણીઓ', 'main_lang.php'),
( 'gujarati', 'payment_methods', 'ચુકવણી પદ્ધતિઓ', 'main_lang.php'),
( 'gujarati', 'payment_form', 'ચુકવણી ફોર્મ', 'main_lang.php'),
( 'gujarati', 'payment_amount', 'ચુકવણી રકમ', 'main_lang.php'),
( 'gujarati', 'payment_adjustement', 'ચુકવણી ગોઠવણ', 'main_lang.php'),
( 'gujarati', 'payment_date', 'ચુકવણી તારીખ', 'main_lang.php'),
( 'gujarati', 'payment_mode', 'ચુકવણી સ્થિતિ', 'main_lang.php'),
( 'gujarati', 'payment_method', 'ચુકવણી પદ્ધતિ', 'main_lang.php'),
( 'gujarati', 'payment_history', 'ચૂકવણીનો ઇતિહાસ', 'main_lang.php'),
( 'gujarati', 'payment_status', 'ચુકવણી સ્થિતિ', 'main_lang.php'),
( 'gujarati', 'paypal_settings', 'PayPal સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'paypal_business_email', 'PayPal વ્યાપાર ઇમેઇલ', 'main_lang.php'),
( 'gujarati', 'pending', 'બાકી', 'main_lang.php'),
( 'gujarati', 'per_bed_charge', 'બેડ દીઠ ચાર્જ', 'main_lang.php'),
( 'gujarati', 'pending_payments', 'બાકી ચુકવણીઓ', 'main_lang.php'),
( 'gujarati', 'per_hour', 'કલાક દીઠ', 'main_lang.php'),
( 'gujarati', 'per_day', 'દિવસ દીઠ', 'main_lang.php'),
( 'gujarati', 'phone_number', 'ફોન નંબર', 'main_lang.php'),
( 'gujarati', 'placeholder', 'પ્લેસહોલ્ડર', 'main_lang.php'),
( 'gujarati', 'post', 'પોસ્ટ', 'main_lang.php'),
( 'gujarati', 'posts', 'પોસ્ટ્સ', 'main_lang.php'),
( 'gujarati', 'postal_code', 'પોસ્ટ કોડ', 'main_lang.php'),
( 'gujarati', 'post_title', 'પોસ્ટશીર્ષક', 'main_lang.php'),
( 'gujarati', 'post_content', 'પોસ્ટ સામગ્રી', 'main_lang.php'),
( 'gujarati', 'post_type', 'પોસ્ટ પ્રકાર', 'main_lang.php'),
( 'gujarati', 'print', 'પ્રિંટ', 'main_lang.php'),
( 'gujarati', 'print_receipt', 'પ્રિંટ રસીદ', 'main_lang.php'),
( 'gujarati', 'progress', 'પ્રગતિ', 'main_lang.php'),
( 'gujarati', 'profile', 'પ્રોફાઇલ', 'main_lang.php'),
( 'gujarati', 'prev_bal', 'અગાઉનુ બેલેન્સ', 'main_lang.php'),
( 'gujarati', 'prev_due', 'અગાઉના કારણે', 'main_lang.php'),
( 'gujarati', 'preferred_size', 'પ્રિફર્ડ કદ 260x60', 'main_lang.php'),
( 'gujarati', 'price', 'ભાવ', 'main_lang.php'),
( 'gujarati', 'print_report', 'પ્રિંટ રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'prescription', 'પ્રિસ્ક્રિપ્શન', 'main_lang.php'),
( 'gujarati', 'preferences', 'પસંદગીઓ', 'main_lang.php'),
( 'gujarati', 'purchase', 'ખરીદી', 'main_lang.php'),
( 'gujarati', 'purchase_date', 'ખરીદીની તારીખ', 'main_lang.php'),
( 'gujarati', 'purchase_return', 'ખરીદી રીટર્ન', 'main_lang.php'),
( 'gujarati', 'purchase_register', 'ખરીદી રજીસ્ટર', 'main_lang.php'),
( 'gujarati', 'promocode', 'પ્રોમોકૉડ', 'main_lang.php'),
( 'gujarati', 'promocodes', 'પ્રોમો કોડ', 'main_lang.php'),
( 'gujarati', 'pending_appointments', 'બાકી નિમણૂંક', 'main_lang.php'),
( 'gujarati', 'pending_payment', 'બાકી ચુકવણી', 'main_lang.php'),
( 'gujarati', 'percentage', 'ટકાવારી', 'main_lang.php'),
( 'gujarati', 'planned_appointment', 'આ નિમણૂંક એક આયોજિત સત્ર છે', 'main_lang.php'),
( 'gujarati', 'planned_visit', 'આ મુલાકાત એક આયોજિત સત્ર છે', 'main_lang.php'),
( 'gujarati', 'planned_sessions', 'આયોજન સત્રો', 'main_lang.php'),
( 'gujarati', 'payment_pending', 'માન્યતા સુધી પેમેન્ટ બાકી રાખો', 'main_lang.php'),
( 'gujarati', 'phone', 'ફોન', 'main_lang.php'),
( 'gujarati', 'pay', 'પે', 'main_lang.php'),
( 'gujarati', 'paypal', 'PayPal', 'main_lang.php'),
( 'gujarati', 'prescribed_medicine', 'નિયત દવા', 'main_lang.php'),
( 'gujarati', 'prefered_language', 'પ્રાધાન્યવાળી ભાષા', 'main_lang.php'),
( 'gujarati', 'quantity', 'જથ્થો', 'main_lang.php'),
( 'gujarati', 'qrcode', 'QRcode', 'main_lang.php'),
( 'gujarati', 'fixed', 'ચોક્કસ', 'main_lang.php'),
( 'gujarati', 'variable', 'ચલ', 'main_lang.php'),
( 'gujarati', 'decimal_places', 'દશાંશ સ્થાનો', 'main_lang.php'),
( 'gujarati', 'rate', 'દર', 'main_lang.php'),
( 'gujarati', 'reason', 'કારણ', 'main_lang.php'),
( 'gujarati', 'in', 'માં', 'main_lang.php'),
( 'gujarati', 'response', 'પ્રતિભાવ', 'main_lang.php'),
( 'gujarati', 'receipt', 'રસીદ', 'main_lang.php'),
( 'gujarati', 'rebrand', 'રિબ્રાન્ડ', 'main_lang.php'),
( 'gujarati', 'receipt_template', 'રસીદ નમૂનાઓ', 'main_lang.php'),
( 'gujarati', 'reference_by', 'સંદર્ભ દ્વારા', 'main_lang.php'),
( 'gujarati', 'refund', 'પરત કરેલી રકમ', 'main_lang.php'),
( 'gujarati', 'reports', 'અહેવાલ', 'main_lang.php'),
( 'gujarati', 'restore', 'પુનઃસ્થાપિત', 'main_lang.php'),
( 'gujarati', 'report', 'રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'reset_password', 'પાસવર્ડ ફરીથી સેટ કરો', 'main_lang.php'),
( 'gujarati', 'remark', 'રીમાર્ક', 'main_lang.php'),
( 'gujarati', 'remove_logo', 'લોગો દૂર કરો', 'main_lang.php'),
( 'gujarati', 'remove', 'દૂર કરો', 'main_lang.php'),
( 'gujarati', 'renew_license', 'લાયસન્સનું નવીકરણ કરો', 'main_lang.php'),
( 'gujarati', 'remove_patient_image', 'પેશન્ટ છબી દૂર કરો', 'main_lang.php'),
( 'gujarati', 'renew_license_to_update', 'અપડેટ કરવા માટે લાઇસેંસનું નવીકરણ કરો', 'main_lang.php'),
( 'gujarati', 'receive_fee', 'પ્રોફેશનલ સેવાઓ અને અમારા અન્ય ચાર્જીસ માટે ફી પ્રાપ્ત', 'main_lang.php'),
( 'gujarati', 'quantity_exceeds', 'જરૂરી જથ્થો ઉપલબ્ધ સંગ્રહ કરતાં વધારે છે', 'main_lang.php'),
( 'gujarati', 'room', 'રૂમ', 'main_lang.php'),
( 'gujarati', 'rooms', 'રૂમ', 'main_lang.php'),
( 'gujarati', 'rooms_categories', 'રૂમ શ્રેણીઓ', 'main_lang.php'),
( 'gujarati', 'rooms_calendar', 'રૂમ કૅલેન્ડર', 'main_lang.php'),
( 'gujarati', 'rooms_allocate', 'રૂમ ફાળવણી', 'main_lang.php'),
( 'gujarati', 'rooms_beds', 'રૂમ / બેડ્સ ', 'main_lang.php'),
( 'gujarati', 'register', 'નોંધણી કરો', 'main_lang.php'),
( 'gujarati', 'registration', 'નોંધણી', 'main_lang.php'),
( 'gujarati', 'reference_details', 'સંદર્ભ વિગતો', 'main_lang.php'),
( 'gujarati', 'resend_code', 'કોડ ફરીથી મોકલો', 'main_lang.php'),
( 'gujarati', 'residence', 'નિવાસ', 'main_lang.php'),
( 'gujarati', 'restore_backup', 'બેકઅપ પુનઃસ્થાપિત કરો', 'main_lang.php'),
( 'gujarati', 'return', 'પાછા આવો', 'main_lang.php'),
( 'gujarati', 'return_change', 'રીટર્ન ચેન્જ', 'main_lang.php'),
( 'gujarati', 'return_date', 'રીટર્ન તારીખ', 'main_lang.php'),
( 'gujarati', 'room_number', 'ઓરડા ક્રમાંક', 'main_lang.php'),
( 'gujarati', 'room_charges', 'રૂમ ચાર્જિસ રિપોર્ટ્સ', 'main_lang.php'),
( 'gujarati', 'refund_amount', 'પરત કરવાની રકમ', 'main_lang.php'),
( 'gujarati', 'refund_date', 'રિફંડ તારીખ', 'main_lang.php'),
( 'gujarati', 'refund_note', 'રીફંડ નોટ', 'main_lang.php'),
( 'gujarati', 'refresh', 'તાજું કરો', 'main_lang.php'),
( 'gujarati', 'required_quantity', 'આવશ્યક જથ્થો', 'main_lang.php'),
( 'gujarati', 'reason_for_appointment', 'નિમણૂંક માટેનું કારણ', 'main_lang.php'),
( 'gujarati', 'reject', ' નામંજૂર', 'main_lang.php'),
( 'gujarati', 'rtl', 'RTL', 'main_lang.php'),
( 'gujarati', 'right_to_left', 'જમણે થી ડાબે ભાષા', 'main_lang.php'),
( 'gujarati', 'reload_language_file_instruction', 'આ ભાષા ફાઇલમાંથી થતા ફેરફારો પર ફરીથી લખાશે.', 'main_lang.php'),
( 'gujarati', 'reload_language_file', 'ભાષા ફાઇલ ફરીથી લોડ કરો', 'main_lang.php'),
( 'gujarati', 'slider_image', 'સ્લાઇડર ચિત્ર', 'main_lang.php'),
( 'gujarati', 'sign_up', 'સાઇન અપ કરો', 'main_lang.php'),
( 'gujarati', 'slider_1', 'સ્લાઇડર 1', 'main_lang.php'),
( 'gujarati', 'slider_2', 'સ્લાઇડર 2', 'main_lang.php'),
( 'gujarati', 'slider_3', 'સ્લાઇડર 3', 'main_lang.php'),
( 'gujarati', 'slider', 'સ્લાઇડર', 'main_lang.php'),
( 'gujarati', 'section', 'વિભાગ', 'main_lang.php'),
( 'gujarati', 'section_3', 'વિભાગ 3', 'main_lang.php'),
( 'gujarati', 'section_2', 'વિભાગ 2', 'main_lang.php'),
( 'gujarati', 'section_1', 'વિભાગ 1', 'main_lang.php'),
( 'gujarati', 'section_4', 'વિભાગ 4', 'main_lang.php'),
( 'gujarati', 'section_name', 'વિભાગનું નામ', 'main_lang.php'),
( 'gujarati', 'senderid', 'પ્રેષક ID', 'main_lang.php'),
( 'gujarati', 'save', 'સાચવો', 'main_lang.php'),
( 'gujarati', 'schedule', 'સૂચિ', 'main_lang.php'),
( 'gujarati', 'search', 'શોધ', 'main_lang.php'),
( 'gujarati', 'search_by_name', 'નામ દ્વારા શોધો', 'main_lang.php'),
( 'gujarati', 'second_number', 'બીજું સંખ્યા', 'main_lang.php'),
( 'gujarati', 'select', 'પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_lang', 'તમારી ભાષા પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_currency', 'ચલણ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_date', 'તારીખ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_duration', 'સમયગાળો પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_media_image', 'મીડિયા ચિત્ર પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_time_zone', 'તમારા ટાઈમઝોન પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_all', 'બધા પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_mode', 'મોડ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'sell', 'વેચાણ', 'main_lang.php'),
( 'gujarati', 'subject', 'વિષય', 'main_lang.php'),
( 'gujarati', 'select_blood_group', 'બ્લડ ગ્રુપ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'shortcode_label', 'તમારે વાપરવા માટે જરૂરી શૉર્ટકોડ્સ:', 'main_lang.php'),
( 'gujarati', 'shortcode_patient_name', '[patient_name] - દર્દીનું નામ', 'main_lang.php'),
( 'gujarati', 'shortcode_patient_id', '[patient_id] - પેશન્ટ આઈ.ડી.', 'main_lang.php'),
( 'gujarati', 'shortcode_clinic_name', '[clinic_name] - ક્લિનિક નામ', 'main_lang.php'),
( 'gujarati', 'shortcode_clinic_logo', '[clinic_logo] - ક્લિનિક લોગો - ક્લિનિક વિગતોમાં સેટ કરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'shortcode_clinic_address', '[clinic_address] - ક્લિનિક સરનામું - ક્લિનિક વિગતોમાં સેટ કરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'shortcode_clinic_landline', '[landline] - લેન્ડલાઇન - ક્લિનિક વિગતોમાં સેટ કરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'shortcode_clinic_mobile', '[mobile] - મોબાઇલ - ક્લિનિક વિગતોમાં સેટ કરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'shortcode_tag_line', '[tag_line] - ટેગલાઇન - ક્લિનિક વિગતોમાં સેટ કરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'shortcode_doctor_name', '[doctor_name] - ડોક્ટર નામ', 'main_lang.php'),
( 'gujarati', 'shortcode_dose_time', '[dose_time] - મોર્નિંગ | મંગળવારે | બુધવાર', 'main_lang.php'),
( 'gujarati', 'shortcode_clinic_email', '[email] - ઇમેઇલ - ક્લિનિક વિગતોમાં સેટ કરી શકાય છે', 'main_lang.php'),
( 'gujarati', 'shortcode_medicine_details', '[medicine_details] - ટેબલ ફોર્મેટમાં તમામ તબીબી વિગતો', 'main_lang.php'),
( 'gujarati', 'shortcode_sms_medicine_details', '[sms_medicine_details] - ટેબલ ફોર્મેટમાં તમામ તબીબી વિગતો', 'main_lang.php'),
( 'gujarati', 'shortcode_appointment_time', '[appointment_time] - નિમણૂંક સમય', 'main_lang.php'),
( 'gujarati', 'shortcode_appointment_date', '[appointment_date] - નિમણૂંક તારીખ', 'main_lang.php'),
( 'gujarati', 'shortcode_appointment_status', '[appointment_status] - નિમણૂક સ્થિતિ', 'main_lang.php'),
( 'gujarati', 'shortcode_bill', '[bill] - બિલની સોફ્ટ કૉપિ', 'main_lang.php'),
( 'gujarati', 'shortcode_appointment_reason', '[appointment_reason] - નિમણૂક કારણ', 'main_lang.php'),
( 'gujarati', 'shortcode_bill_date', '[bill_date] - બિલની તારીખ', 'main_lang.php'),
( 'gujarati', 'shortcode_bill_id', '[bill_id] - બિલ આઈડી', 'main_lang.php'),
( 'gujarati', 'shortcode_bill_time', '[bill_time] - બિલનો સમય', 'main_lang.php'),
( 'gujarati', 'shortcode_patient_email', '[patient_email] - ઇમેઇલ આઈડી', 'main_lang.php'),
( 'gujarati', 'shortcode_patient_age', '[age] - દર્દીની ઉંમર', 'main_lang.php'),
( 'gujarati', 'shortcode_patient_sex', '[sex] - પેશન્ટ સેક્સ', 'main_lang.php'),
( 'gujarati', 'shortcode_visit_date', '[visit_date] - મુલાકાત તારીખ', 'main_lang.php'),
( 'gujarati', 'shortcode_total', '[total] - આ બિલનો કુલ', 'main_lang.php'),
( 'gujarati', 'shortcode_previous_due', '[previous_due] - પાછલા બાકી લેણાં', 'main_lang.php'),
( 'gujarati', 'shortcode_paid_amount', '[paid_amount] - ચૂકવેલ રકમ', 'main_lang.php'),
( 'gujarati', 'shortcode_username', '[username] - વપરાશકર્તા નામ દ્વારા બદલવામાં આવશે', 'main_lang.php'),
( 'gujarati', 'shortcode_patient_phone_number', '[patient_phone_number] - ફોન નંબર', 'main_lang.php'),
( 'gujarati', 'shortcode_password', '[password] - પાસવર્ડ દ્વારા બદલવામાં આવશે', 'main_lang.php'),
( 'gujarati', 'shortcode_senderid', '[senderid] - પ્રેષક ID દ્વારા બદલવામાં આવશે', 'main_lang.php'),
( 'gujarati', 'shortcode_message', '[message] - સંદેશ દ્વારા બદલવામાં આવશે', 'main_lang.php'),
( 'gujarati', 'shortcode_template_id', '[template_id] - ઢાંચો ID દ્વારા બદલવામાં આવશે', 'main_lang.php'),
( 'gujarati', 'shortcode_mobileno', '[mobileno] - પ્રાપ્તકર્તા મોબાઇલ નંબર દ્વારા બદલવામાં આવશે', 'main_lang.php'),
( 'gujarati', 'shortcode_bill_columns', 'કોલમમાં બિલ માટે કોષ્ટકમાં પ્રદર્શિત કરવા', 'main_lang.php'),
( 'gujarati', 'share_type', 'શેર પ્રકાર', 'main_lang.php'),
( 'gujarati', 'shortcode_prescription_columns', 'પ્રિસ્ક્રિપ્શન માટે કોષ્ટકમાં પ્રદર્શિત કરવા માટે કૉલમ', 'main_lang.php'),
( 'gujarati', 'sms_settings', 'એસએમએસ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'services_settings', 'સેવાઓ સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'smtp_instructions', 'ફક્ત SMTP ઇમેઇલ્સ મોકલવા માટે આવશ્યક ', 'main_lang.php'),
( 'gujarati', 'set', 'સેટ કરો', 'main_lang.php'),
( 'gujarati', 'stock_sell', 'વેચો', 'main_lang.php'),
( 'gujarati', 'sell_id', 'વેચાણ આઈડી', 'main_lang.php'),
( 'gujarati', 'sell_amount', 'વેચાણ રકમ', 'main_lang.php'),
( 'gujarati', 'sell_date', 'વેચાણ તારીખ', 'main_lang.php'),
( 'gujarati', 'sell_price', 'વેચાણ ભાવ', 'main_lang.php'),
( 'gujarati', 'set_as_default', 'મૂળભૂત તરીકે સેટ કરો', 'main_lang.php'),
( 'gujarati', 'settings', 'સેટિંગ્સ', 'main_lang.php'),
( 'gujarati', 'services', 'સેવાઓ', 'main_lang.php'),
( 'gujarati', 'service', 'સેવા', 'main_lang.php'),
( 'gujarati', 'services_type', 'સેવાઓ પ્રકાર', 'main_lang.php'),
( 'gujarati', 'session', 'સત્ર', 'main_lang.php'),
( 'gujarati', 'sessions', 'સત્રો', 'main_lang.php'),
( 'gujarati', 'session_report', 'સત્ર અહેવાલ', 'main_lang.php'),
( 'gujarati', 'setting', 'સેટિંગ', 'main_lang.php'),
( 'gujarati', 'signature', 'હસ્તાક્ષર', 'main_lang.php'),
( 'gujarati', 'software_name', 'સોફ્ટવેર નામ', 'main_lang.php'),
( 'gujarati', 'sold_at', 'પર વેચવામાં', 'main_lang.php'),
( 'gujarati', 'sold_avg', 'સરેરાશ વેચાણ', 'main_lang.php'),
( 'gujarati', 'special_access', 'વિશેષ ઍક્સેસ', 'main_lang.php'),
( 'gujarati', 'sold_quantity', 'વેચાઈ જથ્થો', 'main_lang.php'),
( 'gujarati', 'specialization', 'ખાસ', 'main_lang.php'),
( 'gujarati', 'sr_no', 'ક્રમ નં.', 'main_lang.php'),
( 'gujarati', 'staff', 'સ્ટાફ', 'main_lang.php'),
( 'gujarati', 'state', 'રાજ્ય', 'main_lang.php'),
( 'gujarati', 'start_date', 'પ્રારંભ તારીખ', 'main_lang.php'),
( 'gujarati', 'start_time', 'પ્રારંભ સમય', 'main_lang.php'),
( 'gujarati', 'status', 'સ્થિતિ', 'main_lang.php'),
( 'gujarati', 'static_prefix', 'સ્થિર પ્રેફિક્ષ', 'main_lang.php'),
( 'gujarati', 'stock_item', 'આઇટમ', 'main_lang.php'),
( 'gujarati', 'stock_stock_report', 'સ્ટોક રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'stock', 'સ્ટોક', 'main_lang.php'),
( 'gujarati', 'stock_report', 'અહેવાલ', 'main_lang.php'),
( 'gujarati', 'submit', 'સબમિટ', 'main_lang.php'),
( 'gujarati', 'sub_total', 'સબ ટોટલ ', 'main_lang.php'),
( 'gujarati', 'supplier', 'સપ્લાયર ', 'main_lang.php'),
( 'gujarati', 'suppliers', 'સપ્લાયરો ', 'main_lang.php'),
( 'gujarati', 'stock_suppliers', 'સપ્લાયર્સ', 'main_lang.php'),
( 'gujarati', 'stock_purchase_report', 'ખરીદી રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'stock_purchase', 'ખરીદી', 'main_lang.php'),
( 'gujarati', 'supplier_name', 'સપ્લાયરનું નામ', 'main_lang.php'),
( 'gujarati', 'support_text', 'આધાર લખાણ', 'main_lang.php'),
( 'gujarati', 'support', 'સપોર્ટ', 'main_lang.php'),
( 'gujarati', 'support_url', 'સપોર્ટ URL', 'main_lang.php'),
( 'gujarati', 'select_doctor', 'ડૉક્ટર ને પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_beautician', 'ડૉક્ટર ને પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_patient', 'પેશન્ટ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_fields', 'ક્ષેત્રો પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_tax_rate', 'કર દર પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'select_a_Slot', 'જગ્યા પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'sell_return', 'રીટર્ન વેચો', 'main_lang.php'),
( 'gujarati', 'stock_sell_report', 'તમામ સેલ રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'synchronize', 'સિંક્રનાઇઝ કરો', 'main_lang.php'),
( 'gujarati', 'total_sell_report', 'કુલ વેચાણ રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'sms_url', 'એસએમએસ મોકલવા માટે URL', 'main_lang.php'),
( 'gujarati', 'smtp_host', 'SMTP હોસ્ટ', 'main_lang.php'),
( 'gujarati', 'smtp_port', 'SMTP પોર્ટ', 'main_lang.php'),
( 'gujarati', 'sms_alert_time', 'એસએમએસ ચેતવણી સમય', 'main_lang.php'),
( 'gujarati', 'sms_format', 'એસએમએસ ફોર્મેટ', 'main_lang.php'),
( 'gujarati', 'sms_template_id', 'એસએમએસ ટેમ્પ્લેટ ID', 'main_lang.php'),
( 'gujarati', 'sms_log', 'એસએમએસ લોગ', 'main_lang.php'),
( 'gujarati', 'save_and_bill', 'સેવ અને બિલ બનાવો', 'main_lang.php'),
( 'gujarati', 'ssn_id', 'આધાર નંબર', 'main_lang.php'),
( 'gujarati', 'set_alert_time', 'ચેતવણી ચેતવણી સેટ કરો', 'main_lang.php'),
( 'gujarati', 'save_complete', 'સાચવો અને પૂર્ણ કરો', 'main_lang.php'),
( 'gujarati', 'slot', 'સ્લોટ', 'main_lang.php'),
( 'gujarati', 'to', 'માટે', 'main_lang.php'),
( 'gujarati', 'take_backup', 'બેકઅપ લો', 'main_lang.php'),
( 'gujarati', 'tag_line', 'ટેગ લાઇન', 'main_lang.php'),
( 'gujarati', 'total_appointments', 'કુલ નિમણૂંક', 'main_lang.php'),
( 'gujarati', 'task', 'કાર્ય', 'main_lang.php'),
( 'gujarati', 'tasks', 'કાર્યો', 'main_lang.php'),
( 'gujarati', 'tax', 'કર', 'main_lang.php'),
( 'gujarati', 'tax_amount', 'કર રકમ', 'main_lang.php'),
( 'gujarati', 'tax_revenue', 'કરવેરા મહેસૂલ', 'main_lang.php'),
( 'gujarati', 'taxable', 'કરપાત્ર', 'main_lang.php'),
( 'gujarati', 'taxable_revenue', 'કરપાત્ર આવક', 'main_lang.php'),
( 'gujarati', 'tax_rates', 'કર દર', 'main_lang.php'),
( 'gujarati', 'tax_report', 'કર રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'tax_rate', 'કર દર', 'main_lang.php'),
( 'gujarati', 'template_name', 'ટેમ્પલેટ નામ', 'main_lang.php'),
( 'gujarati', 'template_content', 'ટેમ્પ્લેટ કન્ટેન્ટ ', 'main_lang.php'),
( 'gujarati', 'thanks', 'આભાર સાથે પ્રાપ્ત', 'main_lang.php'),
( 'gujarati', 'time', 'સમય', 'main_lang.php'),
( 'gujarati', 'test', 'પરીક્ષણ', 'main_lang.php'),
( 'gujarati', 'timings', 'સમય', 'main_lang.php'),
( 'gujarati', 'timestamp', 'ટાઇમસ્ટેમ્પ', 'main_lang.php'),
( 'gujarati', 'time_format', 'સમય ફોર્મેટ', 'main_lang.php'),
( 'gujarati', 'time_zone', 'સમય ઝોન', 'main_lang.php'),
( 'gujarati', 'time_interval', 'સમય અંતરાલ', 'main_lang.php'),
( 'gujarati', 'title', 'શીર્ષક', 'main_lang.php'),
( 'gujarati', 'to_admin_panel', ' એડમિન પેનલ પર', 'main_lang.php'),
( 'gujarati', 'to_date', 'આજ સુધી', 'main_lang.php'),
( 'gujarati', 'to_be_paid', 'ચૂકવણી કરવામાં', 'main_lang.php'),
( 'gujarati', 'total', 'કુલ', 'main_lang.php'),
( 'gujarati', 'total_due_after_payment', 'ચુકવણી પછી કુલ રકમ', 'main_lang.php'),
( 'gujarati', 'transport', 'ટ્રાન્સપોર્ટ', 'main_lang.php'),
( 'gujarati', 'treatment', 'સારવાર', 'main_lang.php'),
( 'gujarati', 'treatment_report', 'સારવાર રિપોર્ટ', 'main_lang.php'),
( 'gujarati', 'treatments', 'સારવારો ', 'main_lang.php'),
( 'gujarati', 'treatment_name', 'સારવાર નામ', 'main_lang.php'),
( 'gujarati', 'treatment_charges', 'સારવાર ચાર્જિસ /ફી', 'main_lang.php'),
( 'gujarati', 'type', 'પ્રકાર', 'main_lang.php'),
( 'gujarati', 'twitter', 'ટ્વીટર', 'main_lang.php'),
( 'gujarati', 'twitter_link', 'ટ્વિટર લિંક', 'main_lang.php'),
( 'gujarati', 'theme', 'થીમ', 'main_lang.php'),
( 'gujarati', 'txn_id', 'TXN ID', 'main_lang.php'),
( 'gujarati', 'tax_rate_name', 'કર દર નામ', 'main_lang.php'),
( 'gujarati', 'test_name', 'પરીક્ષણ નામ', 'main_lang.php'),
( 'gujarati', 'tests', 'પરીક્ષણ', 'main_lang.php'),
( 'gujarati', 'text', 'ટેક્સ્ટ', 'main_lang.php'),
( 'gujarati', 'top_section_1', 'ટોચ વિભાગ 1', 'main_lang.php'),
( 'gujarati', 'top_section_2', 'ટોચ વિભાગ 2', 'main_lang.php'),
( 'gujarati', 'top_section_3', 'ટોચ વિભાગ 3', 'main_lang.php'),
( 'gujarati', 'this_payment_is_rejected', 'આ ચુકવણી નકારવામાં આવે છે', 'main_lang.php'),
( 'gujarati', 'thousands_separator', 'હજારો વિભાજક', 'main_lang.php'),
( 'gujarati', 'types', 'પ્રકારો', 'main_lang.php'),
( 'gujarati', 'upload', 'અપલોડ કરો', 'main_lang.php'),
( 'gujarati', 'upload_extension', 'અપલોડ એક્સ્ટેન્શન્સ', 'main_lang.php'),
( 'gujarati', 'update', 'અપડેટ', 'main_lang.php'),
( 'gujarati', 'updates', 'અપડેટ્સ', 'main_lang.php'),
( 'gujarati', 'update_now', 'હમણાં અપડેટ કરો', 'main_lang.php'),
( 'gujarati', 'username', 'વપરાશકર્તા નામ', 'main_lang.php'),
( 'gujarati', 'user', 'વપરાશકર્તા', 'main_lang.php'),
( 'gujarati', 'url', 'URL', 'main_lang.php'),
( 'gujarati', 'users', 'વપરાશકર્તાઓ', 'main_lang.php'),
( 'gujarati', 'using', 'નો ઉપયોગ', 'main_lang.php'),
( 'gujarati', 'upcoming_appointments', 'આગામી નિમણૂંક', 'main_lang.php'),
( 'gujarati', 'unpacking_zip_package', 'અનપેકિંગ ઝિપ પેકેજ', 'main_lang.php'),
( 'gujarati', 'upload_language_file', 'હાલની ભાષા ફાઇલ અપલોડ કરો', 'main_lang.php'),
( 'gujarati', 'vaccine', 'રસી', 'main_lang.php'),
( 'gujarati', 'vaccines', 'રસીઓ', 'main_lang.php'),
( 'gujarati', 'vaccine_master', 'રસીકરણ', 'main_lang.php'),
( 'gujarati', 'vaccine_name', 'રસી નામ', 'main_lang.php'),
( 'gujarati', 'view', 'જુઓ', 'main_lang.php'),
( 'gujarati', 'viewed', 'જોઈ', 'main_lang.php'),
( 'gujarati', 'visit', 'મુલાકાત', 'main_lang.php'),
( 'gujarati', 'visit_date', 'મુલાકાતની તારીખ', 'main_lang.php'),
( 'gujarati', 'visit_time', 'સમયની મુલાકાત લો', 'main_lang.php'),
( 'gujarati', 'visit_type', 'પ્રકાર ની મુલાકાત લો', 'main_lang.php'),
( 'gujarati', 'visits', 'મુલાકાતો', 'main_lang.php'),
( 'gujarati', 'verify', 'ચકાસો', 'main_lang.php'),
( 'gujarati', 'verification_code', 'ચકાસણી કોડ', 'main_lang.php'),
( 'gujarati', 'version', 'આવૃત્તિ', 'main_lang.php'),
( 'gujarati', 'verify_email', 'ઇમેઇલ ચકાસો', 'main_lang.php'),
( 'gujarati', 'voucher_no', 'વાઉચર નં.', 'main_lang.php'),
( 'gujarati', 'voucher_date', 'વાઉચર તારીખ', 'main_lang.php'),
( 'gujarati', 'view_larger_map', 'મોટો નકશો જુઓ', 'main_lang.php'),
( 'gujarati', 'value', 'મૂલ્ય', 'main_lang.php'),
( 'gujarati', 'view_prescription', 'પ્રિસ્ક્રિપ્શન જુઓ', 'main_lang.php'),
( 'gujarati', 'visit_report', 'તબીબી ઇતિહાસ અહેવાલ', 'main_lang.php'),
( 'gujarati', 'waiting', 'રાહ ', 'main_lang.php'),
( 'gujarati', 'waiting_in', 'માં પ્રતીક્ષામાં છે', 'main_lang.php'),
( 'gujarati', 'welcome', 'સ્વાગત', 'main_lang.php'),
( 'gujarati', 'whole_day', 'આખો દિવસ', 'main_lang.php'),
( 'gujarati', 'website', 'વેબસાઇટ', 'main_lang.php'),
( 'gujarati', 'working', 'કાર્યરત', 'main_lang.php'),
( 'gujarati', 'working_days', 'કાર્યકારી દિવસો', 'main_lang.php'),
( 'gujarati', 'website_text', 'વેબસાઇટ ટેક્સ્ટ', 'main_lang.php'),
( 'gujarati', 'website_url', 'વેબપૃષ્ઠ URL', 'main_lang.php'),
( 'gujarati', 'working_key', 'કામ કરતી કી', 'main_lang.php'),
( 'gujarati', 'non_working', 'આ નોન વર્કિંગ ડે છે', 'main_lang.php'),
( 'gujarati', 'we_provide', 'અમે આપીશું', 'main_lang.php'),
( 'gujarati', 'sunday', 'રવિવાર', 'main_lang.php'),
( 'gujarati', 'year', 'વર્ષ', 'main_lang.php'),
( 'gujarati', 'monday', 'સોમવાર', 'main_lang.php'),
( 'gujarati', 'tuesday', 'મંગળવાર', 'main_lang.php'),
( 'gujarati', 'wednesday', 'બુધવાર', 'main_lang.php'),
( 'gujarati', 'friday', 'શુક્રવાર', 'main_lang.php'),
( 'gujarati', 'thursday', 'ગુરુવાર', 'main_lang.php'),
( 'gujarati', 'saturday', 'શનિવાર', 'main_lang.php'),
( 'gujarati', 'your_username', 'તમારું વપરાશકર્તા નામ', 'main_lang.php'),
( 'gujarati', 'your_password', 'તમારો પાસવર્ડ', 'main_lang.php'),
( 'gujarati', 'room_numbers_for', 'માટે રૂમ નંબર્સ', 'main_lang.php'),
( 'gujarati', 'aplha_space', '% S ફીલ્ડમાં ફક્ત આલ્ફા અક્ષરો અને વ્હાઇટ સ્પેસ હોઈ શકે છે', 'main_lang.php'),
( 'gujarati', 'first_or_last', 'કૃપા કરી પ્રથમ નામ અથવા છેલ્લું નામ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'password_not_match', 'જૂના પાસવર્ડ મેળ ખાતો નથી', 'main_lang.php'),
( 'gujarati', 'irreversible_process', 'આ એક ઉલટાવી શકાય તેવી પ્રક્રિયા છે. આનાથી ડેટા ગુમાવવાનું કારણ બની શકે છે. માહિતી પુનઃસ્થાપિત કરતા પહેલાં ખરેખર ખરેખર ખાતરી કરો', 'main_lang.php'),
( 'gujarati', 'calculation_purpose_only', '*આ ક્ષેત્રો માત્ર ગણતરી હેતુ માટે છે. ચુકવણી રકમ ક્ષેત્રમાં વાસ્તવિક ચુકવણી રકમ ઉમેરો.', 'main_lang.php'),
( 'gujarati', 'numbersof_days_between_two_appointments', 'બે એપોઇન્ટમેન્ટ્સ વચ્ચેના દિવસોના મૂળભૂત નંબરો પર તેને સેટ કરો આગલા ફોલોઅપને આપમેળે સેટ કરવાનું અક્ષમ કરવા માટે, તેને 0 પર સેટ કરો.', 'main_lang.php'),
( 'gujarati', 'clickto_toggle_display', '(ડિસ્પ્લે ટૉગલ કરવા માટે ક્લિક કરો)', 'main_lang.php'),
( 'gujarati', 'nobillsfound_for_selected_parameters', 'પસંદ કરેલ પરિમાણો માટે કોઈ બિલ મળ્યા નથી', 'main_lang.php'),
( 'gujarati', 'norecfound', 'કોઈ રેકોર્ડ મળ્યો નથી ', 'main_lang.php'),
( 'gujarati', 'areyousure', 'તમે ખાતરી કરો કે તમે કરવા માંગો છો', 'main_lang.php'),
( 'gujarati', 'areyousure_delete', 'તમે ખાતરી કરો કે તમે કાઢી નાખવા માંગો છો ?', 'main_lang.php'),
( 'gujarati', 'areyousure_approve', 'શું તમે ખરેખર મંજૂર કરવા માંગો છો?', 'main_lang.php'),
( 'gujarati', 'areyousure_reject', 'શું તમે ખરેખર નકારવા માંગો છો?', 'main_lang.php'),
( 'gujarati', 'areyousure_deactivate', 'તમે ખાતરી કરો કે તમે નિષ્ક્રિય કરવા માંગો છો?', 'main_lang.php'),
( 'gujarati', 'areyousure_cleardata', 'તમે ખાતરી કરો કે તમે ડેટા કાઢી નાખવા માંગો છો ?આ પ્રક્રિયા પૂર્વવત્ કરી શકાતું નથી!', 'main_lang.php'),
( 'gujarati', 'invalid_username', 'અમાન્ય વપરાશકર્તા નામ અને / અથવા પાસવર્ડ', 'main_lang.php'),
( 'gujarati', 'please_select', 'મહેરબાની કરી, પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'tempnote', '&nbsp;&nbsp;&nbsp;&nbsp;* હાલ ના ટેમ્પ્લેટ નું નામ બદલાસો તો તે ટેમ્પ્લેટ નહિ રેહશે. તેને બદલે તે ટેમ્પ્લેટની નવી કોપી બનાવશે. ', 'main_lang.php'),
( 'gujarati', 'jpg_format_not_allow', 'JPG ફાઇલ ફોર્મેટ માન્ય છે &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ઈમેજ સાઈજ : 800 * 800', 'main_lang.php'),
( 'gujarati', 'no_file_chosen', 'કોઈ ફાઇલ પસંદ', 'main_lang.php'),
( 'gujarati', 'no_treatment_added_add_treatment', 'કોઈ સારવાર ઉમેર્યા નથી. સારવાર ઉમેરો.', 'main_lang.php'),
( 'gujarati', 'no_vaccine_schedule_added_add_vaccine', 'કોઈ રસી શેડ્યૂલ ઉમેરાઈ નથી. રસી શેડ્યૂલ ઉમેરો.', 'main_lang.php'),
( 'gujarati', 'no_vaccine_added_add_vaccine', 'કોઈ રસીઓ ઉમેરાઈ નથી. રસી ઉમેરો.', 'main_lang.php'),
( 'gujarati', 'upload_extention_instruction', 'જો તમારી પાસે એક્સટેન્શન ઝીપ ફોર્મેટમા હોય તો તમે તેને અહી અપલોડ કરી ઇન્સ્ટોલ કરી શકો છો .', 'main_lang.php'),
( 'gujarati', 'temptext', 'ટેમ્પ્લેટ ડિરેક્ટરી નમૂનો ટેમ્પ્લેટ વાપરવા માટે લખી શકાય તેવી સુયોજિત થયેલ હોવું જ જોઈએ', 'main_lang.php'),
( 'gujarati', 'toggle_display', '(ડિસ્પ્લે ટૉગલ કરવા માટે ક્લિક કરો)', 'main_lang.php'),
( 'gujarati', 'no_visits', 'આ દર્દી માટે કોઈ મુલાકાત નથી ', 'main_lang.php'),
( 'gujarati', 'initial_password_message', 'પ્રારંભિક પાસવર્ડ વપરાશકર્તાનામ તરીકે સમાન છે', 'main_lang.php'),
( 'gujarati', 'is_active_email', '{ફીલ્ડ} સક્રિય નથી. કૃપા કરીને સંપર્ક સંચાલક કરો', 'main_lang.php'),
( 'gujarati', 'no_disease', 'કોઈ રોગ ઉમેર્યા નથી. એક રોગ ઉમેરો.', 'main_lang.php'),
( 'gujarati', 'thanks_to_amazing_works', 'ચિકિત્સા નીચેની અમેઝિંગ કામો વગર શક્ય બન્યું ન હોત.', 'main_lang.php'),
( 'gujarati', 'validate_date_or_day', 'કૃપા કરી તારીખ દાખલ કરો અથવા દિવસો પસંદ કરો.', 'main_lang.php'),
( 'gujarati', 'doctor_not_available', 'ડાક્તરઆ સમય દરમિયાન ઉપલબ્ધ નથી', 'main_lang.php'),
( 'gujarati', 'max_post_allowed', '(તમે મહત્તમ પોસ્ટ સુધી પહોંચી ગયા છો કે જે ઉમેરી શકાય છે)', 'main_lang.php'),
( 'gujarati', 'time_booked', 'આ સમય પહેલેથી જ મહત્તમ દર્દીઓ સાથે બુક થયેલ છે!', 'main_lang.php'),
( 'gujarati', 'image_for_compare', 'કૃપા કરીને તુલના માટે છબીઓ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'error_saving_image', 'છબી સાચવવાનો પ્રયાસ કરતી વખતે થોડી ભૂલ આવી.', 'main_lang.php'),
( 'gujarati', 'select_two', 'કૃપા કરીને ફક્ત બે જ પસંદ કરો', 'main_lang.php'),
( 'gujarati', 'validate_code', 'ચકાસણી કોડ યોગ્ય નથી', 'main_lang.php'),
( 'gujarati', 'save_language_instructions', '(ફક્ત ટેક્સ્ટ બદલો અને સાચવવા માટે આગળ વધો)', 'main_lang.php'),
( 'gujarati', 'reset_password_instructions', 'કૃપા કરીને તમારું વપરાશકર્તાનામ અથવા ઇમેઇલ સરનામું દાખલ કરો.તમને ઇમેઇલ દ્વારા એક નવો પાસવર્ડ બનાવવા માટે એક લિંક પ્રાપ્ત થશે.', 'main_lang.php'),
( 'gujarati', 'no_email_registered', 'તે વપરાશકર્તાનામ અથવા ઇમેઇલ સાથે કોઈ વપરાશકર્તા રજીસ્ટર નથી.', 'main_lang.php'),
( 'gujarati', 'check_confirmation_link', 'પુષ્ટિકરણ લિંક માટે તમારું ઇમેઇલ તપાસો.', 'main_lang.php'),
( 'gujarati', 'appointment_payment_success', 'તમારું ચુકવણી સફળ થયું, બુકિંગની મુલાકાત માટે આભાર.', 'main_lang.php'),
( 'gujarati', 'paypal_cancel_salutation', 'પ્રિય સભ્ય', 'main_lang.php'),
( 'gujarati', 'paypal_cancel_message', 'માફ કરશો! તમારો છેલ્લો વ્યવહાર રદ થયો હતો.', 'main_lang.php'),
( 'gujarati', 'file_missing', 'ફોલ્ડર ખૂટે છે.', 'main_lang.php'),
( 'gujarati', 'sms_username_instruction', 'એસએમએસ API પ્રદાતા દ્વારા પ્રદાન કરેલ વપરાશકર્તા નામ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'sms_password_instruction', 'એસએમએસ API પ્રદાતા દ્વારા પ્રદાન કરેલો પાસવર્ડ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'sms_senderid_instruction', 'એસએમએસ API પ્રદાતા દ્વારા પ્રદાન કરાયેલ પ્રેષક આઈડી દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'sms_countrycode_instruction', 'મોબાઇલ નંબરમાં દેશનો કોડ શામેલ કરવા માટે તેને ખાલી રાખો', 'main_lang.php'),
( 'gujarati', 'sms_url_instruction', 'એસએમએસ API પ્રદાતા દ્વારા પૂરી પાડવામાં આવેલ URL દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'updating_to_latest', 'ચિકિત્સાને નવીનતમ સંસ્કરણ પર અપડેટ કરી રહ્યું છે. <br/> આ પ્રક્રિયામાં થોડો સમય લાગી શકે છે. <br/>', 'main_lang.php'),
( 'gujarati', 'donot_close_browser', '<strong> પ્રક્રિયા પૂર્ણ થાય ત્યાં સુધી બ્રાઉઝર બંધ કરશો નહીં. </ strong> <br/>', 'main_lang.php'),
( 'gujarati', 'download_chikitsa', 'છેલ્લી ચિકિત્સા ઝિપ ડાઉનલોડ કરી રહ્યું છે ... <br/>', 'main_lang.php'),
( 'gujarati', 'no_services', 'કોઈ સેવાઓ ઉમેરાઈ નથી. એક સેવા ઉમેરો.', 'main_lang.php'),
( 'gujarati', 'unzip_file', 'ઝિપ ફાઇલને અનઝિપ કરી રહ્યું છે <br/>', 'main_lang.php'),
( 'gujarati', 'compatible_version', '%1 ની આ સંસ્કરણ સાથે સુસંગત', 'main_lang.php'),
( 'gujarati', 'extension_requires', 'આ એક્સ્ટેંશનને %1 %2 ની જરૂર છે', 'main_lang.php'),
( 'gujarati', 'please_enter_first_name', 'કૃપા કરીને પ્રથમ નામ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'please_enter_last_name', 'કૃપા કરીને છેલ્લું નામ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'please_enter_mobile_number', 'મહેરબાની કરીને મોબાઇલ નંબર દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'australian_currency', 'ઓસ્ટ્રેલિયન ડોલર (એયુડી)', 'main_lang.php'),
( 'gujarati', 'please_enter_language_name', 'ભાષા નામ દાખલ કરો', 'main_lang.php'),
( 'gujarati', 'brazilian_currency', 'બ્રાઝિલિયન રીઅલ (બીઆરએલ)', 'main_lang.php'),
( 'gujarati', 'canadian_currency', 'કેનેડિયન ડોલર (સીએડી)', 'main_lang.php'),
( 'gujarati', 'czech_currency', 'ચેક કોરુના (સીઝેડકે)', 'main_lang.php'),
( 'gujarati', 'danish_currency', 'ડેનિશ ક્રાઉન (ડીકેકે)', 'main_lang.php'),
( 'gujarati', 'euro_currency', 'યુરો (EUR)', 'main_lang.php'),
( 'gujarati', 'hong_kong_currency', 'હોંગકોંગ ડોલર (HKD)', 'main_lang.php'),
( 'gujarati', 'hungarian_currency', 'હંગેરિયન ફોરિન્ટ (એચયુએફ)', 'main_lang.php'),
( 'gujarati', 'israeli_currency', 'ઇઝરાયેલી ન્યુ શેકેલ (આઇએલએસ)', 'main_lang.php'),
( 'gujarati', 'malaysian_currency', 'મલેશિયન રીંગગિટ (MYR)', 'main_lang.php'),
( 'gujarati', 'mexican_currency', 'મેક્સીકન પેસો (એમએક્સએન)', 'main_lang.php'),
( 'gujarati', 'norwegian_currency', 'નોર્વેજિયન ક્રાઉન (NOK)', 'main_lang.php'),
( 'gujarati', 'new_zealand_currency', 'ન્યુઝિલેન્ડ ડૉલર (એનઝેડડી)', 'main_lang.php'),
( 'gujarati', 'japanese_currency', 'જાપાનીઝ યેન (જેપીવાય)', 'main_lang.php'),
( 'gujarati', 'philippine_currency', 'ફિલિપાઈન પેસો (PHP)', 'main_lang.php'),
( 'gujarati', 'polish_currency', 'પોલિશ ઝ્લોટી (પીએલએન)', 'main_lang.php'),
( 'gujarati', 'singapore_currency', 'સિંગાપોર ડોલર (એસજીડી)', 'main_lang.php'),
( 'gujarati', 'pound_currency', 'પાઉન્ડ સ્ટર્લિંગ (જીબીપી)', 'main_lang.php'),
( 'gujarati', 'swedish_currency', 'સ્વીડિશ ક્રોના (SEK)', 'main_lang.php'),
( 'gujarati', 'swiss_currency', 'સ્વિસ ફ્રેંક (સીએચએફ)', 'main_lang.php'),
( 'gujarati', 'taiwan_currency', 'તાઇવાન ન્યૂ ડૉલર (TWD)', 'main_lang.php'),
( 'gujarati', 'thai_currency', 'થાઇ બાહ્ટ (THB)', 'main_lang.php'),
( 'gujarati', 'uae_currency', 'યુએઇ દિરહામ (AED)', 'main_lang.php'),
( 'gujarati', 'us_currency', 'યુ.એસ. ડૉલર (યુએસડી)', 'main_lang.php'),
( 'gujarati', 'bangladesh_currency', 'બાંગ્લાદેશ ટાકા (બીડીટી)', 'main_lang.php'),
( 'gujarati', 'bahraini_currency', 'બહેરિન દિનાર (બીએચડી)', 'main_lang.php'),
( 'gujarati', 'chinese_currency', 'ચિની યુઆન રેનમિબી (સીએનવાય)', 'main_lang.php'),
( 'gujarati', 'indian_currency', 'ભારતીય રૂપિયો (આઈએનઆર)', 'main_lang.php'),
( 'gujarati', 'kuwaiti_currency', 'કુવૈત દિનાર (કેડબલ્યુડી)', 'main_lang.php'),
( 'gujarati', 'kenyan_currency', 'કેન્યા શિલિંગ (કેઇએસ)', 'main_lang.php'),
( 'gujarati', 'sri_lankan_currency', 'શ્રીલંકન રૂપિ (એલકેઆર)', 'main_lang.php'),
( 'gujarati', 'mauritius_currency', 'મોરિશિયસ રૂપી (મુર)', 'main_lang.php'),
( 'gujarati', 'nepalese_currency', 'નેપાળી રૂપી (એનપીઆર)', 'main_lang.php'),
( 'gujarati', 'omani_currency', 'ઓમની રિયલ (ઓએમઆર)', 'main_lang.php'),
( 'gujarati', 'qatari_currency', 'કતાર રિયાલ (ક્યુએઆર)', 'main_lang.php'),
( 'gujarati', 'saudi_currency', 'સાઉદી રિયાલ (એસએઆર)', 'main_lang.php'),
( 'gujarati', 'south_african_currency', 'દક્ષિણ આફ્રિકન રૅન્ડ (ZAR)', 'main_lang.php'),
( 'gujarati', 'grace_hours', 'ગ્રેસ અવર્સ', 'main_lang.php'),
( 'gujarati', 'minimum', 'પ્રવેશ માટે ન્યૂનતમ કલાકો', 'main_lang.php'),
( 'gujarati', 'base_charge', 'ન્યૂનતમ કલાકો માટે આધાર ચાર્જ', 'main_lang.php'),
( 'gujarati', 'migration_none_found', 'No migrations were found.', 'migration_lang.php'),
( 'gujarati', 'migration_not_found', 'No migration could be found with the version number: %s.', 'migration_lang.php'),
( 'gujarati', 'migration_sequence_gap', 'There is a gap in the migration sequence near version number: %s.', 'migration_lang.php'),
( 'gujarati', 'migration_multiple_version', 'There are multiple migrations with the same version number: %s.', 'migration_lang.php'),
( 'gujarati', 'migration_missing_up_method', 'The migration class "%s" is missing an "up" method.', 'migration_lang.php'),
( 'gujarati', 'migration_class_doesnt_exist', 'The migration class "%s" could not be found.', 'migration_lang.php'),
( 'gujarati', 'migration_invalid_filename', 'Migration "%s" has an invalid filename.', 'migration_lang.php'),
( 'gujarati', 'migration_missing_down_method', 'The migration class "%s" is missing a "down" method.', 'migration_lang.php'),
( 'gujarati', 'terabyte_abbr', 'TB', 'number_lang.php'),
( 'gujarati', 'gigabyte_abbr', 'GB', 'number_lang.php'),
( 'gujarati', 'kilobyte_abbr', 'KB', 'number_lang.php'),
( 'gujarati', 'bytes', 'Bytes', 'number_lang.php'),
( 'gujarati', 'megabyte_abbr', 'MB', 'number_lang.php'),
( 'gujarati', 'pagination_prev_link', '&lt;', 'pagination_lang.php'),
( 'gujarati', 'pagination_first_link', '&lsaquo; First', 'pagination_lang.php'),
( 'gujarati', 'pagination_next_link', '&gt;', 'pagination_lang.php'),
( 'gujarati', 'pagination_last_link', 'Last &rsaquo;', 'pagination_lang.php'),
( 'gujarati', 'profiler_database', 'DATABASE', 'profiler_lang.php'),
( 'gujarati', 'profiler_controller_info', 'CLASS/METHOD', 'profiler_lang.php'),
( 'gujarati', 'profiler_benchmarks', 'BENCHMARKS', 'profiler_lang.php'),
( 'gujarati', 'profiler_queries', 'QUERIES', 'profiler_lang.php'),
( 'gujarati', 'profiler_get_data', 'GET DATA', 'profiler_lang.php'),
( 'gujarati', 'profiler_post_data', 'POST DATA', 'profiler_lang.php'),
( 'gujarati', 'profiler_uri_string', 'URI STRING', 'profiler_lang.php'),
( 'gujarati', 'profiler_memory_usage', 'MEMORY USAGE', 'profiler_lang.php'),
( 'gujarati', 'profiler_config', 'CONFIG VARIABLES', 'profiler_lang.php'),
( 'gujarati', 'profiler_session_data', 'SESSION DATA', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_db', 'Database driver is not currently loaded', 'profiler_lang.php'),
( 'gujarati', 'profiler_headers', 'HTTP HEADERS', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_post', 'No POST data exists', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_get', 'No GET data exists', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_queries', 'No queries were run', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_uri', 'No URI data exists', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_memory', 'Memory Usage Unavailable', 'profiler_lang.php'),
( 'gujarati', 'profiler_no_profiles', 'No Profile data - all Profiler sections have been disabled.', 'profiler_lang.php'),
( 'gujarati', 'profiler_section_hide', 'Hide', 'profiler_lang.php'),
( 'gujarati', 'profiler_section_show', 'Show', 'profiler_lang.php'),
( 'gujarati', 'profiler_seconds', 'seconds', 'profiler_lang.php'),
( 'gujarati', 'ut_test_name', 'Test Name', 'unit_test_lang.php'),
( 'gujarati', 'ut_test_datatype', 'Test Datatype', 'unit_test_lang.php'),
( 'gujarati', 'ut_res_datatype', 'Expected Datatype', 'unit_test_lang.php'),
( 'gujarati', 'ut_result', 'Result', 'unit_test_lang.php'),
( 'gujarati', 'ut_file', 'File Name', 'unit_test_lang.php'),
( 'gujarati', 'ut_undefined', 'Undefined Test Name', 'unit_test_lang.php'),
( 'gujarati', 'ut_passed', 'Passed', 'unit_test_lang.php'),
( 'gujarati', 'ut_line', 'Line Number', 'unit_test_lang.php'),
( 'gujarati', 'ut_failed', 'Failed', 'unit_test_lang.php'),
( 'gujarati', 'ut_boolean', 'Boolean', 'unit_test_lang.php'),
( 'gujarati', 'ut_float', 'Float', 'unit_test_lang.php'),
( 'gujarati', 'ut_integer', 'Integer', 'unit_test_lang.php'),
( 'gujarati', 'ut_double', 'Float', 'unit_test_lang.php'),
( 'gujarati', 'ut_array', 'Array', 'unit_test_lang.php'),
( 'gujarati', 'ut_string', 'String', 'unit_test_lang.php'),
( 'gujarati', 'ut_object', 'Object', 'unit_test_lang.php'),
( 'gujarati', 'ut_null', 'Null', 'unit_test_lang.php'),
( 'gujarati', 'ut_resource', 'Resource', 'unit_test_lang.php'),
( 'gujarati', 'ut_notes', 'Notes', 'unit_test_lang.php'),
( 'gujarati', 'upload_userfile_not_set', 'Unable to find a post variable called userfile.', 'upload_lang.php'),
( 'gujarati', 'upload_file_exceeds_limit', 'The uploaded file exceeds the maximum allowed size in your PHP configuration file.', 'upload_lang.php'),
( 'gujarati', 'upload_file_exceeds_form_limit', 'The uploaded file exceeds the maximum size allowed by the submission form.', 'upload_lang.php'),
( 'gujarati', 'upload_file_partial', 'The file was only partially uploaded.', 'upload_lang.php'),
( 'gujarati', 'upload_no_temp_directory', 'The temporary folder is missing.', 'upload_lang.php'),
( 'gujarati', 'upload_unable_to_write_file', 'The file could not be written to disk.', 'upload_lang.php'),
( 'gujarati', 'upload_stopped_by_extension', 'The file upload was stopped by extension.', 'upload_lang.php'),
( 'gujarati', 'upload_no_file_selected', 'You did not select a file to upload.', 'upload_lang.php'),
( 'gujarati', 'upload_invalid_filetype', 'The filetype you are attempting to upload is not allowed.', 'upload_lang.php'),
( 'gujarati', 'upload_invalid_filesize', 'The file you are attempting to upload is larger than the permitted size.', 'upload_lang.php'),
( 'gujarati', 'upload_invalid_dimensions', 'The image you are attempting to upload doesn\'t fit into the allowed dimensions.', 'upload_lang.php'),
( 'gujarati', 'upload_destination_error', 'A problem was encountered while attempting to move the uploaded file to the final destination.', 'upload_lang.php'),
( 'gujarati', 'upload_no_filepath', 'The upload path does not appear to be valid.', 'upload_lang.php'),
( 'gujarati', 'upload_no_file_types', 'You have not specified any allowed file types.', 'upload_lang.php'),
( 'gujarati', 'upload_bad_filename', 'The file name you submitted already exists on the server.', 'upload_lang.php'),
( 'gujarati', 'upload_not_writable', 'The upload destination folder does not appear to be writable.', 'upload_lang.php'),
('gujarati', 'enable_patient_account', 'પેશન્ટ એકાઉન્ટ સક્ષમ કરો', 'main_lang.php') ,
('gujarati', 'patient_account_msg', '(તમે ભરતિયું રકમ કરતાં વધુ ચુકવણી લઈ શકશો. પેશન્ટ એકાઉન્ટમાં વધારાની ચુકવણી જાળવવામાં આવશે. આ રકમનો ઉપયોગ આગલી વખતે બિલને સમાયોજિત કરવા માટે કરી શકાય છે)', 'main_lang.php'),
('gujarati', 'all_items', 'બધી વસ્તુઓ', 'main_lang.php') ,
('gujarati', 'all_purchase', 'બધી ખરીદી', 'main_lang.php') ,
('gujarati', 'stock_reports', 'સ્ટોક રિપોર્ટ', 'main_lang.php') ,
('gujarati', 'preferred_size_icon', 'ફેવિકોન પ્રિફર્ડ કદ 16X16', 'main_lang.php') ,
('gujarati', 'favicon', 'ફેવિકોન', 'main_lang.php'),
('gujarati', 'content_section', 'સામગ્રી વિભાગ', 'main_lang.php') ;