ALTER TABLE %dbprefix%invoice ADD currency_symbol VARCHAR(10) NOT NULL;
UPDATE %dbprefix%invoice SET currency_symbol ='Rs.';
ALTER TABLE %dbprefix%bill_detail ADD quantity int(11) NOT NULL;
ALTER TABLE %dbprefix%bill_detail ADD mrp	decimal(10,2)	NOT NULL;
ALTER TABLE %dbprefix%bill_detail ADD type	varchar(25)	NOT NULL;
ALTER TABLE %dbprefix%bill_detail ADD purchase_id     int(11);
ALTER TABLE %dbprefix%payment DROP pay_date;
ALTER TABLE %dbprefix%payment DROP pay_mode;
ALTER TABLE %dbprefix%payment DROP amount;
ALTER TABLE %dbprefix%payment DROP cheque_no;                        
ALTER TABLE %dbprefix%payment ADD patient_id int(11);
ALTER TABLE %dbprefix%payment ADD pay_amount decimal(11,2);
ALTER TABLE %dbprefix%appointments ADD userid int(11) NOT NULL;
ALTER TABLE %dbprefix%appointments ADD status varchar(255) NOT NULL;
ALTER TABLE %dbprefix%patient ADD display_id varchar(12) NOT NULL;
ALTER TABLE %dbprefix%patient ADD followup_date date NOT NULL;
ALTER TABLE %dbprefix%patient ADD reference_by varchar(255) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD display_name varchar(255) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD email varchar(150) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD type varchar(50) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD address_line_1 varchar(150) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD address_line_2 varchar(150) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD city varchar(50) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD state varchar(50) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD postal_code varchar(50) NOT NULL;
ALTER TABLE %dbprefix%contacts ADD country varchar(50) NOT NULL;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.type = %dbprefix%address.type;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.address_line_1 = %dbprefix%address.address_line_1;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.address_line_2 = %dbprefix%address.address_line_2;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.city = %dbprefix%address.city;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.state = %dbprefix%address.state;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.postal_code = %dbprefix%address.postal_code;
UPDATE %dbprefix%contacts INNER JOIN %dbprefix%address ON (%dbprefix%contacts.contact_id = %dbprefix%address.contact_id) SET %dbprefix%contacts.country = %dbprefix%address.country;
ALTER TABLE %dbprefix%visit ADD userid int(11) NOT NULL;
ALTER TABLE %dbprefix%clinic ADD time_interval decimal(11,2) NOT NULL DEFAULT '0.50';
ALTER TABLE %dbprefix%purchase ADD remain_quantity INT NOT NULL;
ALTER TABLE %dbprefix%purchase ADD bill_no varchar(255) NOT NULL;
ALTER TABLE %dbprefix%purchase ADD mrp float(11,2) NOT NULL;
DROP TABLE IF EXISTS %dbprefix%address;
DROP VIEW IF EXISTS %dbprefix%view_address;
DROP VIEW IF EXISTS %dbprefix%view_contacts;
CREATE TABLE IF NOT EXISTS %dbprefix%users ( userid int(11) NOT NULL AUTO_INCREMENT, name varchar(255) DEFAULT NULL, username varchar(16) DEFAULT NULL, password varchar(255) NOT NULL, level varchar(15) NOT NULL,is_active INT(1) NOT NULL DEFAULT '1', PRIMARY KEY (userid), UNIQUE KEY username (username) );
CREATE TABLE IF NOT EXISTS %dbprefix%appointment_log ( appointment_id int(11) NOT NULL,change_date_time varchar(255) NOT NULL,start_time time NOT NULL,from_time time NOT NULL,to_time time NOT NULL,old_status varchar(255) NOT NULL,status varchar(255) NOT NULL,name varchar(255) NOT NULL);
CREATE OR REPLACE VIEW %dbprefix%view_patient AS SELECT patient.patient_id,patient.patient_since, patient.display_id, patient.reference_by, patient.followup_date,contacts.display_name,contacts.contact_id,contacts.first_name,contacts.middle_name,contacts.last_name,contacts.phone_number,contacts.email FROM %dbprefix%patient as patient LEFT JOIN %dbprefix%contacts as contacts ON patient.contact_id = contacts.contact_id;
CREATE OR REPLACE VIEW %dbprefix%view_report AS SELECT appointment.appointment_id,appointment.patient_id,CONCAT(IFNULL(view_patient.first_name,''),' ',IFNULL(view_patient.middle_name,''), ' ',IFNULL(view_patient.last_name,'')) as patient_name,appointment.userid,appointment.appointment_date,min(appointment.start_time) as appointment_time,max(CASE appointment_log.status WHEN 'Waiting' THEN appointment_log.from_time END) as waiting_in,(max(CASE appointment_log.status WHEN 'Consultation' THEN appointment_log.from_time END) - max(CASE appointment_log.status WHEN 'Waiting' THEN appointment_log.from_time END)) as waiting_duration, max(CASE appointment_log.status WHEN 'Consultation' THEN appointment_log.from_time END) as consultation_in, max(CASE appointment_log.status WHEN 'Complete' THEN appointment_log.from_time END) as consultation_out, (max(CASE appointment_log.status WHEN 'Complete' THEN appointment_log.from_time END) - max(CASE appointment_log.status WHEN 'Consultation' THEN appointment_log.from_time END)) as consultation_duration,max(CASE appointment_log.old_status WHEN 'Consultation' THEN timediff(appointment_log.to_time,appointment_log.from_time) END) as waiting_out,max(bill.total_amount) as collection_amount FROM  %dbprefix%appointments as appointment LEFT JOIN %dbprefix%view_patient as view_patient ON appointment.patient_id = view_patient.patient_id LEFT JOIN %dbprefix%bill as bill ON appointment.visit_id = bill.visit_id LEFT JOIN %dbprefix%appointment_log as appointment_log ON appointment.appointment_id = appointment_log.appointment_id GROUP BY appointment.appointment_id,patient_name;
CREATE OR REPLACE VIEW %dbprefix%view_bill AS SELECT bill.bill_id,bill.bill_date,bill.visit_id,users.name AS doctor_name,visit.userid,patient.patient_id,patient.display_id,contacts.first_name,contacts.middle_name,contacts.last_name,bill.total_amount,bill.due_amount FROM %dbprefix%bill AS bill INNER JOIN %dbprefix%visit as visit ON bill.visit_id = visit.visit_id INNER JOIN %dbprefix%users as users ON visit.userid = users.userid INNER JOIN %dbprefix%patient as patient ON bill.patient_id = patient.patient_id INNER JOIN %dbprefix%contacts as contacts ON contacts.contact_id = patient.contact_id;
CREATE OR REPLACE VIEW %dbprefix%view_bill_detail_report AS SELECT bill.bill_id,bill.bill_date,bill.visit_id,bill_detail.particular,bill_detail.amount,visit.userid,CONCAT(view_patient.first_name,' ',view_patient.middle_name, ' ',view_patient.last_name) as patient_name,view_patient.display_id,bill_detail.type FROM %dbprefix%bill as bill LEFT JOIN %dbprefix%bill_detail as bill_detail ON bill_detail.bill_id = bill.bill_id LEFT JOIN %dbprefix%visit as visit ON visit.visit_id = bill.visit_id LEFT JOIN %dbprefix%view_patient as view_patient ON view_patient.patient_id =bill.patient_id;
UPDATE %dbprefix%version SET current_version='0.0.5';