INSERT INTO %dbprefix%contact_details (contact_id,type,detail) SELECT contact_id,'mobile',phone_number FROM %dbprefix%contacts WHERE (phone_number IS NOT NULL AND phone_number != '') AND contact_id IN (SELECT contact_id FROM %dbprefix%patient);
INSERT INTO %dbprefix%contact_details (contact_id,type,detail) SELECT contact_id,'mobile',second_number FROM %dbprefix%contacts WHERE (second_number IS NOT NULL AND second_number != '') AND contact_id IN (SELECT contact_id FROM %dbprefix%patient);
ALTER TABLE %dbprefix%appointments ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%appointment_log ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%bill ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%bill_detail ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%bill_payment_r ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%clinic ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%contacts ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%contact_details ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%data ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%followup ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%invoice ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%modules ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%navigation_menu ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%patient ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%payment ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%payment_transaction ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%receipt_template ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%reference_by ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%todos ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%users ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%user_categories ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%version ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%visit ADD is_deleted INT NULL;
ALTER TABLE %dbprefix%working_days ADD is_deleted INT NULL;

ALTER TABLE %dbprefix%appointments ADD sync_status INT NULL;
ALTER TABLE %dbprefix%appointment_log ADD sync_status INT NULL;
ALTER TABLE %dbprefix%bill ADD sync_status INT NULL;
ALTER TABLE %dbprefix%bill_detail ADD sync_status INT NULL;
ALTER TABLE %dbprefix%bill_payment_r ADD sync_status INT NULL;
ALTER TABLE %dbprefix%clinic ADD sync_status INT NULL;
ALTER TABLE %dbprefix%contacts ADD sync_status INT NULL;
ALTER TABLE %dbprefix%contact_details ADD sync_status INT NULL;
ALTER TABLE %dbprefix%data ADD sync_status INT NULL;
ALTER TABLE %dbprefix%followup ADD sync_status INT NULL;
ALTER TABLE %dbprefix%invoice ADD sync_status INT NULL;
ALTER TABLE %dbprefix%modules ADD sync_status INT NULL;
ALTER TABLE %dbprefix%navigation_menu ADD sync_status INT NULL;
ALTER TABLE %dbprefix%patient ADD sync_status INT NULL;
ALTER TABLE %dbprefix%payment ADD sync_status INT NULL;
ALTER TABLE %dbprefix%payment_transaction ADD sync_status INT NULL;
ALTER TABLE %dbprefix%receipt_template ADD sync_status INT NULL;
ALTER TABLE %dbprefix%reference_by ADD sync_status INT NULL;
ALTER TABLE %dbprefix%todos ADD sync_status INT NULL;
ALTER TABLE %dbprefix%users ADD sync_status INT NULL;
ALTER TABLE %dbprefix%user_categories ADD sync_status INT NULL;
ALTER TABLE %dbprefix%version ADD sync_status INT NULL;
ALTER TABLE %dbprefix%visit ADD sync_status INT NULL;
ALTER TABLE %dbprefix%working_days ADD sync_status INT NULL;

ALTER TABLE %dbprefix%users ADD centers VARCHAR( 50 ) NULL AFTER contact_id;
UPDATE %dbprefix%version SET current_version='0.5.1';